export const kelimeler=[
  { "ingilizce": "abroad", "turkce": "yurt dışı", "okunus": "/əˈbrɔːd/" },
  { "ingilizce": "academy", "turkce": "akademi", "okunus": "/əˈkædəmi/" },
  { "ingilizce": "accommodation", "turkce": "konaklama", "okunus": "/əˌkɒməˈdeɪʃn/" },
  { "ingilizce": "album", "turkce": "albüm", "okunus": "/ˈælbəm/" },
  { "ingilizce": "applicable", "turkce": "uygulanabilir", "okunus": "/əˈplɪkəbl/" },
  { "ingilizce": "arrival", "turkce": "varış", "okunus": "/əˈraɪvl/" },
  { "ingilizce": "bar", "turkce": "bar", "okunus": "/bɑːr/" },
  { "ingilizce": "beard", "turkce": "sakal", "okunus": "/bɪəd/" },
  { "ingilizce": "blind date", "turkce": "görmeden randevulaşma", "okunus": "/ˌblaɪnd ˈdeɪt/" },
  { "ingilizce": "borrow", "turkce": "ödünç almak", "okunus": "/ˈbɒrəʊ/" },
  { "ingilizce": "bubbly", "turkce": "hayat dolu/neşeli", "okunus": "/ˈbʌbli/" },
  { "ingilizce": "busker", "turkce": "sokak çalgıcısı", "okunus": "/ˈbʌskə(r)/" },
  { "ingilizce": "camper van", "turkce": "karavan", "okunus": "/ˈkæmpə væn/" },
  { "ingilizce": "carpenter", "turkce": "marangoz", "okunus": "/ˈkɑːpəntə(r)/" },
  { "ingilizce": "chatty", "turkce": "geveze/konuşkan", "okunus": "/ˈtʃæti/" },
  { "ingilizce": "cheers", "turkce": "şerefe/teşekkürler", "okunus": "/tʃɪəz/" },
  { "ingilizce": "college", "turkce": "kolej/yüksekokul", "okunus": "/ˈkɒlɪdʒ/" },
  { "ingilizce": "couple", "turkce": "çift", "okunus": "/ˈkʌpl/" },
  { "ingilizce": "crazy", "turkce": "çılgın", "okunus": "/ˈkreɪzi/" },
  { "ingilizce": "crazy about", "turkce": "bayılmak (bir şeye)", "okunus": "/ˈkreɪzi əˈbaʊt/" },
  { "ingilizce": "daily", "turkce": "günlük", "okunus": "/ˈdeɪli/" },
  { "ingilizce": "date", "turkce": "tarih/hurma/randevu", "okunus": "/deɪt/" },
  { "ingilizce": "definitely", "turkce": "kesinlikle", "okunus": "/ˈdefɪnətli/" },
  { "ingilizce": "delete", "turkce": "silmek", "okunus": "/dɪˈliːt/" },
  { "ingilizce": "delicious", "turkce": "lezzetli", "okunus": "/dɪˈlɪʃəs/" },
  { "ingilizce": "departure", "turkce": "kalkış", "okunus": "/dɪˈpɑːtʃə(r)/" },
  { "ingilizce": "dietary", "turkce": "diyetle ilgili", "okunus": "/ˈdaɪətəri/" },
  { "ingilizce": "early days", "turkce": "henüz erken", "okunus": "/ˌɜːli ˈdeɪz/" },
  { "ingilizce": "embarrass", "turkce": "utandırmak", "okunus": "/ɪmˈbærəs/" },
  { "ingilizce": "embarrassing", "turkce": "utanç verici", "okunus": "/ɪmˈbærəsɪŋ/" },
  { "ingilizce": "emergency", "turkce": "acil durum", "okunus": "/ɪˈmɜːdʒənsi/" },
  { "ingilizce": "empty", "turkce": "boş", "okunus": "/ˈempti/" },
  { "ingilizce": "excited", "turkce": "heyecanlı", "okunus": "/ɪkˈsaɪtɪd/" },
  { "ingilizce": "fabulous", "turkce": "harika/efsanevi", "okunus": "/ˈfæbjələs/" },
  { "ingilizce": "flatmate", "turkce": "ev arkadaşı", "okunus": "/ˈflætmeɪt/" },
  { "ingilizce": "forever", "turkce": "sonsuza dek", "okunus": "/fərˈevə(r)/" },
  { "ingilizce": "gender", "turkce": "cinsiyet", "okunus": "/ˈdʒendə(r)/" },
  { "ingilizce": "global", "turkce": "küresel", "okunus": "/ˈɡləʊbl/" },
  { "ingilizce": "heavy", "turkce": "ağır/yoğun", "okunus": "/ˈhevi/" },
  { "ingilizce": "hire", "turkce": "kiralamak", "okunus": "/ˈhaɪə(r)/" },
  { "ingilizce": "hostel", "turkce": "pansiyon", "okunus": "/ˈhɒstl/" },
  { "ingilizce": "How do you do?", "turkce": "Memnun oldum (resmi)", "okunus": "/haʊ du ju duː/" },
  { "ingilizce": "I'm afraid", "turkce": "Korkarım ki/Maalesef", "okunus": "/aɪm əˈfreɪd/" },
  { "ingilizce": "improve", "turkce": "geliştirmek", "okunus": "/ɪmˈpruːv/" },
  { "ingilizce": "in common", "turkce": "ortak nokta", "okunus": "/ɪn ˈkɒmən/" },
  { "ingilizce": "journalist", "turkce": "gazeteci", "okunus": "/ˈdʒɜːnəlɪst/" },
  { "ingilizce": "jumper", "turkce": "kazak", "okunus": "/ˈdʒʌmpə(r)/" },
  { "ingilizce": "kind", "turkce": "kibar", "okunus": "/kaɪnd/" },
  { "ingilizce": "kiss", "turkce": "öpmek", "okunus": "/kɪs/" },
  { "ingilizce": "knock over", "turkce": "devirmek/çarpmak", "okunus": "/nɒk ˈəʊvə(r)/" },
  { "ingilizce": "lend", "turkce": "ödünç vermek", "okunus": "/lend/" },
  { "ingilizce": "lose touch", "turkce": "iletişimi koparmak", "okunus": "/luːz tʌtʃ/" },
  { "ingilizce": "marital status", "turkce": "medeni hal", "okunus": "/ˌmærɪtl ˈsteɪtəs/" },
  { "ingilizce": "mean", "turkce": "cimri/kaba", "okunus": "/miːn/" },
  { "ingilizce": "medical condition", "turkce": "tıbbi durum/rahatsızlık", "okunus": "/ˈmedɪkl kənˈdɪʃn/" },
  { "ingilizce": "mess", "turkce": "dağınıklık", "okunus": "/mes/" },
  { "ingilizce": "miss", "turkce": "özlemek/kaçırmak", "okunus": "/mɪs/" },
  { "ingilizce": "mountain", "turkce": "dağ", "okunus": "/ˈmaʊntən/" },
  { "ingilizce": "my pleasure", "turkce": "bir şey değil/zevkliydi", "okunus": "/maɪ ˈpleʒə(r)/" },
  { "ingilizce": "nest", "turkce": "yuva", "okunus": "/nest/" },
  { "ingilizce": "never mind", "turkce": "boşver/önemli değil", "okunus": "/ˈnevə maɪnd/" },
  { "ingilizce": "nickname", "turkce": "lakap", "okunus": "/ˈnɪkneɪm/" },
  { "ingilizce": "no trouble", "turkce": "sorun değil/zahmet değil", "okunus": "/nəʊ ˈtrʌbl/" },
  { "ingilizce": "noise", "turkce": "gürültü", "okunus": "/nɔɪz/" },
  { "ingilizce": "obviously", "turkce": "açıkçası/belli ki", "okunus": "/ˈɒbviəsli/" },
  { "ingilizce": "occupation", "turkce": "meslek", "okunus": "/ˌɒkjuˈpeɪʃn/" },
  { "ingilizce": "pardon", "turkce": "pardon/efendim?", "okunus": "/ˈpɑːdn/" },
  { "ingilizce": "permanent", "turkce": "kalıcı", "okunus": "/ˈpɜːmənənt/" },
  { "ingilizce": "pick up", "turkce": "toplamak/almak", "okunus": "/pɪk ʌp/" },
  { "ingilizce": "pleasure", "turkce": "zevk/memnuniyet", "okunus": "/ˈpleʒə(r)/" },
  { "ingilizce": "postcode", "turkce": "posta kodu", "okunus": "/ˈpəʊstkəʊd/" },
  { "ingilizce": "pretty", "turkce": "güzel/sevimli", "okunus": "/ˈprɪti/" },
  { "ingilizce": "pub", "turkce": "pub/bar", "okunus": "/pʌb/" },
  { "ingilizce": "relationship", "turkce": "ilişki", "okunus": "/rɪˈleɪʃnʃɪp/" },
  { "ingilizce": "reporter", "turkce": "muhabir", "okunus": "/rɪˈpɔːtə(r)/" },
  { "ingilizce": "requirements", "turkce": "gereksinimler", "okunus": "/rɪˈkwaɪəmənts/" },
  { "ingilizce": "rescue", "turkce": "kurtarmak", "okunus": "/ˈreskjuː/" },
  { "ingilizce": "retire", "turkce": "emekli olmak", "okunus": "/rɪˈtaɪə(r)/" },
  { "ingilizce": "reunited", "turkce": "yeniden birleşmiş", "okunus": "/ˌriːjuˈnaɪtɪd/" },
  { "ingilizce": "scholarship", "turkce": "burs", "okunus": "/ˈskɒləʃɪp/" },
  { "ingilizce": "seaside", "turkce": "deniz kenarı", "okunus": "/ˈsiːsaɪd/" },
  { "ingilizce": "secondary school", "turkce": "ortaokul", "okunus": "/ˈsekəndri skuːl/" },
  { "ingilizce": "signature", "turkce": "imza", "okunus": "/ˈsɪɡnətʃə(r)/" },
  { "ingilizce": "single", "turkce": "bekar", "okunus": "/ˈsɪŋɡl/" },
  { "ingilizce": "surname", "turkce": "soyadı", "okunus": "/ˈsɜːneɪm/" },
  { "ingilizce": "surprising", "turkce": "şaşırtıcı", "okunus": "/səˈpraɪzɪŋ/" },
  { "ingilizce": "text", "turkce": "mesaj yazmak", "okunus": "/tekst/" },
  { "ingilizce": "unusual", "turkce": "olağandışı", "okunus": "/ʌnˈjuːʒuəl/" },
  { "ingilizce": "veggie (vegetarian)", "turkce": "vejetaryen", "okunus": "/ˈvedʒi/" },
  { "ingilizce": "wardrobe", "turkce": "gardırop", "okunus": "/ˈwɔːdrəʊb/" },
  { "ingilizce": "well-paid", "turkce": "iyi maaşlı", "okunus": "/ˌwel ˈpeɪd/" },
  { "ingilizce": "wild", "turkce": "vahşi", "okunus": "/waɪld/" },
  { "ingilizce": "wink", "turkce": "göz kırpmak", "okunus": "/wɪŋk/" },
  { "ingilizce": "woolly", "turkce": "yünlü", "okunus": "/ˈwʊli/" },
  { "ingilizce": "worried", "turkce": "endişeli", "okunus": "/ˈwʌrid/" },
  { "ingilizce": "a handful", "turkce": "ele avuca sığmaz", "okunus": "/ə ˈhændfʊl/" },
  { "ingilizce": "absolutely", "turkce": "kesinlikle", "okunus": "/ˈæbsəluːtli/" },
  { "ingilizce": "acting", "turkce": "oyunculuk", "okunus": "/ˈæktɪŋ/" },
  { "ingilizce": "art gallery", "turkce": "sanat galerisi", "okunus": "/ˈɑːt ɡæləri/" },
  { "ingilizce": "beat", "turkce": "yenmek", "okunus": "/biːt/" },
  { "ingilizce": "believe", "turkce": "inanmak", "okunus": "/bɪˈliːv/" },
  { "ingilizce": "brave", "turkce": "cesur", "okunus": "/breɪv/" },
  { "ingilizce": "competitive", "turkce": "rekabetçi", "okunus": "/kəmˈpetətɪv/" },
  { "ingilizce": "confidence", "turkce": "özgüven", "okunus": "/ˈkɒnfɪdəns/" },
  { "ingilizce": "confident", "turkce": "kendinden emin", "okunus": "/ˈkɒnfɪdənt/" },
  { "ingilizce": "countryside", "turkce": "kırsal bölge", "okunus": "/ˈkʌntrisaɪd/" },
  { "ingilizce": "crossword", "turkce": "bulmaca", "okunus": "/ˈkrɒswɜːd/" },
  { "ingilizce": "dependent", "turkce": "bağımlı", "okunus": "/dɪˈpendənt/" },
  { "ingilizce": "despite", "turkce": "-e rağmen", "okunus": "/dɪˈspaɪt/" },
  { "ingilizce": "disagree", "turkce": "katılmamak", "okunus": "/ˌdɪsəˈɡriː/" },
  { "ingilizce": "divorced", "turkce": "boşanmış", "okunus": "/dɪˈvɔːst/" },
  { "ingilizce": "dress", "turkce": "elbise", "okunus": "/dres/" },
  { "ingilizce": "dye", "turkce": "boyamak (saç vb.)", "okunus": "/daɪ/" },
  { "ingilizce": "equally", "turkce": "eşit derecede", "okunus": "/ˈiːkwəli/" },
  { "ingilizce": "experiment", "turkce": "deney yapmak", "okunus": "/ɪkˈsperɪment/" },
  { "ingilizce": "explore", "turkce": "keşfetmek", "okunus": "/ɪkˈsplɔː(r)/" },
  { "ingilizce": "express an opinion", "turkce": "fikir beyan etmek", "okunus": "/ɪkˈspres ən əˈpɪnjən/" },
  { "ingilizce": "fence", "turkce": "çit", "okunus": "/fens/" },
  { "ingilizce": "fight", "turkce": "kavga etmek", "okunus": "/faɪt/" },
  { "ingilizce": "forget", "turkce": "unutmak", "okunus": "/fəˈɡet/" },
  { "ingilizce": "grown-up", "turkce": "yetişkin", "okunus": "/ˌɡrəʊn ˈʌp/" },
  { "ingilizce": "headphones", "turkce": "kulaklık", "okunus": "/ˈhedfəʊnz/" },
  { "ingilizce": "homework", "turkce": "ev ödevi", "okunus": "/ˈhəʊmwɜːk/" },
  { "ingilizce": "hopeless", "turkce": "umutsuz/beceriksiz", "okunus": "/ˈhəʊpləs/" },
  { "ingilizce": "identical", "turkce": "özdeş/tıpatıp aynı", "okunus": "/aɪˈdentɪkl/" },
  { "ingilizce": "ill", "turkce": "hasta", "okunus": "/ɪl/" },
  { "ingilizce": "independent", "turkce": "bağımsız", "okunus": "/ˌɪndɪˈpendənt/" },
  { "ingilizce": "ingredients", "turkce": "malzemeler", "okunus": "/ɪnˈɡriːdiənts/" },
  { "ingilizce": "invite", "turkce": "davet etmek", "okunus": "/ɪnˈvaɪt/" },
  { "ingilizce": "jealous", "turkce": "kıskanç", "okunus": "/ˈdʒeləs/" },
  { "ingilizce": "keep in touch", "turkce": "iletişimi sürdürmek", "okunus": "/kiːp ɪn tʌtʃ/" },
  { "ingilizce": "lazy", "turkce": "tembel", "okunus": "/ˈleɪzi/" },
  { "ingilizce": "lie-in", "turkce": "geç uyanmak", "okunus": "/ˈlaɪ ɪn/" },
  { "ingilizce": "magazine", "turkce": "dergi", "okunus": "/ˌmæɡəˈziːn/" },
  { "ingilizce": "neighbour", "turkce": "komşu", "okunus": "/ˈneɪbə(r)/" },
  { "ingilizce": "notice", "turkce": "fark etmek", "okunus": "/ˈnəʊtɪs/" },
  { "ingilizce": "pay no attention", "turkce": "aldırış etmemek", "okunus": "/peɪ nəʊ əˈtenʃn/" },
  { "ingilizce": "personality", "turkce": "kişilik", "okunus": "/ˌpɜːsəˈnæləti/" },
  { "ingilizce": "play", "turkce": "oyun (tiyatro)", "okunus": "/pleɪ/" },
  { "ingilizce": "polite", "turkce": "kibar", "okunus": "/pəˈlaɪt/" },
  { "ingilizce": "postman", "turkce": "postacı", "okunus": "/ˈpəʊstmən/" },
  { "ingilizce": "practice", "turkce": "pratik", "okunus": "/ˈpræktɪs/" },
  { "ingilizce": "puzzle", "turkce": "yapboz/bulmaca", "okunus": "/ˈpʌzl/" },
  { "ingilizce": "quiz", "turkce": "kısa sınav", "okunus": "/kwɪz/" },
  { "ingilizce": "recipe", "turkce": "tarif", "okunus": "/ˈresəpi/" },
  { "ingilizce": "rich", "turkce": "zengin", "okunus": "/rɪtʃ/" },
  { "ingilizce": "saxophone", "turkce": "saksafon", "okunus": "/ˈsæksəfəʊn/" },
  { "ingilizce": "scary", "turkce": "korkutucu", "okunus": "/ˈskeəri/" },
  { "ingilizce": "score", "turkce": "skor/puan", "okunus": "/skɔː(r)/" },
  { "ingilizce": "shy", "turkce": "utangaç", "okunus": "/ʃaɪ/" },
  { "ingilizce": "smart", "turkce": "akıllı/şık", "okunus": "/smɑːt/" },
  { "ingilizce": "solitary", "turkce": "yalnız", "okunus": "/ˈsɒlətri/" },
  { "ingilizce": "solve", "turkce": "çözmek", "okunus": "/sɒlv/" },
  { "ingilizce": "suit", "turkce": "yakışmak", "okunus": "/suːt/" },
  { "ingilizce": "suspicious", "turkce": "şüpheli/kuşkulu", "okunus": "/səˈspɪʃəs/" },
  { "ingilizce": "takeaway", "turkce": "paket servis", "okunus": "/ˈteɪkəweɪ/" },
  { "ingilizce": "tattoo", "turkce": "dövme", "okunus": "/təˈtuː/" },
  { "ingilizce": "twins", "turkce": "ikizler", "okunus": "/twɪnz/" },
  { "ingilizce": "usually", "turkce": "genellikle", "okunus": "/ˈjuːʒuəli/" },
  { "ingilizce": "village", "turkce": "köy", "okunus": "/ˈvɪlɪdʒ/" },
  { "ingilizce": "accident", "turkce": "kaza", "okunus": "/ˈæksɪdənt/" },
  { "ingilizce": "afford", "turkce": "maddi gücü yetmek", "okunus": "/əˈfɔːd/" },
  { "ingilizce": "air conditioning", "turkce": "klima", "okunus": "/ˈeə kəndɪʃnɪŋ/" },
  { "ingilizce": "angry", "turkce": "kızgın", "okunus": "/ˈæŋɡri/" },
  { "ingilizce": "appointment", "turkce": "randevu", "okunus": "/əˈpɔɪntmənt/" },
  { "ingilizce": "assassin", "turkce": "suikastçı", "okunus": "/əˈsæsɪn/" },
  { "ingilizce": "bang", "turkce": "çarpmak/gümlemek", "okunus": "/bæŋ/" },
  { "ingilizce": "boss", "turkce": "patron", "okunus": "/bɒs/" },
  { "ingilizce": "breathe", "turkce": "nefes almak", "okunus": "/briːð/" },
  { "ingilizce": "bricklayer", "turkce": "duvar ustası", "okunus": "/ˈbrɪkleɪə(r)/" },
  { "ingilizce": "bullet", "turkce": "kurşun/mermi", "okunus": "/ˈbʊlɪt/" },
  { "ingilizce": "capture", "turkce": "yakalamak", "okunus": "/ˈkæptʃə(r)/" },
  { "ingilizce": "cardboard box", "turkce": "karton kutu", "okunus": "/ˈkɑːdbɔːd bɒks/" },
  { "ingilizce": "checkout", "turkce": "kasa (market)", "okunus": "/ˈtʃekaʊt/" },
  { "ingilizce": "club together", "turkce": "para birleştirmek", "okunus": "/klʌb təˈɡedə(r)/" },
  { "ingilizce": "coast", "turkce": "sahil", "okunus": "/kəʊst/" },
  { "ingilizce": "continually", "turkce": "sürekli", "okunus": "/kənˈtɪnjuəli/" },
  { "ingilizce": "covered", "turkce": "kaplı/örtülü", "okunus": "/ˈkʌvəd/" },
  { "ingilizce": "creep", "turkce": "sinsice yaklaşmak/sürünmek", "okunus": "/kriːp/" },
  { "ingilizce": "curse", "turkce": "lanetlemek/küfretmek", "okunus": "/kɜːs/" },
  { "ingilizce": "curtain", "turkce": "perde", "okunus": "/ˈkɜːtn/" },
  { "ingilizce": "cut", "turkce": "kesmek", "okunus": "/kʌt/" },
  { "ingilizce": "darkness", "turkce": "karanlık", "okunus": "/ˈdɑːknəs/" },
  { "ingilizce": "description", "turkce": "tanımlama", "okunus": "/dɪˈskrɪpʃn/" },
  { "ingilizce": "die", "turkce": "ölmek", "okunus": "/daɪ/" },
  { "ingilizce": "disappear", "turkce": "kaybolmak", "okunus": "/ˌdɪsəˈpɪə(r)/" },
  { "ingilizce": "enjoy", "turkce": "tadını çıkarmak", "okunus": "/ɪnˈdʒɔɪ/" },
  { "ingilizce": "escape", "turkce": "kaçmak", "okunus": "/ɪˈskeɪp/" },
  { "ingilizce": "exactly", "turkce": "tam olarak", "okunus": "/ɪɡˈzæktli/" },
  { "ingilizce": "excellent", "turkce": "mükemmel", "okunus": "/ˈeksələnt/" },
  { "ingilizce": "expiry date", "turkce": "son kullanma tarihi", "okunus": "/ɪkˈspaɪəri deɪt/" },
  { "ingilizce": "feathers", "turkce": "tüyler", "okunus": "/ˈfeðəz/" },
  { "ingilizce": "feed", "turkce": "beslemek", "okunus": "/fiːd/" },
  { "ingilizce": "finishing line", "turkce": "bitiş çizgisi", "okunus": "/ˈfɪnɪʃɪŋ laɪn/" },
  { "ingilizce": "fluently", "turkce": "akıcı bir şekilde", "okunus": "/ˈfluːəntli/" },
  { "ingilizce": "furious", "turkce": "öfkeli", "okunus": "/ˈfjʊəriəs/" },
  { "ingilizce": "generously", "turkce": "cömertçe", "okunus": "/ˈdʒenərəsli/" },
  { "ingilizce": "gradually", "turkce": "yavaş yavaş", "okunus": "/ˈɡrædʒuəli/" },
  { "ingilizce": "guess", "turkce": "tahmin etmek", "okunus": "/ɡes/" },
  { "ingilizce": "guiltily", "turkce": "suçlu bir şekilde", "okunus": "/ˈɡɪltɪli/" },
  { "ingilizce": "gun", "turkce": "silah", "okunus": "/ɡʌn/" },
  { "ingilizce": "gunshot", "turkce": "silah sesi", "okunus": "/ˈɡʌnʃɒt/" },
  { "ingilizce": "happily", "turkce": "mutlulukla", "okunus": "/ˈhæpɪli/" },
  { "ingilizce": "headfirst", "turkce": "kafa üstü", "okunus": "/ˌhedˈfɜːst/" },
  { "ingilizce": "headline", "turkce": "manşet", "okunus": "/ˈhedlaɪn/" },
  { "ingilizce": "honk", "turkce": "korna çalmak", "okunus": "/hɒŋk/" },
  { "ingilizce": "injured", "turkce": "yaralı", "okunus": "/ˈɪndʒəd/" },
  { "ingilizce": "invitation", "turkce": "davetiye", "okunus": "/ˌɪnvɪˈteɪʃn/" },
  { "ingilizce": "luxurious", "turkce": "lüks", "okunus": "/lʌɡˈʒʊəriəs/" },
  { "ingilizce": "midnight", "turkce": "gece yarısı", "okunus": "/ˈmɪdnaɪt/" },
  { "ingilizce": "motorway", "turkce": "otoyol", "okunus": "/ˈməʊtəweɪ/" },
  { "ingilizce": "oil", "turkce": "yağ/petrol", "okunus": "/ɔɪl/" },
  { "ingilizce": "painter", "turkce": "ressam/boyacı", "okunus": "/ˈpeɪntə(r)/" },
  { "ingilizce": "passionately", "turkce": "tutkuyla", "okunus": "/ˈpæʃənətli/" },
  { "ingilizce": "payday", "turkce": "maaş günü", "okunus": "/ˈpeɪdeɪ/" },
  { "ingilizce": "peacefully", "turkce": "huzurla", "okunus": "/ˈpiːsfəli/" },
  { "ingilizce": "penguin", "turkce": "penguen", "okunus": "/ˈpeŋɡwɪn/" },
  { "ingilizce": "pillow", "turkce": "yastık", "okunus": "/ˈpɪləʊ/" },
  { "ingilizce": "poem", "turkce": "şiir", "okunus": "/ˈpəʊɪm/" },
  { "ingilizce": "portrait", "turkce": "portre", "okunus": "/ˈpɔːtreɪt/" },
  { "ingilizce": "refuse", "turkce": "reddetmek", "okunus": "/rɪˈfjuːz/" },
  { "ingilizce": "robber", "turkce": "soyguncu", "okunus": "/ˈrɒbə(r)/" },
  { "ingilizce": "sardine", "turkce": "sardalya", "okunus": "/ˌsɑːˈdiːn/" },
  { "ingilizce": "seashore", "turkce": "deniz kıyısı", "okunus": "/ˈsiːʃɔː(r)/" },
  { "ingilizce": "secret agent", "turkce": "gizli ajan", "okunus": "/ˌsiːkrət ˈeɪdʒənt/" },
  { "ingilizce": "sick", "turkce": "hasta", "okunus": "/sɪk/" },
  { "ingilizce": "spot", "turkce": "fark etmek/görmek", "okunus": "/spɒt/" },
  { "ingilizce": "spy", "turkce": "casus", "okunus": "/spaɪ/" },
  { "ingilizce": "staff", "turkce": "personel", "okunus": "/stɑːf/" },
  { "ingilizce": "stall", "turkce": "tezgah/stand", "okunus": "/stɔːl/" },
  { "ingilizce": "strong", "turkce": "güçlü", "okunus": "/strɒŋ/" },
  { "ingilizce": "studio", "turkce": "stüdyo", "okunus": "/ˈstjuːdiəʊ/" },
  { "ingilizce": "tail", "turkce": "kuyruk", "okunus": "/teɪl/" },
  { "ingilizce": "tear", "turkce": "gözyaşı", "okunus": "/tɪə(r)/" },
  { "ingilizce": "thump", "turkce": "güm güm vurmak", "okunus": "/θʌmp/" },
  { "ingilizce": "tiny", "turkce": "küçücük", "okunus": "/ˈtaɪni/" },
  { "ingilizce": "triathlon", "turkce": "triatlon", "okunus": "/traɪˈæθlɒn/" },
  { "ingilizce": "urgently", "turkce": "acilen", "okunus": "/ˈɜːdʒəntli/" },
  { "ingilizce": "vase", "turkce": "vazo", "okunus": "/vɑːz/" },
  { "ingilizce": "wallet", "turkce": "cüzdan", "okunus": "/ˈwɒlɪt/" },
  { "ingilizce": "whisper", "turkce": "fısıldamak", "okunus": "/ˈwɪspə(r)/" },
  { "ingilizce": "alcohol", "turkce": "alkol", "okunus": "/ˈælkəhɒl/" },
  { "ingilizce": "attraction", "turkce": "cazibe/turistik yer", "okunus": "/əˈtrækʃn/" },
  { "ingilizce": "bake", "turkce": "fırında pişirmek", "okunus": "/beɪk/" },
  { "ingilizce": "baking", "turkce": "pişirme", "okunus": "/ˈbeɪkɪŋ/" },
  { "ingilizce": "bitterly", "turkce": "acı bir şekilde", "okunus": "/ˈbɪtəli/" },
  { "ingilizce": "bunch", "turkce": "salkım/demet", "okunus": "/bʌntʃ/" },
  { "ingilizce": "can", "turkce": "konserve kutusu", "okunus": "/kæn/" },
  { "ingilizce": "caramel", "turkce": "karamel", "okunus": "/ˈkærəmel/" },
  { "ingilizce": "chef", "turkce": "şef", "okunus": "/ʃef/" },
  { "ingilizce": "chewing gum", "turkce": "sakız", "okunus": "/ˈtʃuːɪŋ ɡʌm/" },
  { "ingilizce": "chillies", "turkce": "acı biberler", "okunus": "/ˈtʃɪliz/" },
  { "ingilizce": "complaint", "turkce": "şikayet", "okunus": "/kəmˈpleɪnt/" },
  { "ingilizce": "contented", "turkce": "hoşnut/memnun", "okunus": "/kənˈtentɪd/" },
  { "ingilizce": "cookies", "turkce": "kurabiyeler", "okunus": "/ˈkʊkiz/" },
  { "ingilizce": "crisps", "turkce": "cips", "okunus": "/krɪsps/" },
  { "ingilizce": "curry", "turkce": "köri/körili yemek", "okunus": "/ˈkʌri/" },
  { "ingilizce": "decaf", "turkce": "kafeinsiz", "okunus": "/ˈdiːkæf/" },
  { "ingilizce": "delicatessen", "turkce": "şarküteri", "okunus": "/ˌdelɪkəˈtesn/" },
  { "ingilizce": "discover", "turkce": "keşfetmek", "okunus": "/dɪˈskʌvə(r)/" },
  { "ingilizce": "dough", "turkce": "hamur", "okunus": "/dəʊ/" },
  { "ingilizce": "engineer", "turkce": "mühendis", "okunus": "/ˌendʒɪˈnɪə(r)/" },
  { "ingilizce": "flavour", "turkce": "aroma/tat", "okunus": "/ˈfleɪvə(r)/" },
  { "ingilizce": "fork", "turkce": "çatal", "okunus": "/fɔːk/" },
  { "ingilizce": "french fries", "turkce": "patates kızartması", "okunus": "/frentʃ fraɪz/" },
  { "ingilizce": "fridge", "turkce": "buzdolabı", "okunus": "/frɪdʒ/" },
  { "ingilizce": "fry", "turkce": "kızartmak", "okunus": "/fraɪ/" },
  { "ingilizce": "fussy", "turkce": "titiz/zor beğenen", "okunus": "/ˈfʌsi/" },
  { "ingilizce": "glasses", "turkce": "gözlük", "okunus": "/ˈɡlɑːsɪz/" },
  { "ingilizce": "guest", "turkce": "misafir", "okunus": "/ɡest/" },
  { "ingilizce": "hike", "turkce": "doğa yürüyüşü yapmak", "okunus": "/haɪk/" },
  { "ingilizce": "ice lolly", "turkce": "meyveli buz", "okunus": "/ˈaɪs lɒli/" },
  { "ingilizce": "ID", "turkce": "kimlik", "okunus": "/ˌaɪ ˈdiː/" },
  { "ingilizce": "increase", "turkce": "artış/artmak", "okunus": "/ɪnˈkriːs/" },
  { "ingilizce": "industrial", "turkce": "endüstriyel", "okunus": "/ɪnˈdʌstriəl/" },
  { "ingilizce": "invent", "turkce": "icat etmek", "okunus": "/ɪnˈvent/" },
  { "ingilizce": "lick", "turkce": "yalamak", "okunus": "/lɪk/" },
  { "ingilizce": "lift", "turkce": "asansör", "okunus": "/lɪft/" },
  { "ingilizce": "loaf", "turkce": "somun (ekmek)", "okunus": "/ləʊf/" },
  { "ingilizce": "lose", "turkce": "kaybetmek", "okunus": "/luːz/" },
  { "ingilizce": "match", "turkce": "kibrit", "okunus": "/mætʃ/" },
  { "ingilizce": "melt", "turkce": "erimek", "okunus": "/melt/" },
  { "ingilizce": "newsagent's", "turkce": "gazete bayii", "okunus": "/ˈnjuːzeɪdʒənts/" },
  { "ingilizce": "off-licence", "turkce": "tekel bayii", "okunus": "/ˈɒf laɪsns/" },
  { "ingilizce": "olive", "turkce": "zeytin", "okunus": "/ˈɒlɪv/" },
  { "ingilizce": "omelette", "turkce": "omlet", "okunus": "/ˈɒmlət/" },
  { "ingilizce": "original", "turkce": "orijinal", "okunus": "/əˈrɪdʒənl/" },
  { "ingilizce": "out of this world", "turkce": "harika/muhteşem", "okunus": "/aʊt əv ðɪs wɜːld/" },
  { "ingilizce": "packet", "turkce": "paket", "okunus": "/ˈpækɪt/" },
  { "ingilizce": "patent", "turkce": "patent", "okunus": "/ˈpeɪtnt/" },
  { "ingilizce": "petrol", "turkce": "benzin", "okunus": "/ˈpetrəl/" },
  { "ingilizce": "popular", "turkce": "popüler", "okunus": "/ˈpɒpjələ(r)/" },
  { "ingilizce": "porch", "turkce": "veranda", "okunus": "/pɔːtʃ/" },
  { "ingilizce": "postcard", "turkce": "kartpostal", "okunus": "/ˈpəʊstkɑːd/" },
  { "ingilizce": "powder", "turkce": "toz", "okunus": "/ˈpaʊdə(r)/" },
  { "ingilizce": "publish", "turkce": "yayımlamak", "okunus": "/ˈpʌblɪʃ/" },
  { "ingilizce": "receive", "turkce": "almak/teslim almak", "okunus": "/rɪˈsiːv/" },
  { "ingilizce": "roast chicken", "turkce": "fırında tavuk", "okunus": "/rəʊst ˈtʃɪkɪn/" },
  { "ingilizce": "secret", "turkce": "sır", "okunus": "/ˈsiːkrət/" },
  { "ingilizce": "shopkeeper", "turkce": "dükkan sahibi", "okunus": "/ˈʃɒpkiːpə(r)/" },
  { "ingilizce": "slice", "turkce": "dilim", "okunus": "/slaɪs/" },
  { "ingilizce": "sparkling", "turkce": "gazlı (içecek)", "okunus": "/ˈspɑːklɪŋ/" },
  { "ingilizce": "spectacular", "turkce": "görkemli", "okunus": "/spekˈtækjələ(r)/" },
  { "ingilizce": "spicy", "turkce": "baharatlı", "okunus": "/ˈspaɪsi/" },
  { "ingilizce": "spinach", "turkce": "ıspanak", "okunus": "/ˈspɪnɪtʃ/" },
  { "ingilizce": "spoon", "turkce": "kaşık", "okunus": "/spuːn/" },
  { "ingilizce": "spoonful", "turkce": "kaşık dolusu", "okunus": "/ˈspuːnfʊl/" },
  { "ingilizce": "sprouts", "turkce": "Brüksel lahanası", "okunus": "/spraʊts/" },
  { "ingilizce": "strange", "turkce": "tuhaf", "okunus": "/streɪndʒ/" },
  { "ingilizce": "successful", "turkce": "başarılı", "okunus": "/səkˈsesfl/" },
  { "ingilizce": "supply", "turkce": "tedarik/kaynak", "okunus": "/səˈplaɪ/" },
  { "ingilizce": "taste", "turkce": "tatmak", "okunus": "/teɪst/" },
  { "ingilizce": "taste buds", "turkce": "tat tomurcukları", "okunus": "/teɪst bʌdz/" },
  { "ingilizce": "thin", "turkce": "ince", "okunus": "/θɪn/" },
  { "ingilizce": "tissues", "turkce": "kağıt mendil", "okunus": "/ˈtɪʃuːz/" },
  { "ingilizce": "tongue", "turkce": "dil", "okunus": "/tʌŋ/" },
  { "ingilizce": "tuna", "turkce": "ton balığı", "okunus": "/ˈtjuːnə/" },
  { "ingilizce": "unexpected", "turkce": "beklenmedik", "okunus": "/ˌʌnɪkˈspektɪd/" },
  { "ingilizce": "wax paper", "turkce": "yağlı kağıt", "okunus": "/wæks ˈpeɪpə(r)/" },
  { "ingilizce": "whisky", "turkce": "viski", "okunus": "/ˈwɪski/" },
  { "ingilizce": "advertising", "turkce": "reklamcılık", "okunus": "/ˈædvətaɪzɪŋ/" },
  { "ingilizce": "ambition", "turkce": "hırs", "okunus": "/æmˈbɪʃn/" },
  { "ingilizce": "apply", "turkce": "başvurmak", "okunus": "/əˈplaɪ/" },
  { "ingilizce": "arrest", "turkce": "tutuklamak", "okunus": "/əˈrest/" },
  { "ingilizce": "as usual", "turkce": "her zamanki gibi", "okunus": "/əz ˈjuːʒuəl/" },
  { "ingilizce": "attack", "turkce": "saldırı", "okunus": "/əˈtæk/" },
  { "ingilizce": "average", "turkce": "ortalama", "okunus": "/ˈævərɪdʒ/" },
  { "ingilizce": "award", "turkce": "ödül", "okunus": "/əˈwɔːd/" },
  { "ingilizce": "ballet", "turkce": "bale", "okunus": "/ˈbæleɪ/" },
  { "ingilizce": "break", "turkce": "mola/kırmak", "okunus": "/breɪk/" },
  { "ingilizce": "brilliant", "turkce": "parlak/zeki", "okunus": "/ˈbrɪliənt/" },
  { "ingilizce": "bully", "turkce": "zorbalık etmek", "okunus": "/ˈbʊli/" },
  { "ingilizce": "career", "turkce": "kariyer", "okunus": "/kəˈrɪə(r)/" },
  { "ingilizce": "carry out", "turkce": "gerçekleştirmek", "okunus": "/ˈkæri aʊt/" },
  { "ingilizce": "catch up", "turkce": "yakalamak/telafi etmek", "okunus": "/kætʃ ʌp/" },
  { "ingilizce": "competition", "turkce": "yarışma", "okunus": "/ˌkɒmpəˈtɪʃn/" },
  { "ingilizce": "course", "turkce": "kurs/ders", "okunus": "/kɔːs/" },
  { "ingilizce": "court", "turkce": "mahkeme/kort", "okunus": "/kɔːt/" },
  { "ingilizce": "crash", "turkce": "çarpmak", "okunus": "/kræʃ/" },
  { "ingilizce": "create", "turkce": "yaratmak", "okunus": "/kriˈeɪt/" },
  { "ingilizce": "cyber criminal", "turkce": "siber suçlu", "okunus": "/ˈsaɪbə krɪmɪnl/" },
  { "ingilizce": "debts", "turkce": "borçlar", "okunus": "/dets/" },
  { "ingilizce": "definite", "turkce": "kesin", "okunus": "/ˈdefɪnət/" },
  { "ingilizce": "develop", "turkce": "geliştirmek", "okunus": "/dɪˈveləp/" },
  { "ingilizce": "disappointed", "turkce": "hayal kırıklığına uğramış", "okunus": "/ˌdɪsəˈpɔɪntɪd/" },
  { "ingilizce": "doubt", "turkce": "şüphe etmek", "okunus": "/daʊt/" },
  { "ingilizce": "earn", "turkce": "para kazanmak", "okunus": "/ɜːn/" },
  { "ingilizce": "exam", "turkce": "sınav", "okunus": "/ɪɡˈzæm/" },
  { "ingilizce": "fall out", "turkce": "küsüşmek/ayrılmak", "okunus": "/fɔːl aʊt/" },
  { "ingilizce": "fashion", "turkce": "moda", "okunus": "/ˈfæʃn/" },
  { "ingilizce": "favourite", "turkce": "favori", "okunus": "/ˈfeɪvərɪt/" },
  { "ingilizce": "fed up", "turkce": "bıkmış", "okunus": "/fed ʌp/" },
  { "ingilizce": "get on (well) with", "turkce": "iyi geçinmek", "okunus": "/ɡet ɒn wel wɪð/" },
  { "ingilizce": "give up", "turkce": "pes etmek/bırakmak", "okunus": "/ɡɪv ʌp/" },
  { "ingilizce": "grandparents", "turkce": "büyükanne ve büyükbaba", "okunus": "/ˈɡrænpeərənts/" },
  { "ingilizce": "grow up", "turkce": "büyümek", "okunus": "/ɡrəʊ ʌp/" },
  { "ingilizce": "hacker", "turkce": "bilgisayar korsanı", "okunus": "/ˈhækə(r)/" },
  { "ingilizce": "homesick", "turkce": "ev özlemi çeken", "okunus": "/ˈhəʊmsɪk/" },
  { "ingilizce": "idiomatic", "turkce": "deyimsel", "okunus": "/ˌɪdiəˈmætɪk/" },
  { "ingilizce": "landscape design", "turkce": "peyzaj tasarımı", "okunus": "/ˈlændskeɪp dɪzaɪn/" },
  { "ingilizce": "leap", "turkce": "sıçramak", "okunus": "/liːp/" },
  { "ingilizce": "literal", "turkce": "kelimesi kelimesine", "okunus": "/ˈlɪtərəl/" },
  { "ingilizce": "look after", "turkce": "göz kulak olmak", "okunus": "/lʊk ˈɑːftə(r)/" },
  { "ingilizce": "look forward to", "turkce": "dört gözle beklemek", "okunus": "/lʊk ˈfɔːwəd tu/" },
  { "ingilizce": "look up", "turkce": "sözlükten bakmak/yukarı bakmak", "okunus": "/lʊk ʌp/" },
  { "ingilizce": "miserable", "turkce": "sefil/mutsuz", "okunus": "/ˈmɪzrəbl/" },
  { "ingilizce": "notorious", "turkce": "kötü şöhretli", "okunus": "/nəʊˈtɔːriəs/" },
  { "ingilizce": "owe", "turkce": "borçlu olmak", "okunus": "/əʊ/" },
  { "ingilizce": "paramedic", "turkce": "sağlık görevlisi", "okunus": "/ˌpærəˈmedɪk/" },
  { "ingilizce": "pay back", "turkce": "geri ödemek", "okunus": "/peɪ bæk/" },
  { "ingilizce": "principal", "turkce": "baş/asıl", "okunus": "/ˈprɪnsəpl/" },
  { "ingilizce": "prison", "turkce": "hapishane", "okunus": "/ˈprɪzn/" },
  { "ingilizce": "program", "turkce": "program", "okunus": "/ˈprəʊɡræm/" },
  { "ingilizce": "run out of", "turkce": "tükenmek/bitmek", "okunus": "/rʌn aʊt əv/" },
  { "ingilizce": "slum", "turkce": "gecekondu mahallesi", "okunus": "/slʌm/" },
  { "ingilizce": "soul", "turkce": "ruh", "okunus": "/səʊl/" },
  { "ingilizce": "stressful", "turkce": "stresli", "okunus": "/ˈstresfl/" },
  { "ingilizce": "suitable", "turkce": "uygun", "okunus": "/ˈsuːtəbl/" },
  { "ingilizce": "take off", "turkce": "çıkarmak (kıyafet)/havalanmak", "okunus": "/teɪk ɒf/" },
  { "ingilizce": "take up", "turkce": "başlamak (hobi vb.)", "okunus": "/teɪk ʌp/" },
  { "ingilizce": "talent", "turkce": "yetenek", "okunus": "/ˈtælənt/" },
  { "ingilizce": "throw away", "turkce": "atmak", "okunus": "/θrəʊ əˈweɪ/" },
  { "ingilizce": "traffic jam", "turkce": "trafik sıkışıklığı", "okunus": "/ˈtræfɪk dʒæm/" },
  { "ingilizce": "try on", "turkce": "denemek (kıyafet)", "okunus": "/traɪ ɒn/" },
  { "ingilizce": "turn off", "turkce": "kapatmak", "okunus": "/tɜːn ɒf/" },
  { "ingilizce": "turn round", "turkce": "arkasını dönmek", "okunus": "/tɜːn raʊnd/" },
  { "ingilizce": "username", "turkce": "kullanıcı adı", "okunus": "/ˈjuːzəneɪm/" },
  { "ingilizce": "virus", "turkce": "virüs", "okunus": "/ˈvaɪrəs/" },
  { "ingilizce": "ability", "turkce": "yetenek", "okunus": "/əˈbɪləti/" },
  { "ingilizce": "accountant", "turkce": "muhasebeci", "okunus": "/əˈkaʊntənt/" },
  { "ingilizce": "actor", "turkce": "aktör", "okunus": "/ˈæktə(r)/" },
  { "ingilizce": "adviser", "turkce": "danışman", "okunus": "/ədˈvaɪzə(r)/" },
  { "ingilizce": "afraid", "turkce": "korkmuş", "okunus": "/əˈfreɪd/" },
  { "ingilizce": "amazing", "turkce": "harika/şaşırtıcı", "okunus": "/əˈmeɪzɪŋ/" },
  { "ingilizce": "ancestor", "turkce": "ata", "okunus": "/ˈænsestə(r)/" },
  { "ingilizce": "ancient", "turkce": "antik", "okunus": "/ˈeɪnʃənt/" },
  { "ingilizce": "announce", "turkce": "duyurmak", "okunus": "/əˈnaʊns/" },
  { "ingilizce": "aqueduct", "turkce": "su kemeri", "okunus": "/ˈækwɪdʌkt/" },
  { "ingilizce": "archaeology", "turkce": "arkeoloji", "okunus": "/ˌɑːkiˈɒlədʒi/" },
  { "ingilizce": "argument", "turkce": "tartışma", "okunus": "/ˈɑːɡjumənt/" },
  { "ingilizce": "armies", "turkce": "ordular", "okunus": "/ˈɑːmiz/" },
  { "ingilizce": "artist", "turkce": "sanatçı", "okunus": "/ˈɑːtɪst/" },
  { "ingilizce": "assistant", "turkce": "asistan", "okunus": "/əˈsɪstənt/" },
  { "ingilizce": "avoid", "turkce": "kaçınmak", "okunus": "/əˈvɔɪd/" },
  { "ingilizce": "biography", "turkce": "biyografi", "okunus": "/baɪˈɒɡrəfi/" },
  { "ingilizce": "catch", "turkce": "yakalamak", "okunus": "/kætʃ/" },
  { "ingilizce": "celebrity", "turkce": "ünlü kişi", "okunus": "/səˈlebrəti/" },
  { "ingilizce": "charity", "turkce": "hayır kurumu", "okunus": "/ˈtʃærəti/" },
  { "ingilizce": "cleaner", "turkce": "temizlikçi", "okunus": "/ˈkliːnə(r)/" },
  { "ingilizce": "coin", "turkce": "madeni para", "okunus": "/kɔɪn/" },
  { "ingilizce": "contact", "turkce": "temas/iletişim", "okunus": "/ˈkɒntækt/" },
  { "ingilizce": "currency", "turkce": "para birimi", "okunus": "/ˈkʌrənsi/" },
  { "ingilizce": "date", "turkce": "flört etmek/tarih", "okunus": "/deɪt/" },
  { "ingilizce": "death", "turkce": "ölüm", "okunus": "/deθ/" },
  { "ingilizce": "destroy", "turkce": "yok etmek", "okunus": "/dɪˈstrɔɪ/" },
  { "ingilizce": "discovery", "turkce": "keşif", "okunus": "/dɪˈskʌvəri/" },
  { "ingilizce": "distant", "turkce": "uzak", "okunus": "/ˈdɪstənt/" },
  { "ingilizce": "dressmaker", "turkce": "terzi", "okunus": "/ˈdresmeɪkə(r)/" },
  { "ingilizce": "economist", "turkce": "ekonomist", "okunus": "/ɪˈkɒnəmɪst/" },
  { "ingilizce": "electrician", "turkce": "elektrikçi", "okunus": "/ɪˌlekˈtrɪʃn/" },
  { "ingilizce": "empire", "turkce": "imparatorluk", "okunus": "/ˈempaɪə(r)/" },
  { "ingilizce": "environment", "turkce": "çevre", "okunus": "/ɪnˈvaɪrənmənt/" },
  { "ingilizce": "execute", "turkce": "idam etmek/yürütmek", "okunus": "/ˈeksɪkjuːt/" },
  { "ingilizce": "exhibition", "turkce": "sergi", "okunus": "/ˌeksɪˈbɪʃn/" },
  { "ingilizce": "expense", "turkce": "masraf", "okunus": "/ɪkˈspens/" },
  { "ingilizce": "fame", "turkce": "şöhret", "okunus": "/feɪm/" },
  { "ingilizce": "footsteps", "turkce": "ayak izleri", "okunus": "/ˈfʊtsteps/" },
  { "ingilizce": "foreign", "turkce": "yabancı", "okunus": "/ˈfɒrən/" },
  { "ingilizce": "glove", "turkce": "eldiven", "okunus": "/ɡlʌv/" },
  { "ingilizce": "government", "turkce": "hükümet", "okunus": "/ˈɡʌvənmənt/" },
  { "ingilizce": "homeless", "turkce": "evsiz", "okunus": "/ˈhəʊmləs/" },
  { "ingilizce": "interpreter", "turkce": "tercüman", "okunus": "/ɪnˈtɜːprətə(r)/" },
  { "ingilizce": "invade", "turkce": "istila etmek", "okunus": "/ɪnˈveɪd/" },
  { "ingilizce": "inventor", "turkce": "mucit", "okunus": "/ɪnˈventə(r)/" },
  { "ingilizce": "join", "turkce": "katılmak", "okunus": "/dʒɔɪn/" },
  { "ingilizce": "kitten", "turkce": "kedi yavrusu", "okunus": "/ˈkɪtn/" },
  { "ingilizce": "landmines", "turkce": "mayınlar", "okunus": "/ˈlændmaɪnz/" },
  { "ingilizce": "leprosy", "turkce": "cüzzam", "okunus": "/ˈleprəsi/" },
  { "ingilizce": "lifetime", "turkce": "ömür boyu", "okunus": "/ˈlaɪftaɪm/" },
  { "ingilizce": "minced meat", "turkce": "kıyma", "okunus": "/mɪnst miːt/" },
  { "ingilizce": "minefield", "turkce": "mayın tarlası", "okunus": "/ˈmaɪnfiːld/" },
  { "ingilizce": "musician", "turkce": "müzisyen", "okunus": "/mjuˈzɪʃn/" },
  { "ingilizce": "ordinary", "turkce": "sıradan", "okunus": "/ˈɔːdnri/" },
  { "ingilizce": "orphan", "turkce": "yetim", "okunus": "/ˈɔːfn/" },
  { "ingilizce": "passion", "turkce": "tutku", "okunus": "/ˈpæʃn/" },
  { "ingilizce": "patron", "turkce": "hami/destekçi", "okunus": "/ˈpeɪtrən/" },
  { "ingilizce": "pharaoh", "turkce": "firavun", "okunus": "/ˈfeərəʊ/" },
  { "ingilizce": "politician", "turkce": "politikacı", "okunus": "/ˌpɒləˈtɪʃn/" },
  { "ingilizce": "professor", "turkce": "profesör", "okunus": "/prəˈfesə(r)/" },
  { "ingilizce": "protester", "turkce": "protestocu", "okunus": "/prəˈtestə(r)/" },
  { "ingilizce": "public", "turkce": "halka açık/kamu", "okunus": "/ˈpʌblɪk/" },
  { "ingilizce": "recently", "turkce": "son zamanlarda", "okunus": "/ˈriːsntli/" },
  { "ingilizce": "refugees", "turkce": "mülteciler", "okunus": "/ˌrefjuˈdʒiːz/" },
  { "ingilizce": "regularly", "turkce": "düzenli olarak", "okunus": "/ˈreɡjələli/" },
  { "ingilizce": "reminder", "turkce": "hatırlatıcı", "okunus": "/rɪˈmaɪndə(r)/" },
  { "ingilizce": "research", "turkce": "araştırma", "okunus": "/rɪˈsɜːtʃ/" },
  { "ingilizce": "reservation", "turkce": "rezervasyon", "okunus": "/ˌrezəˈveɪʃn/" },
  { "ingilizce": "set up", "turkce": "kurmak", "okunus": "/set ʌp/" },
  { "ingilizce": "sewage", "turkce": "kanalizasyon", "okunus": "/ˈsuːɪdʒ/" },
  { "ingilizce": "shelter", "turkce": "barınak", "okunus": "/ˈʃeltə(r)/" },
  { "ingilizce": "shipyard", "turkce": "tersane", "okunus": "/ˈʃɪpjɑːd/" },
  { "ingilizce": "soldier", "turkce": "asker", "okunus": "/ˈsəʊldʒə(r)/" },
  { "ingilizce": "solo artist", "turkce": "solo sanatçı", "okunus": "/ˈsəʊləʊ ɑːtɪst/" },
  { "ingilizce": "straight", "turkce": "düz", "okunus": "/streɪt/" },
  { "ingilizce": "taxes", "turkce": "vergiler", "okunus": "/tæksɪz/" },
  { "ingilizce": "tent", "turkce": "çadır", "okunus": "/tent/" },
  { "ingilizce": "tomb", "turkce": "mezar", "okunus": "/tuːm/" },
  { "ingilizce": "underpants", "turkce": "külot/iç çamaşırı", "okunus": "/ˈʌndəpænts/" },
  { "ingilizce": "victim", "turkce": "kurban", "okunus": "/ˈvɪktɪm/" },
  { "ingilizce": "wide", "turkce": "geniş", "okunus": "/waɪd/" },
  { "ingilizce": "wildlife", "turkce": "vahşi yaşam", "okunus": "/ˈwaɪldlaɪf/" },
  { "ingilizce": "adore", "turkce": "tapmak/çok sevmek", "okunus": "/əˈdɔː(r)/" },
  { "ingilizce": "bridge", "turkce": "köprü", "okunus": "/brɪdʒ/" },
  { "ingilizce": "bright", "turkce": "parlak", "okunus": "/braɪt/" },
  { "ingilizce": "building", "turkce": "bina", "okunus": "/ˈbɪldɪŋ/" },
  { "ingilizce": "calm", "turkce": "sakin", "okunus": "/kɑːm/" },
  { "ingilizce": "capture", "turkce": "yakalamak", "okunus": "/ˈkæptʃə(r)/" },
  { "ingilizce": "collection", "turkce": "koleksiyon", "okunus": "/kəˈlekʃn/" },
  { "ingilizce": "composer", "turkce": "besteci", "okunus": "/kəmˈpəʊzə(r)/" },
  { "ingilizce": "concert", "turkce": "konser", "okunus": "/ˈkɒnsət/" },
  { "ingilizce": "concert hall", "turkce": "konser salonu", "okunus": "/ˈkɒnsət hɔːl/" },
  { "ingilizce": "cosmopolitan", "turkce": "kozmopolit", "okunus": "/ˌkɒzməˈpɒlɪtən/" },
  { "ingilizce": "dirty", "turkce": "kirli", "okunus": "/ˈdɜːti/" },
  { "ingilizce": "experience", "turkce": "tecrübe", "okunus": "/ɪkˈspɪəriəns/" },
  { "ingilizce": "factory", "turkce": "fabrika", "okunus": "/ˈfæktri/" },
  { "ingilizce": "fierce", "turkce": "şiddetli/vahşi", "okunus": "/fɪəs/" },
  { "ingilizce": "fireplace", "turkce": "şömine", "okunus": "/ˈfaɪəpleɪs/" },
  { "ingilizce": "friendly", "turkce": "dost canlısı", "okunus": "/ˈfrendli/" },
  { "ingilizce": "glad", "turkce": "memnun", "okunus": "/ɡlæd/" },
  { "ingilizce": "gorgeous", "turkce": "muhteşem", "okunus": "/ˈɡɔːdʒəs/" },
  { "ingilizce": "iron", "turkce": "demir", "okunus": "/ˈaɪən/" },
  { "ingilizce": "jungle", "turkce": "orman (balta girmemiş)", "okunus": "/ˈdʒʌŋɡl/" },
  { "ingilizce": "lightning", "turkce": "şimşek", "okunus": "/ˈlaɪtnɪŋ/" },
  { "ingilizce": "mood", "turkce": "ruh hali", "okunus": "/muːd/" },
  { "ingilizce": "mysterious", "turkce": "gizemli", "okunus": "/mɪˈstɪəriəs/" },
  { "ingilizce": "negative", "turkce": "olumsuz", "okunus": "/ˈneɡətɪv/" },
  { "ingilizce": "nightlife", "turkce": "gece hayatı", "okunus": "/ˈnaɪtlaɪf/" },
  { "ingilizce": "opposite", "turkce": "karşı/zıt", "okunus": "/ˈɒpəzɪt/" },
  { "ingilizce": "out of focus", "turkce": "odaklanmamış/bulanık", "okunus": "/aʊt əv ˈfəʊkəs/" },
  { "ingilizce": "parcel", "turkce": "koli/paket", "okunus": "/ˈpɑːsl/" },
  { "ingilizce": "photographer", "turkce": "fotoğrafçı", "okunus": "/fəˈtɒɡrəfə(r)/" },
  { "ingilizce": "pleased", "turkce": "memnun", "okunus": "/pliːzd/" },
  { "ingilizce": "population", "turkce": "nüfus", "okunus": "/ˌpɒpjuˈleɪʃn/" },
  { "ingilizce": "pretend", "turkce": "gibi yapmak", "okunus": "/prɪˈtend/" },
  { "ingilizce": "proud", "turkce": "gururlu", "okunus": "/praʊd/" },
  { "ingilizce": "qualified", "turkce": "nitelikli", "okunus": "/ˈkwɒlɪfaɪd/" },
  { "ingilizce": "rediscover", "turkce": "yeniden keşfetmek", "okunus": "/ˌriːdɪˈskʌvə(r)/" },
  { "ingilizce": "reliable", "turkce": "güvenilir", "okunus": "/rɪˈlaɪəbl/" },
  { "ingilizce": "rude", "turkce": "kaba", "okunus": "/ruːd/" },
  { "ingilizce": "salary", "turkce": "maaş", "okunus": "/ˈsæləri/" },
  { "ingilizce": "salty", "turkce": "tuzlu", "okunus": "/ˈsɔːlti/" },
  { "ingilizce": "screen saver", "turkce": "ekran koruyucu", "okunus": "/ˈskriːn seɪvə(r)/" },
  { "ingilizce": "sculptor", "turkce": "heykeltıraş", "okunus": "/ˈskʌlptə(r)/" },
  { "ingilizce": "shadow", "turkce": "gölge", "okunus": "/ˈʃædəʊ/" },
  { "ingilizce": "skyscraper", "turkce": "gökdelen", "okunus": "/ˈskaɪskreɪpə(r)/" },
  { "ingilizce": "specialize", "turkce": "uzmanlaşmak", "okunus": "/ˈspeʃəlaɪz/" },
  { "ingilizce": "steel", "turkce": "çelik", "okunus": "/stiːl/" },
  { "ingilizce": "storm", "turkce": "fırtına", "okunus": "/stɔːm/" },
  { "ingilizce": "stupid", "turkce": "aptal", "okunus": "/ˈstjuːpɪd/" },
  { "ingilizce": "terrified", "turkce": "dehşete düşmüş", "okunus": "/ˈterɪfaɪd/" },
  { "ingilizce": "thunder", "turkce": "gök gürültüsü", "okunus": "/ˈθʌndə(r)/" },
  { "ingilizce": "tour", "turkce": "tur", "okunus": "/tʊə(r)/" },
  { "ingilizce": "turtle", "turkce": "kaplumbağa", "okunus": "/ˈtɜːtl/" },
  { "ingilizce": "unique", "turkce": "benzersiz", "okunus": "/juˈniːk/" },
  { "ingilizce": "view", "turkce": "manzara", "okunus": "/vjuː/" },
  { "ingilizce": "virtual", "turkce": "sanal", "okunus": "/ˈvɜːtʃuəl/" },
  { "ingilizce": "waste", "turkce": "israf etmek/atık", "okunus": "/weɪst/" },
  { "ingilizce": "well-known", "turkce": "iyi bilinen", "okunus": "/ˌwel ˈnəʊn/" },
  { "ingilizce": "ache", "turkce": "ağrı/sızı", "okunus": "/eɪk/" },
  { "ingilizce": "advertisement", "turkce": "reklam", "okunus": "/ədˈvɜːtɪsmənt/" },
  { "ingilizce": "advice", "turkce": "tavsiye", "okunus": "/ədˈvaɪs/" },
  { "ingilizce": "allergy", "turkce": "alerji", "okunus": "/ˈælədʒi/" },
  { "ingilizce": "ambulance", "turkce": "ambulans", "okunus": "/ˈæmbjələns/" },
  { "ingilizce": "ankle", "turkce": "ayak bileği", "okunus": "/ˈæŋkl/" },
  { "ingilizce": "application form", "turkce": "başvuru formu", "okunus": "/ˌæplɪˈkeɪʃn fɔːm/" },
  { "ingilizce": "archery", "turkce": "okçuluk", "okunus": "/ˈɑːtʃəri/" },
  { "ingilizce": "arm", "turkce": "kol", "okunus": "/ɑːm/" },
  { "ingilizce": "audition", "turkce": "seçme (oyunculuk)", "okunus": "/ɔːˈdɪʃn/" },
  { "ingilizce": "be sick", "turkce": "hasta olmak/kusmak", "okunus": "/bi sɪk/" },
  { "ingilizce": "belt", "turkce": "kemer", "okunus": "/belt/" },
  { "ingilizce": "bite", "turkce": "ısırmak", "okunus": "/baɪt/" },
  { "ingilizce": "blow", "turkce": "üflemek", "okunus": "/bləʊ/" },
  { "ingilizce": "body", "turkce": "vücut", "okunus": "/ˈbɒdi/" },
  { "ingilizce": "boot", "turkce": "bot", "okunus": "/buːt/" },
  { "ingilizce": "boxing", "turkce": "boks", "okunus": "/ˈbɒksɪŋ/" },
  { "ingilizce": "cap", "turkce": "şapka", "okunus": "/kæp/" },
  { "ingilizce": "chariot", "turkce": "savaş arabası", "okunus": "/ˈtʃæriət/" },
  { "ingilizce": "chat", "turkce": "sohbet etmek", "okunus": "/tʃæt/" },
  { "ingilizce": "coach", "turkce": "koç/otobüs", "okunus": "/kəʊtʃ/" },
  { "ingilizce": "cold", "turkce": "soğuk algınlığı", "okunus": "/kəʊld/" },
  { "ingilizce": "couch", "turkce": "kanepe", "okunus": "/kaʊtʃ/" },
  { "ingilizce": "cough", "turkce": "öksürmek", "okunus": "/kɒf/" },
  { "ingilizce": "crash diet", "turkce": "şok diyet", "okunus": "/kræʃ ˈdaɪət/" },
  { "ingilizce": "depressing", "turkce": "bunalımlı", "okunus": "/dɪˈpresɪŋ/" },
  { "ingilizce": "desk", "turkce": "sıra/masa", "okunus": "/desk/" },
  { "ingilizce": "diarrhoea", "turkce": "ishal", "okunus": "/ˌdaɪəˈriːə/" },
  { "ingilizce": "easy-going", "turkce": "uyumlu/rahat", "okunus": "/ˌiːzi ˈɡəʊɪŋ/" },
  { "ingilizce": "equipment", "turkce": "ekipman", "okunus": "/ɪˈkwɪpmənt/" },
  { "ingilizce": "exercise", "turkce": "egzersiz", "okunus": "/ˈeksəsaɪz/" },
  { "ingilizce": "eye", "turkce": "göz", "okunus": "/aɪ/" },
  { "ingilizce": "feet", "turkce": "ayaklar", "okunus": "/fiːt/" },
  { "ingilizce": "fever", "turkce": "ateş", "okunus": "/ˈfiːvə(r)/" },
  { "ingilizce": "finger", "turkce": "parmak", "okunus": "/ˈfɪŋɡə(r)/" },
  { "ingilizce": "fit", "turkce": "formda", "okunus": "/fɪt/" },
  { "ingilizce": "fitness routine", "turkce": "fitness rutini", "okunus": "/ˈfɪtnəs ruːtiːn/" },
  { "ingilizce": "flight attendant", "turkce": "kabin memuru", "okunus": "/ˈflaɪt ətendənt/" },
  { "ingilizce": "flu", "turkce": "grip", "okunus": "/fluː/" },
  { "ingilizce": "food poisoning", "turkce": "gıda zehirlenmesi", "okunus": "/ˈfuːd pɔɪzənɪŋ/" },
  { "ingilizce": "gentle", "turkce": "nazik", "okunus": "/ˈdʒentl/" },
  { "ingilizce": "gland", "turkce": "bez (vücutta)", "okunus": "/ɡlænd/" },
  { "ingilizce": "goggles", "turkce": "koruyucu gözlük", "okunus": "/ˈɡɒɡlz/" },
  { "ingilizce": "gymnastics", "turkce": "jimnastik", "okunus": "/dʒɪmˈnæstɪks/" },
  { "ingilizce": "hand", "turkce": "el", "okunus": "/hænd/" },
  { "ingilizce": "head", "turkce": "baş", "okunus": "/hed/" },
  { "ingilizce": "helmet", "turkce": "kask", "okunus": "/ˈhelmɪt/" },
  { "ingilizce": "high heels", "turkce": "yüksek topuklar", "okunus": "/haɪ hiːlz/" },
  { "ingilizce": "hold your breath", "turkce": "nefesini tutmak", "okunus": "/həʊld jɔː(r) breθ/" },
  { "ingilizce": "hoodie", "turkce": "kapüşonlu", "okunus": "/ˈhʊdi/" },
  { "ingilizce": "hurt", "turkce": "incinmek/acımak", "okunus": "/hɜːt/" },
  { "ingilizce": "injury", "turkce": "sakatlık", "okunus": "/ˈɪndʒəri/" },
  { "ingilizce": "jacket", "turkce": "ceket", "okunus": "/ˈdʒækɪt/" },
  { "ingilizce": "jeans", "turkce": "kot pantolon", "okunus": "/dʒiːnz/" },
  { "ingilizce": "knee", "turkce": "diz", "okunus": "/niː/" },
  { "ingilizce": "leggings", "turkce": "tayt", "okunus": "/ˈleɡɪŋz/" },
  { "ingilizce": "leg", "turkce": "bacak", "okunus": "/leɡ/" },
  { "ingilizce": "liquid", "turkce": "sıvı", "okunus": "/ˈlɪkwɪd/" },
  { "ingilizce": "lose weight", "turkce": "kilo vermek", "okunus": "/luːz weɪt/" },
  { "ingilizce": "martial art", "turkce": "dövüş sanatı", "okunus": "/ˌmɑːʃl ˈɑːt/" },
  { "ingilizce": "mental", "turkce": "zihinsel", "okunus": "/ˈmentl/" },
  { "ingilizce": "mind", "turkce": "zihin", "okunus": "/maɪnd/" },
  { "ingilizce": "necessary", "turkce": "gerekli", "okunus": "/ˈnesəsəri/" },
  { "ingilizce": "neck", "turkce": "boyun", "okunus": "/nek/" },
  { "ingilizce": "on the spot", "turkce": "yerinde/hemen", "okunus": "/ɒn ðə spɒt/" },
  { "ingilizce": "physical", "turkce": "fiziksel", "okunus": "/ˈfɪzɪkl/" },
  { "ingilizce": "prescribe", "turkce": "reçete yazmak", "okunus": "/prɪˈskraɪb/" },
  { "ingilizce": "prescription", "turkce": "reçete", "okunus": "/prɪˈskrɪpʃn/" },
  { "ingilizce": "put on weight", "turkce": "kilo almak", "okunus": "/pʊt ɒn weɪt/" },
  { "ingilizce": "rehydrate", "turkce": "su kaybını gidermek", "okunus": "/ˌriːhaɪˈdreɪt/" },
  { "ingilizce": "risky", "turkce": "riskli", "okunus": "/ˈrɪski/" },
  { "ingilizce": "role", "turkce": "rol", "okunus": "/rəʊl/" },
  { "ingilizce": "sandals", "turkce": "sandalet", "okunus": "/ˈsændlz/" },
  { "ingilizce": "scarf", "turkce": "atkı", "okunus": "/skɑːf/" },
  { "ingilizce": "sensitive", "turkce": "hassas", "okunus": "/ˈsensətɪv/" },
  { "ingilizce": "shave", "turkce": "tıraş olmak", "okunus": "/ʃeɪv/" },
  { "ingilizce": "shirt", "turkce": "gömlek", "okunus": "/ʃɜːt/" },
  { "ingilizce": "shorts", "turkce": "şort", "okunus": "/ʃɔːts/" },
  { "ingilizce": "shoulder", "turkce": "omuz", "okunus": "/ˈʃəʊldə(r)/" },
  { "ingilizce": "skateboarding", "turkce": "kaykay", "okunus": "/ˈskeɪtbɔːdɪŋ/" },
  { "ingilizce": "skip", "turkce": "atlamak (öğün vb.)", "okunus": "/skɪp/" },
  { "ingilizce": "skirt", "turkce": "etek", "okunus": "/skɜːt/" },
  { "ingilizce": "slippery", "turkce": "kaygan", "okunus": "/ˈslɪpəri/" },
  { "ingilizce": "sneeze", "turkce": "hapşırmak", "okunus": "/sniːz/" },
  { "ingilizce": "socks", "turkce": "çorap", "okunus": "/sɒks/" },
  { "ingilizce": "sore throat", "turkce": "boğaz ağrısı", "okunus": "/sɔː(r) θrəʊt/" },
  { "ingilizce": "sports vest", "turkce": "spor atleti", "okunus": "/spɔːts vest/" },
  { "ingilizce": "sprain", "turkce": "burkmak", "okunus": "/spreɪn/" },
  { "ingilizce": "stuff", "turkce": "şeyler/eşya", "okunus": "/stʌf/" },
  { "ingilizce": "stuntwoman", "turkce": "kadın dublör", "okunus": "/ˈstʌntwʊmən/" },
  { "ingilizce": "suit", "turkce": "takım elbise", "okunus": "/suːt/" },
  { "ingilizce": "sunglasses", "turkce": "güneş gözlüğü", "okunus": "/ˈsʌnɡlɑːsɪz/" },
  { "ingilizce": "surfboard", "turkce": "sörf tahtası", "okunus": "/ˈsɜːfbɔːd/" },
  { "ingilizce": "surfer", "turkce": "sörfçü", "okunus": "/ˈsɜːfə(r)/" },
  { "ingilizce": "swallow", "turkce": "yutmak", "okunus": "/ˈswɒləʊ/" },
  { "ingilizce": "swimsuit", "turkce": "mayo", "okunus": "/ˈswɪmsuːt/" },
  { "ingilizce": "swollen", "turkce": "şişmiş", "okunus": "/ˈswəʊlən/" },
  { "ingilizce": "sword", "turkce": "kılıç", "okunus": "/sɔːd/" },
  { "ingilizce": "temperature", "turkce": "sıcaklık/ateş", "okunus": "/ˈtemprətʃə(r)/" },
  { "ingilizce": "tie", "turkce": "kravat", "okunus": "/taɪ/" },
  { "ingilizce": "toe", "turkce": "ayak parmağı", "okunus": "/təʊ/" },
  { "ingilizce": "tracksuit", "turkce": "eşofman", "okunus": "/ˈtræksuːt/" },
  { "ingilizce": "train", "turkce": "antrenman yapmak", "okunus": "/treɪn/" },
  { "ingilizce": "trainers", "turkce": "spor ayakkabı", "okunus": "/ˈtreɪnəz/" },
  { "ingilizce": "truck", "turkce": "kamyon", "okunus": "/trʌk/" },
  { "ingilizce": "T-shirt", "turkce": "tişört", "okunus": "/ˈtiː ʃɜːt/" },
  { "ingilizce": "uniform", "turkce": "üniforma", "okunus": "/ˈjuːnɪfɔːm/" },
  { "ingilizce": "waist", "turkce": "bel", "okunus": "/weɪst/" },
  { "ingilizce": "warm up", "turkce": "ısınmak", "okunus": "/wɔːm ʌp/" },
  { "ingilizce": "watch", "turkce": "kol saati", "okunus": "/wɒtʃ/" },
  { "ingilizce": "wave", "turkce": "dalga", "okunus": "/weɪv/" },
  { "ingilizce": "wheel", "turkce": "tekerlek", "okunus": "/wiːl/" },
  { "ingilizce": "wrist", "turkce": "bilek", "okunus": "/rɪst/" },
  { "ingilizce": "annoyed", "turkce": "rahatsız olmuş", "okunus": "/əˈnɔɪd/" },
  { "ingilizce": "atomic bomb", "turkce": "atom bombası", "okunus": "/əˈtɒmɪk bɒm/" },
  { "ingilizce": "audience", "turkce": "seyirci", "okunus": "/ˈɔːdiəns/" },
  { "ingilizce": "bark", "turkce": "havlamak", "okunus": "/bɑːk/" },
  { "ingilizce": "behave", "turkce": "davranmak", "okunus": "/bɪˈheɪv/" },
  { "ingilizce": "being", "turkce": "varlık", "okunus": "/ˈbiːɪŋ/" },
  { "ingilizce": "chase", "turkce": "kovalamak", "okunus": "/tʃeɪs/" },
  { "ingilizce": "clap", "turkce": "alkışlamak", "okunus": "/klæp/" },
  { "ingilizce": "complex", "turkce": "karmaşık", "okunus": "/ˈkɒmpleks/" },
  { "ingilizce": "doll", "turkce": "oyuncak bebek", "okunus": "/dɒl/" },
  { "ingilizce": "graduate", "turkce": "mezun olmak", "okunus": "/ˈɡrædʒueɪt/" },
  { "ingilizce": "graveyard", "turkce": "mezarlık", "okunus": "/ˈɡreɪvjɑːd/" },
  { "ingilizce": "heartbroken", "turkce": "kalbi kırık", "okunus": "/ˈhɑːtbrəʊkən/" },
  { "ingilizce": "lecture", "turkce": "ders/konferans", "okunus": "/ˈlektʃə(r)/" },
  { "ingilizce": "literature", "turkce": "edebiyat", "okunus": "/ˈlɪtrətʃə(r)/" },
  { "ingilizce": "lock", "turkce": "kilitlemek", "okunus": "/lɒk/" },
  { "ingilizce": "lonely", "turkce": "yalnız", "okunus": "/ˈləʊnli/" },
  { "ingilizce": "memory", "turkce": "hafıza/anı", "okunus": "/ˈmeməri/" },
  { "ingilizce": "monster", "turkce": "canavar", "okunus": "/ˈmɒnstə(r)/" },
  { "ingilizce": "moral", "turkce": "kıssadan hisse/ahlak", "okunus": "/ˈmɒrəl/" },
  { "ingilizce": "naughty", "turkce": "yaramaz", "okunus": "/ˈnɔːti/" },
  { "ingilizce": "nervous", "turkce": "gergin", "okunus": "/ˈnɜːvəs/" },
  { "ingilizce": "novel", "turkce": "roman", "okunus": "/ˈnɒvl/" },
  { "ingilizce": "overjoyed", "turkce": "aşırı mutlu", "okunus": "/ˌəʊvəˈdʒɔɪd/" },
  { "ingilizce": "poor", "turkce": "fakir", "okunus": "/pɔː(r)/" },
  { "ingilizce": "possession", "turkce": "sahiplik/eşya", "okunus": "/pəˈzeʃn/" },
  { "ingilizce": "sack", "turkce": "çuval", "okunus": "/sæk/" },
  { "ingilizce": "shake", "turkce": "sallamak/titremek", "okunus": "/ʃeɪk/" },
  { "ingilizce": "simple", "turkce": "basit", "okunus": "/ˈsɪmpl/" },
  { "ingilizce": "society", "turkce": "toplum", "okunus": "/səˈsaɪəti/" },
  { "ingilizce": "stranger", "turkce": "yabancı", "okunus": "/ˈstreɪndʒə(r)/" },
  { "ingilizce": "stressed", "turkce": "stresli", "okunus": "/strest/" },
  { "ingilizce": "swap", "turkce": "takas etmek", "okunus": "/swɒp/" },
  { "ingilizce": "ugly", "turkce": "çirkin", "okunus": "/ˈʌɡli/" },
  { "ingilizce": "upset", "turkce": "üzgün", "okunus": "/ʌpˈset/" },
  { "ingilizce": "wise", "turkce": "bilge", "okunus": "/waɪz/" },
  { "ingilizce": "yard", "turkce": "avlu/yarda", "okunus": "/jɑːd/" },
  { "ingilizce": "addicted", "turkce": "bağımlı", "okunus": "/əˈdɪktɪd/" },
  { "ingilizce": "artificial intelligence", "turkce": "yapay zeka", "okunus": "/ˌɑːtɪfɪʃl ɪnˈtelɪdʒəns/" },
  { "ingilizce": "ballpoint pen", "turkce": "tükenmez kalem", "okunus": "/ˈbɔːlpɔɪnt pen/" },
  { "ingilizce": "breath", "turkce": "nefes", "okunus": "/breθ/" },
  { "ingilizce": "broadcast", "turkce": "yayın yapmak", "okunus": "/ˈbrɔːdkɑːst/" },
  { "ingilizce": "chew", "turkce": "çiğnemek", "okunus": "/tʃuː/" },
  { "ingilizce": "chum", "turkce": "kafa dengi arkadaş", "okunus": "/tʃʌm/" },
  { "ingilizce": "disadvantage", "turkce": "dezavantaj", "okunus": "/ˌdɪsədˈvɑːntɪdʒ/" },
  { "ingilizce": "export", "turkce": "ihraç etmek", "okunus": "/ɪkˈspɔːt/" },
  { "ingilizce": "fan", "turkce": "hayran/taraftar", "okunus": "/fæn/" },
  { "ingilizce": "flood", "turkce": "sel basmak/taşmak", "okunus": "/flʌd/" },
  { "ingilizce": "football ground", "turkce": "futbol sahası", "okunus": "/ˈfʊtbɔːl ɡraʊnd/" },
  { "ingilizce": "found", "turkce": "kurmak", "okunus": "/faʊnd/" },
  { "ingilizce": "freshen", "turkce": "tazelemek", "okunus": "/ˈfreʃn/" },
  { "ingilizce": "genius", "turkce": "dahi", "okunus": "/ˈdʒiːniəs/" },
  { "ingilizce": "glory", "turkce": "şan/şeref", "okunus": "/ˈɡlɔːri/" },
  { "ingilizce": "hand-held", "turkce": "elde taşınan", "okunus": "/hænd held/" },
  { "ingilizce": "invention", "turkce": "icat", "okunus": "/ɪnˈvenʃn/" },
  { "ingilizce": "kill", "turkce": "öldürmek", "okunus": "/kɪl/" },
  { "ingilizce": "landline", "turkce": "sabit hat", "okunus": "/ˈlændlaɪn/" },
  { "ingilizce": "launch", "turkce": "fırlatmak/başlatmak", "okunus": "/lɔːntʃ/" },
  { "ingilizce": "logo", "turkce": "logo", "okunus": "/ˈləʊɡəʊ/" },
  { "ingilizce": "master", "turkce": "uzmanlaşmak", "okunus": "/ˈmɑːstə(r)/" },
  { "ingilizce": "private", "turkce": "özel", "okunus": "/ˈpraɪvət/" },
  { "ingilizce": "put someone through", "turkce": "telefonu bağlamak", "okunus": "/pʊt ˈsʌmwʌn θruː/" },
  { "ingilizce": "respond", "turkce": "yanıt vermek", "okunus": "/rɪˈspɒnd/" },
  { "ingilizce": "rubber", "turkce": "kauçuk/silgi", "okunus": "/ˈrʌbə(r)/" },
  { "ingilizce": "simplicity", "turkce": "basitlik", "okunus": "/sɪmˈplɪsəti/" },
  { "ingilizce": "skeleton", "turkce": "iskelet", "okunus": "/ˈskelɪtn/" },
  { "ingilizce": "software", "turkce": "yazılım", "okunus": "/ˈsɒftweə(r)/" },
  { "ingilizce": "statistics", "turkce": "istatistik", "okunus": "/stəˈtɪstɪks/" },
  { "ingilizce": "tag", "turkce": "etiketlemek", "okunus": "/tæɡ/" },
  { "ingilizce": "tree sap", "turkce": "ağaç özü", "okunus": "/triː sæp/" },
  { "ingilizce": "trillion", "turkce": "trilyon", "okunus": "/ˈtrɪljən/" },
  { "ingilizce": "trophy", "turkce": "kupa/ödül", "okunus": "/ˈtrəʊfi/" },
  { "ingilizce": "valuable", "turkce": "değerli", "okunus": "/ˈvæljuəbl/" },
  { "ingilizce": "version", "turkce": "versiyon", "okunus": "/ˈvɜːʃn/" },
  { "ingilizce": "waste time", "turkce": "zaman harcamak", "okunus": "/weɪst taɪm/" },
  { "ingilizce": "accidentally", "turkce": "kazara", "okunus": "/ˌæksɪˈdentəli/" },
  { "ingilizce": "anniversary", "turkce": "yıl dönümü", "okunus": "/ˌænɪˈvɜːsəri/" },
  { "ingilizce": "appreciate", "turkce": "takdir etmek", "okunus": "/əˈpriːʃieɪt/" },
  { "ingilizce": "astronomer", "turkce": "astronom", "okunus": "/əˈstrɒnəmə(r)/" },
  { "ingilizce": "bridesmaid", "turkce": "nedime", "okunus": "/ˈbraɪdzmeɪd/" },
  { "ingilizce": "cabbage", "turkce": "lahana", "okunus": "/ˈkæbɪdʒ/" },
  { "ingilizce": "collector", "turkce": "koleksiyoncu", "okunus": "/kəˈlektə(r)/" },
  { "ingilizce": "commemorative", "turkce": "anma/hatıra", "okunus": "/kəˈmemərətɪv/" },
  { "ingilizce": "cope", "turkce": "başa çıkmak", "okunus": "/kəʊp/" },
  { "ingilizce": "demand", "turkce": "talep etmek", "okunus": "/dɪˈmɑːnd/" },
  { "ingilizce": "demanding", "turkce": "talepkar/zorlu", "okunus": "/dɪˈmɑːndɪŋ/" },
  { "ingilizce": "due", "turkce": "vadesi dolmuş/beklenen", "okunus": "/djuː/" },
  { "ingilizce": "duplicate", "turkce": "kopya/benzer", "okunus": "/ˈdjuːplɪkət/" },
  { "ingilizce": "engaged", "turkce": "nişanlı", "okunus": "/ɪnˈɡeɪdʒd/" },
  { "ingilizce": "entrepreneur", "turkce": "girişimci", "okunus": "/ˌɒntrəprəˈnɜː(r)/" },
  { "ingilizce": "fail", "turkce": "başarısız olmak", "okunus": "/feɪl/" },
  { "ingilizce": "forbidden", "turkce": "yasak", "okunus": "/fəˈbɪdn/" },
  { "ingilizce": "funeral", "turkce": "cenaze", "okunus": "/ˈfjuːnərəl/" },
  { "ingilizce": "garage", "turkce": "garaj/tamirhane", "okunus": "/ˈɡærɑːdʒ/" },
  { "ingilizce": "healthcare", "turkce": "sağlık hizmeti", "okunus": "/ˈhelθkeə(r)/" },
  { "ingilizce": "honeymoon", "turkce": "balayı", "okunus": "/ˈhʌnimuːn/" },
  { "ingilizce": "influence", "turkce": "etkilemek", "okunus": "/ˈɪnfluəns/" },
  { "ingilizce": "keyboard", "turkce": "klavye/org", "okunus": "/ˈkiːbɔːd/" },
  { "ingilizce": "life expectancy", "turkce": "ortalama yaşam süresi", "okunus": "/ˈlaɪf ɪkspektənsi/" },
  { "ingilizce": "married", "turkce": "evli", "okunus": "/ˈmærid/" },
  { "ingilizce": "memorabilia", "turkce": "hatıra eşyalar", "okunus": "/ˌmemərəˈbɪliə/" },
  { "ingilizce": "never-ending", "turkce": "bitmeyen", "okunus": "/ˌnevər ˈendɪŋ/" },
  { "ingilizce": "optimistic", "turkce": "iyimser", "okunus": "/ˌɒptɪˈmɪstɪk/" },
  { "ingilizce": "peer", "turkce": "akran", "okunus": "/pɪə(r)/" },
  { "ingilizce": "pessimistic", "turkce": "kötümser", "okunus": "/ˌpesɪˈmɪstɪk/" },
  { "ingilizce": "physicist", "turkce": "fizikçi", "okunus": "/ˈfɪzɪsɪst/" },
  { "ingilizce": "poetry", "turkce": "şiir sanatı", "okunus": "/ˈpəʊətri/" },
  { "ingilizce": "pregnant", "turkce": "hamile", "okunus": "/ˈpreɡnənt/" },
  { "ingilizce": "raindrop", "turkce": "yağmur damlası", "okunus": "/ˈreɪndrɒp/" },
  { "ingilizce": "regret", "turkce": "pişmanlık", "okunus": "/rɪˈɡret/" },
  { "ingilizce": "renewed", "turkce": "yenilenmiş", "okunus": "/rɪˈnjuːd/" },
  { "ingilizce": "repair", "turkce": "tamir etmek", "okunus": "/rɪˈpeə(r)/" },
  { "ingilizce": "resources", "turkce": "kaynaklar", "okunus": "/rɪˈsɔːsɪz/" },
  { "ingilizce": "rocket", "turkce": "roket", "okunus": "/ˈrɒkɪt/" },
  { "ingilizce": "selfish", "turkce": "bencil", "okunus": "/ˈselfɪʃ/" },
  { "ingilizce": "serious", "turkce": "ciddi", "okunus": "/ˈsɪəriəs/" },
  { "ingilizce": "servant", "turkce": "hizmetçi", "okunus": "/ˈsɜːvənt/" },
  { "ingilizce": "split up", "turkce": "ayrılmak", "okunus": "/splɪt ʌp/" },
  { "ingilizce": "stick", "turkce": "sopa/baston", "okunus": "/stɪk/" },
  { "ingilizce": "surrogate", "turkce": "taşıyıcı (anne)", "okunus": "/ˈsʌrəɡət/" },
  { "ingilizce": "tragedy", "turkce": "trajedi", "okunus": "/ˈtrædʒədi/" },
  { "ingilizce": "unsaid", "turkce": "söylenmemiş", "okunus": "/ˌʌnˈsed/" },
  { "ingilizce": "wealth", "turkce": "servet", "okunus": "/welθ/" },
  { "ingilizce": "widowed", "turkce": "dul kalmış", "okunus": "/ˈwɪdəʊd/" },
  { "ingilizce": "barbecue", "turkce": "mangal", "okunus": "/ˈbɑːbɪkjuː/" },
  { "ingilizce": "biscuit", "turkce": "bisküvi", "okunus": "/ˈbɪskɪt/" },
  { "ingilizce": "boomerang", "turkce": "bumerang", "okunus": "/ˈbuːməræŋ/" },
  { "ingilizce": "campus", "turkce": "kampüs", "okunus": "/ˈkæmpəs/" },
  { "ingilizce": "coincidence", "turkce": "tesadüf", "okunus": "/kəʊˈɪnsɪdəns/" },
  { "ingilizce": "confuse", "turkce": "kafasını karıştırmak", "okunus": "/kənˈfjuːz/" },
  { "ingilizce": "drop out", "turkce": "okulu bırakmak", "okunus": "/drɒp aʊt/" },
  { "ingilizce": "economics", "turkce": "ekonomi", "okunus": "/ˌiːkəˈnɒmɪks/" },
  { "ingilizce": "flip", "turkce": "fiske vurmak/çevirmek", "okunus": "/flɪp/" },
  { "ingilizce": "gambler", "turkce": "kumarbaz", "okunus": "/ˈɡæmblə(r)/" },
  { "ingilizce": "gig", "turkce": "konser/iş", "okunus": "/ɡɪɡ/" },
  { "ingilizce": "grateful", "turkce": "minnettar", "okunus": "/ˈɡreɪtfl/" },
  { "ingilizce": "greedy", "turkce": "açgözlü", "okunus": "/ˈɡriːdi/" },
  { "ingilizce": "lack", "turkce": "eksiklik/yokluk", "okunus": "/læk/" },
  { "ingilizce": "loan", "turkce": "borç/kredi", "okunus": "/ləʊn/" },
  { "ingilizce": "lorry", "turkce": "kamyon", "okunus": "/ˈlɒri/" },
  { "ingilizce": "meditate", "turkce": "meditasyon yapmak", "okunus": "/ˈmedɪteɪt/" },
  { "ingilizce": "probability", "turkce": "olasılık", "okunus": "/ˌprɒbəˈbɪləti/" },
  { "ingilizce": "retrain", "turkce": "yeniden eğitmek", "okunus": "/ˌriːˈtreɪn/" },
  { "ingilizce": "terrorist attack", "turkce": "terörist saldırısı", "okunus": "/ˈterərɪst əˈtæk/" },
  { "ingilizce": "threat", "turkce": "tehdit", "okunus": "/θret/" },
  { "ingilizce": "tick", "turkce": "tik tak etmek/işaretlemek", "okunus": "/tɪk/" },
  { "ingilizce": "toast", "turkce": "kadeh kaldırmak/tost", "okunus": "/təʊst/" },
  { "ingilizce": "unbelievable", "turkce": "inanılmaz", "okunus": "/ˌʌnbɪˈliːvəbl/" },
  { "ingilizce": "weird", "turkce": "tuhaf", "okunus": "/wɪəd/" }
]