export const kelimeler=[

  { "ingilizce": "abroad", "turkce": "yurt dışı", "okunus": "ıbrod", "seviye": "B1" },
  { "ingilizce": "academy", "turkce": "akademi", "okunus": "ı kedımi", "seviye": "B1" },
  { "ingilizce": "accommodation", "turkce": "konaklama", "okunus": "ı komı deyşın", "seviye": "B1" },
  { "ingilizce": "album", "turkce": "albüm", "okunus": "el bım", "seviye": "A2" },
  { "ingilizce": "applicable", "turkce": "uygulanabilir", "okunus": "ı pli kıbıl", "seviye": "B2" },
  { "ingilizce": "arrival", "turkce": "varış", "okunus": "ı rayvıl", "seviye": "A2" },
  { "ingilizce": "bar", "turkce": "bar", "okunus": "bar", "seviye": "A1" },
  { "ingilizce": "beard", "turkce": "sakal", "okunus": "bird", "seviye": "A2" },
  { "ingilizce": "blind date", "turkce": "görmeden randevulaşma", "okunus": "blaynd deyt", "seviye": "B1" },
  { "ingilizce": "borrow", "turkce": "ödünç almak", "okunus": "borov", "seviye": "A2" },
  { "ingilizce": "bubbly", "turkce": "hayat dolu/neşeli", "okunus": "babli", "seviye": "B2" },
  { "ingilizce": "busker", "turkce": "sokak çalgıcısı", "okunus": "baskır", "seviye": "B2" },
  { "ingilizce": "camper van", "turkce": "karavan", "okunus": "kempır ven", "seviye": "B1" },
  { "ingilizce": "carpenter", "turkce": "marangoz", "okunus": "karpıntır", "seviye": "B1" },
  { "ingilizce": "chatty", "turkce": "geveze/konuşkan", "okunus": "çeti", "seviye": "B1" },
  { "ingilizce": "cheers", "turkce": "şerefe/teşekkürler", "okunus": "çirs", "seviye": "A2" },
  { "ingilizce": "college", "turkce": "kolej/yüksekokul", "okunus": "kalıc", "seviye": "A2" },
  { "ingilizce": "couple", "turkce": "çift", "okunus": "kapıl", "seviye": "A2" },
  { "ingilizce": "crazy", "turkce": "çılgın", "okunus": "kreyzi", "seviye": "A2" },
  { "ingilizce": "crazy about", "turkce": "bayılmak (bir şeye)", "okunus": "kreyzi ıbaut", "seviye": "B1" },
  { "ingilizce": "daily", "turkce": "günlük", "okunus": "deyli", "seviye": "A2" },
  { "ingilizce": "date", "turkce": "tarih/hurma/randevu/flört etmek", "okunus": "deyt", "seviye": "A2" },
  { "ingilizce": "definitely", "turkce": "kesinlikle", "okunus": "definitli", "seviye": "A2" },
  { "ingilizce": "delete", "turkce": "silmek", "okunus": "dilit", "seviye": "A2" },
  { "ingilizce": "delicious", "turkce": "lezzetli", "okunus": "dilişıs", "seviye": "A2" },
  { "ingilizce": "departure", "turkce": "kalkış", "okunus": "diparçır", "seviye": "B1" },
  { "ingilizce": "dietary", "turkce": "diyetle ilgili", "okunus": "dayıtri", "seviye": "B2" },
  { "ingilizce": "early days", "turkce": "henüz erken", "okunus": "örli deyz", "seviye": "B2" },
  { "ingilizce": "embarrass", "turkce": "utandırmak", "okunus": "imbıres", "seviye": "B1" },
  { "ingilizce": "embarrassing", "turkce": "utanç verici", "okunus": "imbıresing", "seviye": "B1" },
  { "ingilizce": "emergency", "turkce": "acil durum", "okunus": "imörcınsi", "seviye": "A2" },
  { "ingilizce": "empty", "turkce": "boş", "okunus": "empti", "seviye": "A1" },
  { "ingilizce": "excited", "turkce": "heyecanlı", "okunus": "iksaytıd", "seviye": "A1" },
  { "ingilizce": "fabulous", "turkce": "harika/efsanevi", "okunus": "febyılıs", "seviye": "B1" },
  { "ingilizce": "flatmate", "turkce": "ev arkadaşı", "okunus": "fletmeyt", "seviye": "B1" },
  { "ingilizce": "forever", "turkce": "sonsuza dek", "okunus": "for evır", "seviye": "A2" },
  { "ingilizce": "gender", "turkce": "cinsiyet", "okunus": "cendır", "seviye": "B1" },
  { "ingilizce": "global", "turkce": "küresel", "okunus": "globıl", "seviye": "B1" },
  { "ingilizce": "heavy", "turkce": "ağır/yoğun", "okunus": "hevi", "seviye": "A1" },
  { "ingilizce": "hire", "turkce": "kiralamak", "okunus": "hayır", "seviye": "A2" },
  { "ingilizce": "hostel", "turkce": "pansiyon", "okunus": "hostıl", "seviye": "A2" },
  { "ingilizce": "How do you do?", "turkce": "Memnun oldum (resmi)", "okunus": "hav du yu du", "seviye": "A2" },
  { "ingilizce": "I'm afraid", "turkce": "Korkarım ki/Maalesef", "okunus": "aym ıfreyd", "seviye": "A2" },
  { "ingilizce": "improve", "turkce": "geliştirmek", "okunus": "impruv", "seviye": "A2" },
  { "ingilizce": "in common", "turkce": "ortak nokta", "okunus": "in kamın", "seviye": "B1" },
  { "ingilizce": "journalist", "turkce": "gazeteci", "okunus": "cörnılist", "seviye": "A2" },
  { "ingilizce": "jumper", "turkce": "kazak", "okunus": "campır", "seviye": "A2" },
  { "ingilizce": "kind", "turkce": "kibar", "okunus": "kaynd", "seviye": "A1" },
  { "ingilizce": "kiss", "turkce": "öpmek", "okunus": "kis", "seviye": "A1" },
  { "ingilizce": "knock over", "turkce": "devirmek/çarpmak", "okunus": "nak ovır", "seviye": "B1" },
  { "ingilizce": "lend", "turkce": "ödünç vermek", "okunus": "lend", "seviye": "A2" },
  { "ingilizce": "lose touch", "turkce": "iletişimi koparmak", "okunus": "luz taç", "seviye": "B1" },
  { "ingilizce": "marital status", "turkce": "medeni hal", "okunus": "meritıl steytıs", "seviye": "B2" },
  { "ingilizce": "mean", "turkce": "cimri/kaba", "okunus": "min", "seviye": "B1" },
  { "ingilizce": "medical condition", "turkce": "tıbbi durum/rahatsızlık", "okunus": "medikıl kındişın", "seviye": "B1" },
  { "ingilizce": "mess", "turkce": "dağınıklık", "okunus": "mes", "seviye": "A2" },
  { "ingilizce": "miss", "turkce": "özlemek/kaçırmak", "okunus": "mis", "seviye": "A2" },
  { "ingilizce": "mountain", "turkce": "dağ", "okunus": "mauntın", "seviye": "A1" },
  { "ingilizce": "my pleasure", "turkce": "bir şey değil/zevkliydi", "okunus": "may plejır", "seviye": "A2" },
  { "ingilizce": "nest", "turkce": "yuva", "okunus": "nest", "seviye": "A2" },
  { "ingilizce": "never mind", "turkce": "boşver/önemli değil", "okunus": "nevır maynd", "seviye": "A2" },
  { "ingilizce": "nickname", "turkce": "lakap", "okunus": "nikneym", "seviye": "A2" },
  { "ingilizce": "no trouble", "turkce": "sorun değil/zahmet değil", "okunus": "no trabıl", "seviye": "A2" },
  { "ingilizce": "noise", "turkce": "gürültü", "okunus": "noyz", "seviye": "A1" },
  { "ingilizce": "obviously", "turkce": "açıkçası/belli ki", "okunus": "abviısli", "seviye": "B1" },
  { "ingilizce": "occupation", "turkce": "meslek", "okunus": "akyı peyşın", "seviye": "B1" },
  { "ingilizce": "pardon", "turkce": "pardon/efendim?", "okunus": "pardın", "seviye": "A2" },
  { "ingilizce": "permanent", "turkce": "kalıcı", "okunus": "pörmınınt", "seviye": "B1" },
  { "ingilizce": "pick up", "turkce": "toplamak/almak", "okunus": "pik ap", "seviye": "A2" },
  { "ingilizce": "pleasure", "turkce": "zevk/memnuniyet", "okunus": "plejır", "seviye": "A2" },
  { "ingilizce": "postcode", "turkce": "posta kodu", "okunus": "postkod", "seviye": "A1" },
  { "ingilizce": "pretty", "turkce": "güzel/sevimli", "okunus": "priti", "seviye": "A1" },
  { "ingilizce": "pub", "turkce": "pub/bar", "okunus": "pab", "seviye": "A1" },
  { "ingilizce": "relationship", "turkce": "ilişki", "okunus": "ri leyşınşip", "seviye": "A2" },
  { "ingilizce": "reporter", "turkce": "muhabir", "okunus": "ri portır", "seviye": "A2" },
  { "ingilizce": "requirements", "turkce": "gereksinimler", "okunus": "ri kuayırmınts", "seviye": "B1" },
  { "ingilizce": "rescue", "turkce": "kurtarmak", "okunus": "reskyu", "seviye": "A2" },
  { "ingilizce": "retire", "turkce": "emekli olmak", "okunus": "ri tayır", "seviye": "B1" },
  { "ingilizce": "reunited", "turkce": "yeniden birleşmiş", "okunus": "ri yunaytıd", "seviye": "B1" },
  { "ingilizce": "scholarship", "turkce": "burs", "okunus": "skalırşip", "seviye": "B1" },
  { "ingilizce": "seaside", "turkce": "deniz kenarı", "okunus": "sisayd", "seviye": "A1" },
  { "ingilizce": "secondary school", "turkce": "ortaokul", "okunus": "sekındri skul", "seviye": "A2" },
  { "ingilizce": "signature", "turkce": "imza", "okunus": "signıçır", "seviye": "A2" },
  { "ingilizce": "single", "turkce": "bekar", "okunus": "singıl", "seviye": "A1" },
  { "ingilizce": "surname", "turkce": "soyadı", "okunus": "sörneym", "seviye": "A1" },
  { "ingilizce": "surprising", "turkce": "şaşırtıcı", "okunus": "sıprayzing", "seviye": "A2" },
  { "ingilizce": "text", "turkce": "mesaj yazmak", "okunus": "tekst", "seviye": "A1" },
  { "ingilizce": "unusual", "turkce": "olağandışı", "okunus": "an yujıl", "seviye": "A2" },
  { "ingilizce": "veggie (vegetarian)", "turkce": "vejetaryen", "okunus": "veci", "seviye": "A2" },
  { "ingilizce": "wardrobe", "turkce": "gardırop", "okunus": "vordrob", "seviye": "A2" },
  { "ingilizce": "well-paid", "turkce": "iyi maaşlı", "okunus": "vel peyd", "seviye": "B1" },
  { "ingilizce": "wild", "turkce": "vahşi", "okunus": "vayld", "seviye": "A2" },
  { "ingilizce": "wink", "turkce": "göz kırpmak", "okunus": "vink", "seviye": "B1" },
  { "ingilizce": "woolly", "turkce": "yünlü", "okunus": "vuli", "seviye": "B1" },
  { "ingilizce": "worried", "turkce": "endişeli", "okunus": "vörid", "seviye": "A1" },
  { "ingilizce": "a handful", "turkce": "ele avuca sığmaz", "okunus": "ı hendful", "seviye": "B2" },
  { "ingilizce": "absolutely", "turkce": "kesinlikle", "okunus": "ebsılutli", "seviye": "A2" },
  { "ingilizce": "acting", "turkce": "oyunculuk", "okunus": "ekting", "seviye": "A2" },
  { "ingilizce": "art gallery", "turkce": "sanat galerisi", "okunus": "art gelıri", "seviye": "A2" },
  { "ingilizce": "beat", "turkce": "yenmek", "okunus": "bit", "seviye": "A2" },
  { "ingilizce": "believe", "turkce": "inanmak", "okunus": "biliv", "seviye": "A1" },
  { "ingilizce": "brave", "turkce": "cesur", "okunus": "breyv", "seviye": "A2" },
  { "ingilizce": "competitive", "turkce": "rekabetçi", "okunus": "kımpetitiv", "seviye": "B1" },
  { "ingilizce": "confidence", "turkce": "özgüven", "okunus": "kanfidıns", "seviye": "B1" },
  { "ingilizce": "confident", "turkce": "kendinden emin", "okunus": "kanfidınt", "seviye": "B1" },
  { "ingilizce": "countryside", "turkce": "kırsal bölge", "okunus": "kantri sayd", "seviye": "A2" },
  { "ingilizce": "crossword", "turkce": "bulmaca", "okunus": "krosvörd", "seviye": "A2" },
  { "ingilizce": "dependent", "turkce": "bağımlı", "okunus": "dipendınt", "seviye": "B1" },
  { "ingilizce": "despite", "turkce": "-e rağmen", "okunus": "dispayt", "seviye": "B1" },
  { "ingilizce": "disagree", "turkce": "katılmamak", "okunus": "disıgri", "seviye": "A2" },
  { "ingilizce": "divorced", "turkce": "boşanmış", "okunus": "divorst", "seviye": "A2" },
  { "ingilizce": "dress", "turkce": "elbise", "okunus": "dres", "seviye": "A1" },
  { "ingilizce": "dye", "turkce": "boyamak (saç vb.)", "okunus": "day", "seviye": "B1" },
  { "ingilizce": "equally", "turkce": "eşit derecede", "okunus": "ikuıli", "seviye": "B1" },
  { "ingilizce": "experiment", "turkce": "deney yapmak", "okunus": "iksperimınt", "seviye": "A2" },
  { "ingilizce": "explore", "turkce": "keşfetmek", "okunus": "iksplor", "seviye": "A2" },
  { "ingilizce": "express an opinion", "turkce": "fikir beyan etmek", "okunus": "ikspres en ıpin yın", "seviye": "B1" },
  { "ingilizce": "fence", "turkce": "çit", "okunus": "fens", "seviye": "A2" },
  { "ingilizce": "fight", "turkce": "kavga etmek", "okunus": "fayt", "seviye": "A1" },
  { "ingilizce": "forget", "turkce": "unutmak", "okunus": "fırget", "seviye": "A1" },
  { "ingilizce": "grown-up", "turkce": "yetişkin", "okunus": "gron ap", "seviye": "A2" },
  { "ingilizce": "headphones", "turkce": "kulaklık", "okunus": "hedfons", "seviye": "A1" },
  { "ingilizce": "homework", "turkce": "ev ödevi", "okunus": "homvörk", "seviye": "A1" },
  { "ingilizce": "hopeless", "turkce": "umutsuz/beceriksiz", "okunus": "hoplıs", "seviye": "B1" },
  { "ingilizce": "identical", "turkce": "özdeş/tıpatıp aynı", "okunus": "aydentikıl", "seviye": "B1" },
  { "ingilizce": "ill", "turkce": "hasta", "okunus": "il", "seviye": "A1" },
  { "ingilizce": "independent", "turkce": "bağımsız", "okunus": "indipendınt", "seviye": "A2" },
  { "ingilizce": "ingredients", "turkce": "malzemeler", "okunus": "ingridiyınts", "seviye": "A2" },
  { "ingilizce": "invite", "turkce": "davet etmek", "okunus": "invayt", "seviye": "A1" },
  { "ingilizce": "jealous", "turkce": "kıskanç", "okunus": "celıs", "seviye": "A2" },
  { "ingilizce": "keep in touch", "turkce": "iletişimi sürdürmek", "okunus": "kip in taç", "seviye": "A2" },
  { "ingilizce": "lazy", "turkce": "tembel", "okunus": "leyzi", "seviye": "A1" },
  { "ingilizce": "lie-in", "turkce": "geç uyanmak", "okunus": "lay in", "seviye": "B1" },
  { "ingilizce": "magazine", "turkce": "dergi", "okunus": "megı zin", "seviye": "A1" },
  { "ingilizce": "neighbour", "turkce": "komşu", "okunus": "neybır", "seviye": "A1" },
  { "ingilizce": "notice", "turkce": "fark etmek", "okunus": "notis", "seviye": "A2" },
  { "ingilizce": "pay no attention", "turkce": "aldırış etmemek", "okunus": "pey no ıtenşın", "seviye": "B2" },
  { "ingilizce": "personality", "turkce": "kişilik", "okunus": "pörsınalıti", "seviye": "A2" },
  { "ingilizce": "play", "turkce": "oyun (tiyatro)", "okunus": "pley", "seviye": "A1" },
  { "ingilizce": "polite", "turkce": "kibar", "okunus": "pılayt", "seviye": "A2" },
  { "ingilizce": "postman", "turkce": "postacı", "okunus": "postmın", "seviye": "A1" },
  { "ingilizce": "practice", "turkce": "pratik", "okunus": "prektis", "seviye": "A1" },
  { "ingilizce": "puzzle", "turkce": "yapboz/bulmaca", "okunus": "pazıl", "seviye": "A2" },
  { "ingilizce": "quiz", "turkce": "kısa sınav", "okunus": "kuiz", "seviye": "A1" },
  { "ingilizce": "recipe", "turkce": "tarif", "okunus": "resıpi", "seviye": "A2" },
  { "ingilizce": "rich", "turkce": "zengin", "okunus": "riç", "seviye": "A1" },
  { "ingilizce": "saxophone", "turkce": "saksafon", "okunus": "seksıfon", "seviye": "A2" },
  { "ingilizce": "scary", "turkce": "korkutucu", "okunus": "skeri", "seviye": "A2" },
  { "ingilizce": "score", "turkce": "skor/puan", "okunus": "skor", "seviye": "A2" },
  { "ingilizce": "shy", "turkce": "utangaç", "okunus": "şay", "seviye": "A2" },
  { "ingilizce": "smart", "turkce": "akıllı/şık", "okunus": "smart", "seviye": "A2" },
  { "ingilizce": "solitary", "turkce": "yalnız", "okunus": "salıteri", "seviye": "B2" },
  { "ingilizce": "solve", "turkce": "çözmek", "okunus": "salv", "seviye": "A2" },
  { "ingilizce": "suit", "turkce": "yakışmak/takım elbise", "okunus": "sut", "seviye": "A2" },
  { "ingilizce": "suspicious", "turkce": "şüpheli/kuşkulu", "okunus": "sıspişıs", "seviye": "B1" },
  { "ingilizce": "takeaway", "turkce": "paket servis", "okunus": "teykıvey", "seviye": "A2" },
  { "ingilizce": "tattoo", "turkce": "dövme", "okunus": "tetu", "seviye": "A2" },
  { "ingilizce": "twins", "turkce": "ikizler", "okunus": "tvins", "seviye": "A1" },
  { "ingilizce": "usually", "turkce": "genellikle", "okunus": "yujıli", "seviye": "A1" },
  { "ingilizce": "village", "turkce": "köy", "okunus": "vilic", "seviye": "A1" },
  { "ingilizce": "accident", "turkce": "kaza", "okunus": "eksidınt", "seviye": "A1" },
  { "ingilizce": "afford", "turkce": "maddi gücü yetmek", "okunus": "ıford", "seviye": "A2" },
  { "ingilizce": "air conditioning", "turkce": "klima", "okunus": "er kındişning", "seviye": "A2" },
  { "ingilizce": "angry", "turkce": "kızgın", "okunus": "engri", "seviye": "A1" },
  { "ingilizce": "appointment", "turkce": "randevu", "okunus": "ıpointmınt", "seviye": "A2" },
  { "ingilizce": "assassin", "turkce": "suikastçı", "okunus": "ısesin", "seviye": "B1" },
  { "ingilizce": "bang", "turkce": "çarpmak/gümlemek", "okunus": "beng", "seviye": "A2" },
  { "ingilizce": "boss", "turkce": "patron", "okunus": "bos", "seviye": "A1" },
  { "ingilizce": "breathe", "turkce": "nefes almak", "okunus": "brid", "seviye": "A2" },
  { "ingilizce": "bricklayer", "turkce": "duvar ustası", "okunus": "brikleyır", "seviye": "B1" },
  { "ingilizce": "bullet", "turkce": "kurşun/mermi", "okunus": "bulit", "seviye": "B1" },
  { "ingilizce": "capture", "turkce": "yakalamak", "okunus": "kepçır", "seviye": "B1" },
  { "ingilizce": "cardboard box", "turkce": "karton kutu", "okunus": "kardbord boks", "seviye": "A2" },
  { "ingilizce": "checkout", "turkce": "kasa (market)", "okunus": "çekaut", "seviye": "A2" },
  { "ingilizce": "club together", "turkce": "para birleştirmek", "okunus": "klab tıgedır", "seviye": "B2" },
  { "ingilizce": "coast", "turkce": "sahil", "okunus": "kost", "seviye": "A2" },
  { "ingilizce": "continually", "turkce": "sürekli", "okunus": "kıntinyuıli", "seviye": "B1" },
  { "ingilizce": "covered", "turkce": "kaplı/örtülü", "okunus": "kavırd", "seviye": "A2" },
  { "ingilizce": "creep", "turkce": "sinsice yaklaşmak/sürünmek", "okunus": "krip", "seviye": "B1" },
  { "ingilizce": "curse", "turkce": "lanetlemek/küfretmek", "okunus": "körs", "seviye": "B1" },
  { "ingilizce": "curtain", "turkce": "perde", "okunus": "körtın", "seviye": "A2" },
  { "ingilizce": "cut", "turkce": "kesmek", "okunus": "kat", "seviye": "A1" },
  { "ingilizce": "darkness", "turkce": "karanlık", "okunus": "darknıs", "seviye": "A2" },
  { "ingilizce": "description", "turkce": "tanımlama", "okunus": "diskripşın", "seviye": "A2" },
  { "ingilizce": "die", "turkce": "ölmek", "okunus": "day", "seviye": "A1" },
  { "ingilizce": "disappear", "turkce": "kaybolmak", "okunus": "disıpir", "seviye": "A2" },
  { "ingilizce": "enjoy", "turkce": "tadını çıkarmak", "okunus": "incoy", "seviye": "A1" },
  { "ingilizce": "escape", "turkce": "kaçmak", "okunus": "iskeyp", "seviye": "A2" },
  { "ingilizce": "exactly", "turkce": "tam olarak", "okunus": "igzektli", "seviye": "A2" },
  { "ingilizce": "excellent", "turkce": "mükemmel", "okunus": "eksılınt", "seviye": "A1" },
  { "ingilizce": "expiry date", "turkce": "son kullanma tarihi", "okunus": "ikspayri deyt", "seviye": "B1" },
  { "ingilizce": "feathers", "turkce": "tüyler", "okunus": "fedırz", "seviye": "A2" },
  { "ingilizce": "feed", "turkce": "beslemek", "okunus": "fid", "seviye": "A2" },
  { "ingilizce": "finishing line", "turkce": "bitiş çizgisi", "okunus": "finişing layn", "seviye": "B1" },
  { "ingilizce": "fluently", "turkce": "akıcı bir şekilde", "okunus": "fluıntli", "seviye": "B1" },
  { "ingilizce": "furious", "turkce": "öfkeli", "okunus": "fyuriyıs", "seviye": "B1" },
  { "ingilizce": "generously", "turkce": "cömertçe", "okunus": "cenırısli", "seviye": "B1" },
  { "ingilizce": "gradually", "turkce": "yavaş yavaş", "okunus": "grecuıli", "seviye": "B1" },
  { "ingilizce": "guess", "turkce": "tahmin etmek", "okunus": "ges", "seviye": "A2" },
  { "ingilizce": "guiltily", "turkce": "suçlu bir şekilde", "okunus": "giltili", "seviye": "B2" },
  { "ingilizce": "gun", "turkce": "silah", "okunus": "gan", "seviye": "A2" },
  { "ingilizce": "gunshot", "turkce": "silah sesi", "okunus": "ganşat", "seviye": "B1" },
  { "ingilizce": "happily", "turkce": "mutlulukla", "okunus": "hepili", "seviye": "A2" },
  { "ingilizce": "headfirst", "turkce": "kafa üstü", "okunus": "hedförst", "seviye": "B2" },
  { "ingilizce": "headline", "turkce": "manşet", "okunus": "hedlayn", "seviye": "B1" },
  { "ingilizce": "honk", "turkce": "korna çalmak", "okunus": "hank", "seviye": "B2" },
  { "ingilizce": "injured", "turkce": "yaralı", "okunus": "incırd", "seviye": "A2" },
  { "ingilizce": "invitation", "turkce": "davetiye", "okunus": "invıteyşın", "seviye": "A2" },
  { "ingilizce": "luxurious", "turkce": "lüks", "okunus": "lag juriyıs", "seviye": "B1" },
  { "ingilizce": "midnight", "turkce": "gece yarısı", "okunus": "midnayt", "seviye": "A1" },
  { "ingilizce": "motorway", "turkce": "otoyol", "okunus": "motırvey", "seviye": "A2" },
  { "ingilizce": "oil", "turkce": "yağ/petrol", "okunus": "oyl", "seviye": "A1" },
  { "ingilizce": "painter", "turkce": "ressam/boyacı", "okunus": "peyntır", "seviye": "A2" },
  { "ingilizce": "passionately", "turkce": "tutkuyla", "okunus": "peşınıtli", "seviye": "B1" },
  { "ingilizce": "payday", "turkce": "maaş günü", "okunus": "peydey", "seviye": "B1" },
  { "ingilizce": "peacefully", "turkce": "huzurla", "okunus": "pisfıli", "seviye": "B1" },
  { "ingilizce": "penguin", "turkce": "penguen", "okunus": "pengvin", "seviye": "A1" },
  { "ingilizce": "pillow", "turkce": "yastık", "okunus": "pilov", "seviye": "A2" },
  { "ingilizce": "poem", "turkce": "şiir", "okunus": "poim", "seviye": "A2" },
  { "ingilizce": "portrait", "turkce": "portre", "okunus": "portreyt", "seviye": "B1" },
  { "ingilizce": "refuse", "turkce": "reddetmek", "okunus": "rifyuz", "seviye": "A2" },
  { "ingilizce": "robber", "turkce": "soyguncu", "okunus": "rabır", "seviye": "A2" },
  { "ingilizce": "sardine", "turkce": "sardalya", "okunus": "sardin", "seviye": "B2" },
  { "ingilizce": "seashore", "turkce": "deniz kıyısı", "okunus": "sişor", "seviye": "A2" },
  { "ingilizce": "secret agent", "turkce": "gizli ajan", "okunus": "sikrıt eycınt", "seviye": "B1" },
  { "ingilizce": "sick", "turkce": "hasta", "okunus": "sik", "seviye": "A1" },
  { "ingilizce": "spot", "turkce": "fark etmek/görmek", "okunus": "spat", "seviye": "A2" },
  { "ingilizce": "spy", "turkce": "casus", "okunus": "spay", "seviye": "A2" },
  { "ingilizce": "staff", "turkce": "personel", "okunus": "staf", "seviye": "A2" },
  { "ingilizce": "stall", "turkce": "tezgah/stand", "okunus": "stol", "seviye": "B1" },
  { "ingilizce": "strong", "turkce": "güçlü", "okunus": "strong", "seviye": "A1" },
  { "ingilizce": "studio", "turkce": "stüdyo", "okunus": "stüdyov", "seviye": "A2" },
  { "ingilizce": "tail", "turkce": "kuyruk", "okunus": "teyl", "seviye": "A1" },
  { "ingilizce": "tear", "turkce": "gözyaşı", "okunus": "tir", "seviye": "A2" },
  { "ingilizce": "thump", "turkce": "güm güm vurmak", "okunus": "tamp", "seviye": "B2" },
  { "ingilizce": "tiny", "turkce": "küçücük", "okunus": "tayni", "seviye": "A2" },
  { "ingilizce": "triathlon", "turkce": "triatlon", "okunus": "trayetlon", "seviye": "B1" },
  { "ingilizce": "urgently", "turkce": "acilen", "okunus": "örcıntli", "seviye": "B1" },
  { "ingilizce": "vase", "turkce": "vazo", "okunus": "vaz", "seviye": "A2" },
  { "ingilizce": "wallet", "turkce": "cüzdan", "okunus": "valit", "seviye": "A2" },
  { "ingilizce": "whisper", "turkce": "fısıldamak", "okunus": "vispır", "seviye": "B1" },
  { "ingilizce": "alcohol", "turkce": "alkol", "okunus": "elkıhol", "seviye": "A2" },
  { "ingilizce": "attraction", "turkce": "cazibe/turistik yer", "okunus": "ıtrekşın", "seviye": "B1" },
  { "ingilizce": "bake", "turkce": "fırında pişirmek", "okunus": "beyk", "seviye": "A2" },
  { "ingilizce": "baking", "turkce": "pişirme", "okunus": "beyking", "seviye": "A2" },
  { "ingilizce": "bitterly", "turkce": "acı bir şekilde", "okunus": "bitırli", "seviye": "B1" },
  { "ingilizce": "bunch", "turkce": "salkım/demet", "okunus": "banç", "seviye": "A2" },
  { "ingilizce": "can", "turkce": "konserve kutusu", "okunus": "ken", "seviye": "A1" },
  { "ingilizce": "caramel", "turkce": "karamel", "okunus": "kerımel", "seviye": "A2" },
  { "ingilizce": "chef", "turkce": "şef", "okunus": "şef", "seviye": "A2" },
  { "ingilizce": "chewing gum", "turkce": "sakız", "okunus": "çuing gam", "seviye": "A2" },
  { "ingilizce": "chillies", "turkce": "acı biberler", "okunus": "çiliz", "seviye": "A2" },
  { "ingilizce": "complaint", "turkce": "şikayet", "okunus": "kımpleynt", "seviye": "B1" },
  { "ingilizce": "contented", "turkce": "hoşnut/memnun", "okunus": "kıntentıd", "seviye": "B1" },
  { "ingilizce": "cookies", "turkce": "kurabiyeler", "okunus": "kukiz", "seviye": "A1" },
  { "ingilizce": "crisps", "turkce": "cips", "okunus": "krisps", "seviye": "A1" },
  { "ingilizce": "curry", "turkce": "köri/körili yemek", "okunus": "kari", "seviye": "A2" },
  { "ingilizce": "decaf", "turkce": "kafeinsiz", "okunus": "dikef", "seviye": "B1" },
  { "ingilizce": "delicatessen", "turkce": "şarküteri", "okunus": "delikıtesın", "seviye": "B2" },
  { "ingilizce": "discover", "turkce": "keşfetmek", "okunus": "diskavır", "seviye": "A2" },
  { "ingilizce": "dough", "turkce": "hamur", "okunus": "do", "seviye": "B1" },
  { "ingilizce": "engineer", "turkce": "mühendis", "okunus": "encinir", "seviye": "A2" },
  { "ingilizce": "flavour", "turkce": "aroma/tat", "okunus": "fleyvır", "seviye": "A2" },
  { "ingilizce": "fork", "turkce": "çatal", "okunus": "fork", "seviye": "A1" },
  { "ingilizce": "french fries", "turkce": "patates kızartması", "okunus": "frenç frayz", "seviye": "A1" },
  { "ingilizce": "fridge", "turkce": "buzdolabı", "okunus": "fric", "seviye": "A1" },
  { "ingilizce": "fry", "turkce": "kızartmak", "okunus": "fray", "seviye": "A2" },
  { "ingilizce": "fussy", "turkce": "titiz/zor beğenen", "okunus": "fasi", "seviye": "B1" },
  { "ingilizce": "glasses", "turkce": "gözlük", "okunus": "glasız", "seviye": "A1" },
  { "ingilizce": "guest", "turkce": "misafir", "okunus": "gest", "seviye": "A2" },
  { "ingilizce": "hike", "turkce": "doğa yürüyüşü yapmak", "okunus": "hayk", "seviye": "A2" },
  { "ingilizce": "ice lolly", "turkce": "meyveli buz", "okunus": "ays lali", "seviye": "A2" },
  { "ingilizce": "ID", "turkce": "kimlik", "okunus": "ay di", "seviye": "A1" },
  { "ingilizce": "increase", "turkce": "artış/artmak", "okunus": "inkris", "seviye": "A2" },
  { "ingilizce": "industrial", "turkce": "endüstriyel", "okunus": "indastriyıl", "seviye": "B1" },
  { "ingilizce": "invent", "turkce": "icat etmek", "okunus": "invent", "seviye": "A2" },
  { "ingilizce": "lick", "turkce": "yalamak", "okunus": "lik", "seviye": "A2" },
  { "ingilizce": "lift", "turkce": "asansör", "okunus": "lift", "seviye": "A2" },
  { "ingilizce": "loaf", "turkce": "somun (ekmek)", "okunus": "lof", "seviye": "B1" },
  { "ingilizce": "lose", "turkce": "kaybetmek", "okunus": "luz", "seviye": "A1" },
  { "ingilizce": "match", "turkce": "kibrit", "okunus": "meç", "seviye": "A2" },
  { "ingilizce": "melt", "turkce": "erimek", "okunus": "melt", "seviye": "A2" },
  { "ingilizce": "newsagent's", "turkce": "gazete bayii", "okunus": "nyuz eycınts", "seviye": "B1" },
  { "ingilizce": "off-licence", "turkce": "tekel bayii", "okunus": "of laysıns", "seviye": "B2" },
  { "ingilizce": "olive", "turkce": "zeytin", "okunus": "aliv", "seviye": "A2" },
  { "ingilizce": "omelette", "turkce": "omlet", "okunus": "amlit", "seviye": "A2" },
  { "ingilizce": "original", "turkce": "orijinal", "okunus": "ıricinıl", "seviye": "A2" },
  { "ingilizce": "out of this world", "turkce": "harika/muhteşem", "okunus": "aut of dis vörld", "seviye": "B2" },
  { "ingilizce": "packet", "turkce": "paket", "okunus": "pekit", "seviye": "A2" },
  { "ingilizce": "patent", "turkce": "patent", "okunus": "peytınt", "seviye": "B2" },
  { "ingilizce": "petrol", "turkce": "benzin", "okunus": "petrıl", "seviye": "A2" },
  { "ingilizce": "popular", "turkce": "popüler", "okunus": "papyulır", "seviye": "A2" },
  { "ingilizce": "porch", "turkce": "veranda", "okunus": "porç", "seviye": "B1" },
  { "ingilizce": "postcard", "turkce": "kartpostal", "okunus": "postkard", "seviye": "A2" },
  { "ingilizce": "powder", "turkce": "toz", "okunus": "paudır", "seviye": "A2" },
  { "ingilizce": "publish", "turkce": "yayımlamak", "okunus": "pabliş", "seviye": "B1" },
  { "ingilizce": "receive", "turkce": "almak/teslim almak", "okunus": "risiv", "seviye": "A2" },
  { "ingilizce": "roast chicken", "turkce": "fırında tavuk", "okunus": "rost çikin", "seviye": "A2" },
  { "ingilizce": "secret", "turkce": "sır", "okunus": "sikrıt", "seviye": "A1" },
  { "ingilizce": "shopkeeper", "turkce": "dükkan sahibi", "okunus": "şapkipır", "seviye": "A2" },
  { "ingilizce": "slice", "turkce": "dilim", "okunus": "slays", "seviye": "A2" },
  { "ingilizce": "sparkling", "turkce": "gazlı (içecek)", "okunus": "sparkling", "seviye": "B1" },
  { "ingilizce": "spectacular", "turkce": "görkemli", "okunus": "spektekyulır", "seviye": "B1" },
  { "ingilizce": "spicy", "turkce": "baharatlı", "okunus": "spaysi", "seviye": "A2" },
  { "ingilizce": "spinach", "turkce": "ıspanak", "okunus": "spiniç", "seviye": "A2" },
  { "ingilizce": "spoon", "turkce": "kaşık", "okunus": "spun", "seviye": "A1" },
  { "ingilizce": "spoonful", "turkce": "kaşık dolusu", "okunus": "spunful", "seviye": "A2" },
  { "ingilizce": "sprouts", "turkce": "Brüksel lahanası", "okunus": "sprauts", "seviye": "B1" },
  { "ingilizce": "strange", "turkce": "tuhaf", "okunus": "streync", "seviye": "A2" },
  { "ingilizce": "successful", "turkce": "başarılı", "okunus": "sıksesfıl", "seviye": "A2" },
  { "ingilizce": "supply", "turkce": "tedarik/kaynak", "okunus": "sıplay", "seviye": "B1" },
  { "ingilizce": "taste", "turkce": "tatmak", "okunus": "teyst", "seviye": "A2" },
  { "ingilizce": "taste buds", "turkce": "tat tomurcukları", "okunus": "teyst badz", "seviye": "B2" },
  { "ingilizce": "thin", "turkce": "ince", "okunus": "tin", "seviye": "A1" },
  { "ingilizce": "tissues", "turkce": "kağıt mendil", "okunus": "tişuz", "seviye": "A2" },
  { "ingilizce": "tongue", "turkce": "dil", "okunus": "tang", "seviye": "A2" },
  { "ingilizce": "tuna", "turkce": "ton balığı", "okunus": "tuna", "seviye": "A2" },
  { "ingilizce": "unexpected", "turkce": "beklenmedik", "okunus": "anikspektıd", "seviye": "B1" },
  { "ingilizce": "wax paper", "turkce": "yağlı kağıt", "okunus": "veks peypır", "seviye": "B2" },
  { "ingilizce": "whisky", "turkce": "viski", "okunus": "viski", "seviye": "A2" },
  { "ingilizce": "advertising", "turkce": "reklamcılık", "okunus": "edvırtayzing", "seviye": "B1" },
  { "ingilizce": "ambition", "turkce": "hırs", "okunus": "embişın", "seviye": "B1" },
  { "ingilizce": "apply", "turkce": "başvurmak", "okunus": "ıplay", "seviye": "A2" },
  { "ingilizce": "arrest", "turkce": "tutuklamak", "okunus": "ırest", "seviye": "A2" },
  { "ingilizce": "as usual", "turkce": "her zamanki gibi", "okunus": "ez yujıl", "seviye": "A2" },
  { "ingilizce": "attack", "turkce": "saldırı", "okunus": "ıtek", "seviye": "A2" },
  { "ingilizce": "average", "turkce": "ortalama", "okunus": "evıric", "seviye": "A2" },
  { "ingilizce": "award", "turkce": "ödül", "okunus": "ıvord", "seviye": "A2" },
  { "ingilizce": "ballet", "turkce": "bale", "okunus": "bele", "seviye": "A2" },
  { "ingilizce": "break", "turkce": "mola/kırmak", "okunus": "breyk", "seviye": "A1" },
  { "ingilizce": "brilliant", "turkce": "parlak/zeki", "okunus": "brilyınt", "seviye": "A2" },
  { "ingilizce": "bully", "turkce": "zorbalık etmek", "okunus": "buli", "seviye": "B1" },
  { "ingilizce": "career", "turkce": "kariyer", "okunus": "kırir", "seviye": "A2" },
  { "ingilizce": "carry out", "turkce": "gerçekleştirmek", "okunus": "keri aut", "seviye": "B1" },
  { "ingilizce": "catch up", "turkce": "yakalamak/telafi etmek", "okunus": "keç ap", "seviye": "A2" },
  { "ingilizce": "competition", "turkce": "yarışma", "okunus": "kampıtişın", "seviye": "A2" },
  { "ingilizce": "course", "turkce": "kurs/ders", "okunus": "kors", "seviye": "A1" },
  { "ingilizce": "court", "turkce": "mahkeme/kort", "okunus": "kort", "seviye": "B1" },
  { "ingilizce": "crash", "turkce": "çarpmak", "okunus": "kreş", "seviye": "A2" },
  { "ingilizce": "create", "turkce": "yaratmak", "okunus": "kri eyt", "seviye": "A2" },
  { "ingilizce": "cyber criminal", "turkce": "siber suçlu", "okunus": "saybır krimınıl", "seviye": "B2" },
  { "ingilizce": "debts", "turkce": "borçlar", "okunus": "dets", "seviye": "B1" },
  { "ingilizce": "definite", "turkce": "kesin", "okunus": "definit", "seviye": "B1" },
  { "ingilizce": "develop", "turkce": "geliştirmek", "okunus": "divelıp", "seviye": "A2" },
  { "ingilizce": "disappointed", "turkce": "hayal kırıklığına uğramış", "okunus": "disıpoyntıd", "seviye": "A2" },
  { "ingilizce": "doubt", "turkce": "şüphe etmek", "okunus": "daut", "seviye": "B1" },
  { "ingilizce": "earn", "turkce": "para kazanmak", "okunus": "örn", "seviye": "A2" },
  { "ingilizce": "exam", "turkce": "sınav", "okunus": "igzem", "seviye": "A1" },
  { "ingilizce": "fall out", "turkce": "küsüşmek/ayrılmak", "okunus": "fol aut", "seviye": "B2" },
  { "ingilizce": "fashion", "turkce": "moda", "okunus": "feşın", "seviye": "A2" },
  { "ingilizce": "favourite", "turkce": "favori", "okunus": "feyvırit", "seviye": "A1" },
  { "ingilizce": "fed up", "turkce": "bıkmış", "okunus": "fed ap", "seviye": "B1" },
  { "ingilizce": "get on (well) with", "turkce": "iyi geçinmek", "okunus": "get on vel vid", "seviye": "B1" },
  { "ingilizce": "give up", "turkce": "pes etmek/bırakmak", "okunus": "giv ap", "seviye": "A2" },
  { "ingilizce": "grandparents", "turkce": "büyükanne ve büyükbaba", "okunus": "grendperınts", "seviye": "A1" },
  { "ingilizce": "grow up", "turkce": "büyümek", "okunus": "grov ap", "seviye": "A2" },
  { "ingilizce": "hacker", "turkce": "bilgisayar korsanı", "okunus": "hekır", "seviye": "A2" },
  { "ingilizce": "homesick", "turkce": "ev özlemi çeken", "okunus": "homsik", "seviye": "B1" },
  { "ingilizce": "idiomatic", "turkce": "deyimsel", "okunus": "idiyı metik", "seviye": "C1" },
  { "ingilizce": "landscape design", "turkce": "peyzaj tasarımı", "okunus": "lend skeyp dizayn", "seviye": "B2" },
  { "ingilizce": "leap", "turkce": "sıçramak", "okunus": "lip", "seviye": "B1" },
  { "ingilizce": "literal", "turkce": "kelimesi kelimesine", "okunus": "litırıl", "seviye": "B2" },
  { "ingilizce": "look after", "turkce": "göz kulak olmak", "okunus": "luk aftır", "seviye": "A2" },
  { "ingilizce": "look forward to", "turkce": "dört gözle beklemek", "okunus": "luk forvırd tu", "seviye": "A2" },
  { "ingilizce": "look up", "turkce": "sözlükten bakmak/yukarı bakmak", "okunus": "luk ap", "seviye": "A2" },
  { "ingilizce": "miserable", "turkce": "sefil/mutsuz", "okunus": "mizrıbıl", "seviye": "B1" },
  { "ingilizce": "notorious", "turkce": "kötü şöhretli", "okunus": "notoriyıs", "seviye": "C1" },
  { "ingilizce": "owe", "turkce": "borçlu olmak", "okunus": "ov", "seviye": "B1" },
  { "ingilizce": "paramedic", "turkce": "sağlık görevlisi", "okunus": "perımedik", "seviye": "B1" },
  { "ingilizce": "pay back", "turkce": "geri ödemek", "okunus": "pey bek", "seviye": "B1" },
  { "ingilizce": "principal", "turkce": "baş/asıl", "okunus": "prinsıpıl", "seviye": "B2" },
  { "ingilizce": "prison", "turkce": "hapishane", "okunus": "prizın", "seviye": "A2" },
  { "ingilizce": "program", "turkce": "program", "okunus": "progrım", "seviye": "A2" },
  { "ingilizce": "run out of", "turkce": "tükenmek/bitmek", "okunus": "ran aut of", "seviye": "B1" },
  { "ingilizce": "slum", "turkce": "gecekondu mahallesi", "okunus": "slam", "seviye": "B2" },
  { "ingilizce": "soul", "turkce": "ruh", "okunus": "sol", "seviye": "B1" },
  { "ingilizce": "stressful", "turkce": "stresli", "okunus": "stresfıl", "seviye": "A2" },
  { "ingilizce": "suitable", "turkce": "uygun", "okunus": "sutıbıl", "seviye": "A2" },
  { "ingilizce": "take off", "turkce": "çıkarmak (kıyafet)/havalanmak", "okunus": "teyk of", "seviye": "A2" },
  { "ingilizce": "take up", "turkce": "başlamak (hobi vb.)", "okunus": "teyk ap", "seviye": "B1" },
  { "ingilizce": "talent", "turkce": "yetenek", "okunus": "telınt", "seviye": "A2" },
  { "ingilizce": "throw away", "turkce": "atmak", "okunus": "tro ıvey", "seviye": "A2" },
  { "ingilizce": "traffic jam", "turkce": "trafik sıkışıklığı", "okunus": "trefik cem", "seviye": "A2" },
  { "ingilizce": "try on", "turkce": "denemek (kıyafet)", "okunus": "tray on", "seviye": "A2" },
  { "ingilizce": "turn off", "turkce": "kapatmak", "okunus": "törn of", "seviye": "A1" },
  { "ingilizce": "turn round", "turkce": "arkasını dönmek", "okunus": "törn raund", "seviye": "A2" },
  { "ingilizce": "username", "turkce": "kullanıcı adı", "okunus": "yuzırneym", "seviye": "A1" },
  { "ingilizce": "virus", "turkce": "virüs", "okunus": "vayrıs", "seviye": "A2" },
  { "ingilizce": "ability", "turkce": "yetenek", "okunus": "ıbilıti", "seviye": "A2" },
  { "ingilizce": "accountant", "turkce": "muhasebeci", "okunus": "ıkauntınt", "seviye": "A2" },
  { "ingilizce": "actor", "turkce": "aktör", "okunus": "ektır", "seviye": "A1" },
  { "ingilizce": "adviser", "turkce": "danışman", "okunus": "edvayzır", "seviye": "B1" },
  { "ingilizce": "afraid", "turkce": "korkmuş", "okunus": "ıfreyd", "seviye": "A1" },
  { "ingilizce": "amazing", "turkce": "harika/şaşırtıcı", "okunus": "ı meyzing", "seviye": "A1" },
  { "ingilizce": "ancestor", "turkce": "ata", "okunus": "ensestır", "seviye": "B1" },
  { "ingilizce": "ancient", "turkce": "antik", "okunus": "eynşınt", "seviye": "A2" },
  { "ingilizce": "announce", "turkce": "duyurmak", "okunus": "ınauns", "seviye": "B1" },
  { "ingilizce": "aqueduct", "turkce": "su kemeri", "okunus": "ekvidakt", "seviye": "C1" },
  { "ingilizce": "archaeology", "turkce": "arkeoloji", "okunus": "arki alıci", "seviye": "B2" },
  { "ingilizce": "argument", "turkce": "tartışma", "okunus": "argyumınt", "seviye": "A2" },
  { "ingilizce": "armies", "turkce": "ordular", "okunus": "armiz", "seviye": "B1" },
  { "ingilizce": "artist", "turkce": "sanatçı", "okunus": "artıst", "seviye": "A1" },
  { "ingilizce": "assistant", "turkce": "asistan", "okunus": "ı sistınt", "seviye": "A2" },
  { "ingilizce": "avoid", "turkce": "kaçınmak", "okunus": "ıvoyd", "seviye": "A2" },
  { "ingilizce": "biography", "turkce": "biyografi", "okunus": "bayagrafi", "seviye": "B1" },
  { "ingilizce": "catch", "turkce": "yakalamak", "okunus": "keç", "seviye": "A2" },
  { "ingilizce": "celebrity", "turkce": "ünlü kişi", "okunus": "selebriti", "seviye": "A2" },
  { "ingilizce": "charity", "turkce": "hayır kurumu", "okunus": "çerıti", "seviye": "A2" },
  { "ingilizce": "cleaner", "turkce": "temizlikçi", "okunus": "klinır", "seviye": "A2" },
  { "ingilizce": "coin", "turkce": "madeni para", "okunus": "koyn", "seviye": "A2" },
  { "ingilizce": "contact", "turkce": "temas/iletişim", "okunus": "kantakt", "seviye": "A2" },
  { "ingilizce": "currency", "turkce": "para birimi", "okunus": "kırınsi", "seviye": "B1" },
  { "ingilizce": "death", "turkce": "ölüm", "okunus": "det", "seviye": "A2" },
  { "ingilizce": "destroy", "turkce": "yok etmek", "okunus": "distroy", "seviye": "A2" },
  { "ingilizce": "discovery", "turkce": "keşif", "okunus": "diskavri", "seviye": "B1" },
  { "ingilizce": "distant", "turkce": "uzak", "okunus": "distınt", "seviye": "B1" },
  { "ingilizce": "dressmaker", "turkce": "terzi", "okunus": "dresmeykır", "seviye": "B2" },
  { "ingilizce": "economist", "turkce": "ekonomist", "okunus": "ikanı mist", "seviye": "B1" },
  { "ingilizce": "electrician", "turkce": "elektrikçi", "okunus": "ilek trişın", "seviye": "A2" },
  { "ingilizce": "empire", "turkce": "imparatorluk", "okunus": "empayır", "seviye": "B1" },
  { "ingilizce": "environment", "turkce": "çevre", "okunus": "invayrınmınt", "seviye": "A2" },
  { "ingilizce": "execute", "turkce": "idam etmek/yürütmek", "okunus": "ekzekyut", "seviye": "B2" },
  { "ingilizce": "exhibition", "turkce": "sergi", "okunus": "eksi bişın", "seviye": "B1" },
  { "ingilizce": "expense", "turkce": "masraf", "okunus": "ikspens", "seviye": "B1" },
  { "ingilizce": "fame", "turkce": "şöhret", "okunus": "feym", "seviye": "B1" },
  { "ingilizce": "footsteps", "turkce": "ayak izleri", "okunus": "futsteps", "seviye": "B1" },
  { "ingilizce": "foreign", "turkce": "yabancı", "okunus": "forın", "seviye": "A2" },
  { "ingilizce": "glove", "turkce": "eldiven", "okunus": "glav", "seviye": "A1" },
  { "ingilizce": "government", "turkce": "hükümet", "okunus": "gavırn mınt", "seviye": "A2" },
  { "ingilizce": "homeless", "turkce": "evsiz", "okunus": "homlıs", "seviye": "A2" },
  { "ingilizce": "interpreter", "turkce": "tercüman", "okunus": "intörpritır", "seviye": "B1" },
  { "ingilizce": "invade", "turkce": "istila etmek", "okunus": "inveyd", "seviye": "B1" },
  { "ingilizce": "inventor", "turkce": "mucit", "okunus": "inventır", "seviye": "B1" },
  { "ingilizce": "join", "turkce": "katılmak", "okunus": "coyn", "seviye": "A1" },
  { "ingilizce": "kitten", "turkce": "kedi yavrusu", "okunus": "kitın", "seviye": "A1" },
  { "ingilizce": "landmines", "turkce": "mayınlar", "okunus": "lendmaynz", "seviye": "B2" },
  { "ingilizce": "leprosy", "turkce": "cüzzam", "okunus": "leprısi", "seviye": "C1" },
  { "ingilizce": "lifetime", "turkce": "ömür boyu", "okunus": "layftaym", "seviye": "B1" },
  { "ingilizce": "minced meat", "turkce": "kıyma", "okunus": "minst mit", "seviye": "B2" },
  { "ingilizce": "minefield", "turkce": "mayın tarlası", "okunus": "mayn fild", "seviye": "B2" },
  { "ingilizce": "musician", "turkce": "müzisyen", "okunus": "myuzi şın", "seviye": "A2" },
  { "ingilizce": "ordinary", "turkce": "sıradan", "okunus": "ordınri", "seviye": "A2" },
  { "ingilizce": "orphan", "turkce": "yetim", "okunus": "orfın", "seviye": "B1" },
  { "ingilizce": "passion", "turkce": "tutku", "okunus": "peşın", "seviye": "B1" },
  { "ingilizce": "patron", "turkce": "hami/destekçi", "okunus": "peyt rın", "seviye": "C1" },
  { "ingilizce": "pharaoh", "turkce": "firavun", "okunus": "ferov", "seviye": "B2" },
  { "ingilizce": "politician", "turkce": "politikacı", "okunus": "palı tişın", "seviye": "A2" },
  { "ingilizce": "professor", "turkce": "profesör", "okunus": "prı fesır", "seviye": "A2" },
  { "ingilizce": "protester", "turkce": "protestocu", "okunus": "prıtestır", "seviye": "B1" },
  { "ingilizce": "public", "turkce": "halka açık/kamu", "okunus": "pablik", "seviye": "A2" },
  { "ingilizce": "recently", "turkce": "son zamanlarda", "okunus": "risıntli", "seviye": "A2" },
  { "ingilizce": "refugees", "turkce": "mülteciler", "okunus": "refyuciz", "seviye": "B1" },
  { "ingilizce": "regularly", "turkce": "düzenli olarak", "okunus": "regyulırli", "seviye": "A2" },
  { "ingilizce": "reminder", "turkce": "hatırlatıcı", "okunus": "ri mayndır", "seviye": "B1" },
  { "ingilizce": "research", "turkce": "araştırma", "okunus": "ri sörç", "seviye": "A2" },
  { "ingilizce": "reservation", "turkce": "rezervasyon", "okunus": "rezır veyşın", "seviye": "B1" },
  { "ingilizce": "set up", "turkce": "kurmak", "okunus": "set ap", "seviye": "A2" },
  { "ingilizce": "sewage", "turkce": "kanalizasyon", "okunus": "suic", "seviye": "B2" },
  { "ingilizce": "shelter", "turkce": "barınak", "okunus": "şeltır", "seviye": "B1" },
  { "ingilizce": "shipyard", "turkce": "tersane", "okunus": "şip yard", "seviye": "B2" },
  { "ingilizce": "soldier", "turkce": "asker", "okunus": "solcır", "seviye": "A2" },
  { "ingilizce": "solo artist", "turkce": "solo sanatçı", "okunus": "solo artıst", "seviye": "B1" },
  { "ingilizce": "straight", "turkce": "düz", "okunus": "streyt", "seviye": "A2" },
  { "ingilizce": "taxes", "turkce": "vergiler", "okunus": "teksiz", "seviye": "A2" },
  { "ingilizce": "tent", "turkce": "çadır", "okunus": "tent", "seviye": "A1" },
  { "ingilizce": "tomb", "turkce": "mezar", "okunus": "tum", "seviye": "B1" },
  { "ingilizce": "underpants", "turkce": "külot/iç çamaşırı", "okunus": "andırpents", "seviye": "A2" },
  { "ingilizce": "victim", "turkce": "kurban", "okunus": "viktim", "seviye": "B1" },
  { "ingilizce": "wide", "turkce": "geniş", "okunus": "vayd", "seviye": "A1" },
  { "ingilizce": "wildlife", "turkce": "vahşi yaşam", "okunus": "vayld layf", "seviye": "B1" },
  { "ingilizce": "adore", "turkce": "tapmak/çok sevmek", "okunus": "ıdor", "seviye": "B1" },
  { "ingilizce": "bridge", "turkce": "köprü", "okunus": "bric", "seviye": "A1" },
  { "ingilizce": "bright", "turkce": "parlak", "okunus": "brayt", "seviye": "A2" },
  { "ingilizce": "building", "turkce": "bina", "okunus": "bildiŋ", "seviye": "A1" },
  { "ingilizce": "calm", "turkce": "sakin", "okunus": "kam", "seviye": "A2" },
  { "ingilizce": "collection", "turkce": "koleksiyon", "okunus": "kılekşın", "seviye": "A2" },
  { "ingilizce": "composer", "turkce": "besteci", "okunus": "kımpozır", "seviye": "B1" },
  { "ingilizce": "concert", "turkce": "konser", "okunus": "kansirt", "seviye": "A1" },
  { "ingilizce": "concert hall", "turkce": "konser salonu", "okunus": "kansirt hol", "seviye": "A2" },
  { "ingilizce": "cosmopolitan", "turkce": "kozmopolit", "okunus": "kazmı palıtin", "seviye": "C1" },
  { "ingilizce": "dirty", "turkce": "kirli", "okunus": "dörti", "seviye": "A1" },
  { "ingilizce": "experience", "turkce": "tecrübe", "okunus": "iks piriyıns", "seviye": "A2" },
  { "ingilizce": "factory", "turkce": "fabrika", "okunus": "fektri", "seviye": "A2" },
  { "ingilizce": "fierce", "turkce": "şiddetli/vahşi", "okunus": "firs", "seviye": "B2" },
  { "ingilizce": "fireplace", "turkce": "şömine", "okunus": "fayır pleys", "seviye": "B1" },
  { "ingilizce": "friendly", "turkce": "dost canlısı", "okunus": "frendli", "seviye": "A1" },
  { "ingilizce": "glad", "turkce": "memnun", "okunus": "gled", "seviye": "A2" },
  { "ingilizce": "gorgeous", "turkce": "muhteşem", "okunus": "gorcıs", "seviye": "B1" },
  { "ingilizce": "iron", "turkce": "demir", "okunus": "ayırn", "seviye": "A2" },
  { "ingilizce": "jungle", "turkce": "orman (balta girmemiş)", "okunus": "cangıl", "seviye": "A2" },
  { "ingilizce": "lightning", "turkce": "şimşek", "okunus": "laytning", "seviye": "A2" },
  { "ingilizce": "mood", "turkce": "ruh hali", "okunus": "mud", "seviye": "B1" },
  { "ingilizce": "mysterious", "turkce": "gizemli", "okunus": "mistiriyıs", "seviye": "B1" },
  { "ingilizce": "negative", "turkce": "olumsuz", "okunus": "negıtiv", "seviye": "B1" },
  { "ingilizce": "nightlife", "turkce": "gece hayatı", "okunus": "nayt layf", "seviye": "B1" },
  { "ingilizce": "opposite", "turkce": "karşı/zıt", "okunus": "apızit", "seviye": "A2" },
  { "ingilizce": "out of focus", "turkce": "odaklanmamış/bulanık", "okunus": "aut of fokıs", "seviye": "B2" },
  { "ingilizce": "parcel", "turkce": "koli/paket", "okunus": "parsıl", "seviye": "A2" },
  { "ingilizce": "photographer", "turkce": "fotoğrafçı", "okunus": "fıtografır", "seviye": "A2" },
  { "ingilizce": "pleased", "turkce": "memnun", "okunus": "plizd", "seviye": "A2" },
  { "ingilizce": "population", "turkce": "nüfus", "okunus": "papyu leyşın", "seviye": "B1" },
  { "ingilizce": "pretend", "turkce": "gibi yapmak", "okunus": "pritend", "seviye": "A2" },
  { "ingilizce": "proud", "turkce": "gururlu", "okunus": "pra ud", "seviye": "A2" },
  { "ingilizce": "qualified", "turkce": "nitelikli", "okunus": "kualifayd", "seviye": "B1" },
  { "ingilizce": "rediscover", "turkce": "yeniden keşfetmek", "okunus": "ri diskavır", "seviye": "B2" },
  { "ingilizce": "reliable", "turkce": "güvenilir", "okunus": "rilaybıl", "seviye": "B1" },
  { "ingilizce": "rude", "turkce": "kaba", "okunus": "rud", "seviye": "A2" },
  { "ingilizce": "salary", "turkce": "maaş", "okunus": "selıri", "seviye": "B1" },
  { "ingilizce": "salty", "turkce": "tuzlu", "okunus": "solti", "seviye": "A2" },
  { "ingilizce": "screen saver", "turkce": "ekran koruyucu", "okunus": "skrin seyvır", "seviye": "B2" },
  { "ingilizce": "sculptor", "turkce": "heykeltıraş", "okunus": "skalp tır", "seviye": "B2" },
  { "ingilizce": "shadow", "turkce": "gölge", "okunus": "şedov", "seviye": "A2" },
  { "ingilizce": "skyscraper", "turkce": "gökdelen", "okunus": "skays krey pır", "seviye": "B1" },
  { "ingilizce": "specialize", "turkce": "uzmanlaşmak", "okunus": "speşı layz", "seviye": "B1" },
  { "ingilizce": "steel", "turkce": "çelik", "okunus": "stil", "seviye": "B1" },
  { "ingilizce": "storm", "turkce": "fırtına", "okunus": "storm", "seviye": "A1" },
  { "ingilizce": "stupid", "turkce": "aptal", "okunus": "styupid", "seviye": "A1" },
  { "ingilizce": "terrified", "turkce": "dehşete düşmüş", "okunus": "terifayd", "seviye": "B1" },
  { "ingilizce": "thunder", "turkce": "gök gürültüsü", "okunus": "tandır", "seviye": "A2" },
  { "ingilizce": "tour", "turkce": "tur", "okunus": "tur", "seviye": "A1" },
  { "ingilizce": "turtle", "turkce": "kaplumbağa", "okunus": "törtıl", "seviye": "A1" },
  { "ingilizce": "unique", "turkce": "benzersiz", "okunus": "yunik", "seviye": "B1" },
  { "ingilizce": "view", "turkce": "manzara", "okunus": "vyu", "seviye": "A2" },
  { "ingilizce": "virtual", "turkce": "sanal", "okunus": "vörçıl", "seviye": "B1" },
  { "ingilizce": "waste", "turkce": "israf etmek/atık", "okunus": "veyst", "seviye": "A2" },
  { "ingilizce": "well-known", "turkce": "iyi bilinen", "okunus": "vel non", "seviye": "A2" },
  { "ingilizce": "ache", "turkce": "ağrı/sızı", "okunus": "eyk", "seviye": "B1" },
  { "ingilizce": "advertisement", "turkce": "reklam", "okunus": "edvörtayzmınt", "seviye": "A2" },
  { "ingilizce": "advice", "turkce": "tavsiye", "okunus": "edvays", "seviye": "A2" },
  { "ingilizce": "allergy", "turkce": "alerji", "okunus": "elıci", "seviye": "B1" },
  { "ingilizce": "ambulance", "turkce": "ambulans", "okunus": "embyılıns", "seviye": "A1" },
  { "ingilizce": "ankle", "turkce": "ayak bileği", "okunus": "engkıl", "seviye": "A2" },
  { "ingilizce": "application form", "turkce": "başvuru formu", "okunus": "eplikeyşın form", "seviye": "B1" },
  { "ingilizce": "archery", "turkce": "okçuluk", "okunus": "arçiri", "seviye": "B2" },
  { "ingilizce": "arm", "turkce": "kol", "okunus": "arm", "seviye": "A1" },
  { "ingilizce": "audition", "turkce": "seçme (oyunculuk)", "okunus": "odişın", "seviye": "B1" },
  { "ingilizce": "be sick", "turkce": "hasta olmak/kusmak", "okunus": "bi sik", "seviye": "A2" },
  { "ingilizce": "belt", "turkce": "kemer", "okunus": "belt", "seviye": "A2" },
  { "ingilizce": "bite", "turkce": "ısırmak", "okunus": "bayt", "seviye": "A2" },
  { "ingilizce": "blow", "turkce": "üflemek", "okunus": "blov", "seviye": "A2" },
  { "ingilizce": "body", "turkce": "vücut", "okunus": "badi", "seviye": "A1" },
  { "ingilizce": "boot", "turkce": "bot", "okunus": "but", "seviye": "A2" },
  { "ingilizce": "boxing", "turkce": "boks", "okunus": "boksing", "seviye": "A2" },
  { "ingilizce": "cap", "turkce": "şapka", "okunus": "kep", "seviye": "A1" },
  { "ingilizce": "chariot", "turkce": "savaş arabası", "okunus": "çeriyıt", "seviye": "C1" },
  { "ingilizce": "chat", "turkce": "sohbet etmek", "okunus": "çet", "seviye": "A1" },
  { "ingilizce": "coach", "turkce": "koç/otobüs", "okunus": "koç", "seviye": "A2" },
  { "ingilizce": "cold", "turkce": "soğuk algınlığı", "okunus": "kold", "seviye": "A1" },
  { "ingilizce": "couch", "turkce": "kanepe", "okunus": "kauç", "seviye": "A2" },
  { "ingilizce": "cough", "turkce": "öksürmek", "okunus": "kof", "seviye": "A2" },
  { "ingilizce": "crash diet", "turkce": "şok diyet", "okunus": "kreş dayıt", "seviye": "B2" },
  { "ingilizce": "depressing", "turkce": "bunalımlı", "okunus": "dipresing", "seviye": "B1" },
  { "ingilizce": "desk", "turkce": "sıra/masa", "okunus": "desk", "seviye": "A1" },
  { "ingilizce": "diarrhoea", "turkce": "ishal", "okunus": "dayı ria", "seviye": "B1" },
  { "ingilizce": "easy-going", "turkce": "uyumlu/rahat", "okunus": "izi goving", "seviye": "B1" },
  { "ingilizce": "equipment", "turkce": "ekipman", "okunus": "ikuipmınt", "seviye": "A2" },
  { "ingilizce": "exercise", "turkce": "egzersiz", "okunus": "eksırsayz", "seviye": "A1" },
  { "ingilizce": "eye", "turkce": "göz", "okunus": "ay", "seviye": "A1" },
  { "ingilizce": "feet", "turkce": "ayaklar", "okunus": "fit", "seviye": "A1" },
  { "ingilizce": "fever", "turkce": "ateş", "okunus": "fivır", "seviye": "A2" },
  { "ingilizce": "finger", "turkce": "parmak", "okunus": "fingır", "seviye": "A1" },
  { "ingilizce": "fit", "turkce": "formda", "okunus": "fit", "seviye": "A2" },
  { "ingilizce": "fitness routine", "turkce": "fitness rutini", "okunus": "fitnıs rutin", "seviye": "B1" },
  { "ingilizce": "flight attendant", "turkce": "kabin memuru", "okunus": "flayt ıten dınt", "seviye": "A2" },
  { "ingilizce": "flu", "turkce": "grip", "okunus": "flu", "seviye": "A2" },
  { "ingilizce": "food poisoning", "turkce": "gıda zehirlenmesi", "okunus": "fud poyzıning", "seviye": "B1" },
  { "ingilizce": "gentle", "turkce": "nazik", "okunus": "centıl", "seviye": "B1" },
  { "ingilizce": "gland", "turkce": "bez (vücutta)", "okunus": "glend", "seviye": "C1" },
  { "ingilizce": "goggles", "turkce": "koruyucu gözlük", "okunus": "gagılz", "seviye": "B1" },
  { "ingilizce": "gymnastics", "turkce": "jimnastik", "okunus": "cimnestiks", "seviye": "A2" },
  { "ingilizce": "hand", "turkce": "el", "okunus": "hend", "seviye": "A1" },
  { "ingilizce": "head", "turkce": "baş", "okunus": "hed", "seviye": "A1" },
  { "ingilizce": "helmet", "turkce": "kask", "okunus": "helmit", "seviye": "A2" },
  { "ingilizce": "high heels", "turkce": "yüksek topuklar", "okunus": "hay hilz", "seviye": "A2" },
  { "ingilizce": "hold your breath", "turkce": "nefesini tutmak", "okunus": "hold yor bret", "seviye": "B1" },
  { "ingilizce": "hoodie", "turkce": "kapüşonlu", "okunus": "hudi", "seviye": "A2" },
  { "ingilizce": "hurt", "turkce": "incinmek/acımak", "okunus": "hört", "seviye": "A2" },
  { "ingilizce": "injury", "turkce": "sakatlık", "okunus": "incıri", "seviye": "A2" },
  { "ingilizce": "jacket", "turkce": "ceket", "okunus": "cekit", "seviye": "A1" },
  { "ingilizce": "jeans", "turkce": "kot pantolon", "okunus": "cinz", "seviye": "A1" },
  { "ingilizce": "knee", "turkce": "diz", "okunus": "ni", "seviye": "A2" },
  { "ingilizce": "leggings", "turkce": "tayt", "okunus": "legingz", "seviye": "B1" },
  { "ingilizce": "leg", "turkce": "bacak", "okunus": "leg", "seviye": "A1" },
  { "ingilizce": "liquid", "turkce": "sıvı", "okunus": "likvid", "seviye": "B1" },
  { "ingilizce": "lose weight", "turkce": "kilo vermek", "okunus": "luz veyt", "seviye": "A2" },
  { "ingilizce": "martial art", "turkce": "dövüş sanatı", "okunus": "marşıl art", "seviye": "B1" },
  { "ingilizce": "mental", "turkce": "zihinsel", "okunus": "mentıl", "seviye": "B1" },
  { "ingilizce": "mind", "turkce": "zihin", "okunus": "maynd", "seviye": "A2" },
  { "ingilizce": "necessary", "turkce": "gerekli", "okunus": "nesısiri", "seviye": "A2" },
  { "ingilizce": "neck", "turkce": "boyun", "okunus": "nek", "seviye": "A1" },
  { "ingilizce": "on the spot", "turkce": "yerinde/hemen", "okunus": "on dı spat", "seviye": "B2" },
  { "ingilizce": "physical", "turkce": "fiziksel", "okunus": "fizikıl", "seviye": "A2" },
  { "ingilizce": "prescribe", "turkce": "reçete yazmak", "okunus": "pris krayb", "seviye": "B1" },
  { "ingilizce": "prescription", "turkce": "reçete", "okunus": "pris kripşın", "seviye": "B1" },
  { "ingilizce": "put on weight", "turkce": "kilo almak", "okunus": "put on veyt", "seviye": "A2" },
  { "ingilizce": "rehydrate", "turkce": "su kaybını gidermek", "okunus": "ri haydreyt", "seviye": "B2" },
  { "ingilizce": "risky", "turkce": "riskli", "okunus": "riski", "seviye": "B1" },
  { "ingilizce": "role", "turkce": "rol", "okunus": "rol", "seviye": "A2" },
  { "ingilizce": "sandals", "turkce": "sandalet", "okunus": "sendılz", "seviye": "A2" },
  { "ingilizce": "scarf", "turkce": "atkı", "okunus": "skarf", "seviye": "A2" },
  { "ingilizce": "sensitive", "turkce": "hassas", "okunus": "sensıtiv", "seviye": "B1" },
  { "ingilizce": "shave", "turkce": "tıraş olmak", "okunus": "şeyv", "seviye": "A2" },
  { "ingilizce": "shirt", "turkce": "gömlek", "okunus": "şört", "seviye": "A1" },
  { "ingilizce": "shorts", "turkce": "şort", "okunus": "şorts", "seviye": "A1" },
  { "ingilizce": "shoulder", "turkce": "omuz", "okunus": "şoldır", "seviye": "A2" },
  { "ingilizce": "skateboarding", "turkce": "kaykay", "okunus": "skeytbording", "seviye": "A2" },
  { "ingilizce": "skip", "turkce": "atlamak (öğün vb.)", "okunus": "skip", "seviye": "A2" },
  { "ingilizce": "skirt", "turkce": "etek", "okunus": "skört", "seviye": "A1" },
  { "ingilizce": "slippery", "turkce": "kaygan", "okunus": "sliperi", "seviye": "B1" },
  { "ingilizce": "sneeze", "turkce": "hapşırmak", "okunus": "sniz", "seviye": "B1" },
  { "ingilizce": "socks", "turkce": "çorap", "okunus": "soks", "seviye": "A1" },
  { "ingilizce": "sore throat", "turkce": "boğaz ağrısı", "okunus": "sor trot", "seviye": "B1" },
  { "ingilizce": "sports vest", "turkce": "spor atleti", "okunus": "sports vest", "seviye": "B2" },
  { "ingilizce": "sprain", "turkce": "burkmak", "okunus": "spreyn", "seviye": "B2" },
  { "ingilizce": "stuff", "turkce": "şeyler/eşya", "okunus": "staf", "seviye": "A2" },
  { "ingilizce": "stuntwoman", "turkce": "kadın dublör", "okunus": "stant vumın", "seviye": "B2" },
  { "ingilizce": "sunglasses", "turkce": "güneş gözlüğü", "okunus": "sanglasız", "seviye": "A1" },
  { "ingilizce": "surfboard", "turkce": "sörf tahtası", "okunus": "sörfbord", "seviye": "B1" },
  { "ingilizce": "surfer", "turkce": "sörfçü", "okunus": "sörfır", "seviye": "A2" },
  { "ingilizce": "swallow", "turkce": "yutmak", "okunus": "svalov", "seviye": "B1" },
  { "ingilizce": "swimsuit", "turkce": "mayo", "okunus": "svimsut", "seviye": "A2" },
  { "ingilizce": "swollen", "turkce": "şişmiş", "okunus": "svolın", "seviye": "B1" },
  { "ingilizce": "sword", "turkce": "kılıç", "okunus": "sord", "seviye": "A2" },
  { "ingilizce": "temperature", "turkce": "sıcaklık/ateş", "okunus": "temprıçır", "seviye": "A2" },
  { "ingilizce": "tie", "turkce": "kravat", "okunus": "tay", "seviye": "A2" },
  { "ingilizce": "toe", "turkce": "ayak parmağı", "okunus": "to", "seviye": "A2" },
  { "ingilizce": "tracksuit", "turkce": "eşofman", "okunus": "trek sut", "seviye": "A2" },
  { "ingilizce": "train", "turkce": "antrenman yapmak", "okunus": "treyn", "seviye": "A1" },
  { "ingilizce": "trainers", "turkce": "spor ayakkabı", "okunus": "treynırz", "seviye": "A2" },
  { "ingilizce": "truck", "turkce": "kamyon", "okunus": "trak", "seviye": "A1" },
  { "ingilizce": "T-shirt", "turkce": "tişört", "okunus": "ti şört", "seviye": "A1" },
  { "ingilizce": "uniform", "turkce": "üniforma", "okunus": "yuniform", "seviye": "A2" },
  { "ingilizce": "waist", "turkce": "bel", "okunus": "veyst", "seviye": "A2" },
  { "ingilizce": "warm up", "turkce": "ısınmak", "okunus": "vorm ap", "seviye": "A2" },
  { "ingilizce": "watch", "turkce": "kol saati", "okunus": "voç", "seviye": "A1" },
  { "ingilizce": "wave", "turkce": "dalga", "okunus": "veyv", "seviye": "A2" },
  { "ingilizce": "wheel", "turkce": "tekerlek", "okunus": "vil", "seviye": "A2" },
  { "ingilizce": "wrist", "turkce": "bilek", "okunus": "rist", "seviye": "B1" },
  { "ingilizce": "annoyed", "turkce": "rahatsız olmuş", "okunus": "ı noy d", "seviye": "A2" },
  { "ingilizce": "atomic bomb", "turkce": "atom bombası", "okunus": "ı to mik bam", "seviye": "B2" },
  { "ingilizce": "audience", "turkce": "seyirci", "okunus": "odiyıns", "seviye": "A2" },
  { "ingilizce": "bark", "turkce": "havlamak", "okunus": "bark", "seviye": "A2" },
  { "ingilizce": "behave", "turkce": "davranmak", "okunus": "bi heyv", "seviye": "A2" },
  { "ingilizce": "being", "turkce": "varlık", "okunus": "bi ing", "seviye": "B1" },
  { "ingilizce": "chase", "turkce": "kovalamak", "okunus": "çeys", "seviye": "A2" },
  { "ingilizce": "clap", "turkce": "alkışlamak", "okunus": "klep", "seviye": "A2" },
  { "ingilizce": "complex", "turkce": "karmaşık", "okunus": "kam pleks", "seviye": "B1" },
  { "ingilizce": "doll", "turkce": "oyuncak bebek", "okunus": "dal", "seviye": "A1" },
  { "ingilizce": "graduate", "turkce": "mezun olmak", "okunus": "grecu eyt", "seviye": "B1" },
  { "ingilizce": "graveyard", "turkce": "mezarlık", "okunus": "greyv yard", "seviye": "B2" },
  { "ingilizce": "heartbroken", "turkce": "kalbi kırık", "okunus": "hart brokın", "seviye": "B1" },
  { "ingilizce": "lecture", "turkce": "ders/konferans", "okunus": "lekçır", "seviye": "B1" },
  { "ingilizce": "literature", "turkce": "edebiyat", "okunus": "litırıçır", "seviye": "B1" },
  { "ingilizce": "lock", "turkce": "kilitlemek", "okunus": "lak", "seviye": "A2" },
  { "ingilizce": "lonely", "turkce": "yalnız", "okunus": "lonli", "seviye": "A2" },
  { "ingilizce": "memory", "turkce": "hafıza/anı", "okunus": "memıri", "seviye": "A2" },
  { "ingilizce": "monster", "turkce": "canavar", "okunus": "manstır", "seviye": "A1" },
  { "ingilizce": "moral", "turkce": "kıssadan hisse/ahlak", "okunus": "morıl", "seviye": "B1" },
  { "ingilizce": "naughty", "turkce": "yaramaz", "okunus": "noti", "seviye": "B1" },
  { "ingilizce": "nervous", "turkce": "gergin", "okunus": "nörvıs", "seviye": "A2" },
  { "ingilizce": "novel", "turkce": "roman", "okunus": "navıl", "seviye": "A2" },
  { "ingilizce": "overjoyed", "turkce": "aşırı mutlu", "okunus": "ovır coyd", "seviye": "B2" },
  { "ingilizce": "poor", "turkce": "fakir", "okunus": "pur", "seviye": "A1" },
  { "ingilizce": "possession", "turkce": "sahiplik/eşya", "okunus": "pızeşın", "seviye": "B1" },
  { "ingilizce": "sack", "turkce": "çuval", "okunus": "sek", "seviye": "B1" },
  { "ingilizce": "shake", "turkce": "sallamak/titremek", "okunus": "şeyk", "seviye": "A2" },
  { "ingilizce": "simple", "turkce": "basit", "okunus": "sim pıl", "seviye": "A1" },
  { "ingilizce": "society", "turkce": "toplum", "okunus": "sı sayıti", "seviye": "A2" },
  { "ingilizce": "stranger", "turkce": "yabancı", "okunus": "streyncır", "seviye": "A2" },
  { "ingilizce": "stressed", "turkce": "stresli", "okunus": "strest", "seviye": "A2" },
  { "ingilizce": "swap", "turkce": "takas etmek", "okunus": "svap", "seviye": "B1" },
  { "ingilizce": "ugly", "turkce": "çirkin", "okunus": "agli", "seviye": "A2" },
  { "ingilizce": "upset", "turkce": "üzgün", "okunus": "ap set", "seviye": "A2" },
  { "ingilizce": "wise", "turkce": "bilge", "okunus": "vayz", "seviye": "B1" },
  { "ingilizce": "yard", "turkce": "avlu/yarda", "okunus": "yard", "seviye": "A2" },
  { "ingilizce": "addicted", "turkce": "bağımlı", "okunus": "ıdiktıd", "seviye": "B1" },
  { "ingilizce": "artificial intelligence", "turkce": "yapay zeka", "okunus": "arti fişıl intelicıns", "seviye": "B1" },
  { "ingilizce": "ballpoint pen", "turkce": "tükenmez kalem", "okunus": "bolpoint pen", "seviye": "A2" },
  { "ingilizce": "breath", "turkce": "nefes", "okunus": "bret", "seviye": "A2" },
  { "ingilizce": "broadcast", "turkce": "yayın yapmak", "okunus": "brod kast", "seviye": "B1" },
  { "ingilizce": "chew", "turkce": "çiğnemek", "okunus": "çu", "seviye": "A2" },
  { "ingilizce": "chum", "turkce": "kafa dengi arkadaş", "okunus": "çam", "seviye": "C1" },
  { "ingilizce": "disadvantage", "turkce": "dezavantaj", "okunus": "disıd vantic", "seviye": "B1" },
  { "ingilizce": "export", "turkce": "ihraç etmek", "okunus": "eksport", "seviye": "B1" },
  { "ingilizce": "fan", "turkce": "hayran/taraftar", "okunus": "fen", "seviye": "A1" },
  { "ingilizce": "flood", "turkce": "sel basmak/taşmak", "okunus": "flad", "seviye": "A2" },
  { "ingilizce": "football ground", "turkce": "futbol sahası", "okunus": "futbol graund", "seviye": "A2" },
  { "ingilizce": "found", "turkce": "kurmak", "okunus": "faund", "seviye": "B1" },
  { "ingilizce": "freshen", "turkce": "tazelemek", "okunus": "freşın", "seviye": "B2" },
  { "ingilizce": "genius", "turkce": "dahi", "okunus": "ciniyıs", "seviye": "A2" },
  { "ingilizce": "glory", "turkce": "şan/şeref", "okunus": "glori", "seviye": "B1" },
  { "ingilizce": "hand-held", "turkce": "elde taşınan", "okunus": "hend held", "seviye": "B1" },
  { "ingilizce": "invention", "turkce": "icat", "okunus": "invenşın", "seviye": "A2" },
  { "ingilizce": "kill", "turkce": "öldürmek", "okunus": "kil", "seviye": "A1" },
  { "ingilizce": "landline", "turkce": "sabit hat", "okunus": "lend layn", "seviye": "B1" },
  { "ingilizce": "launch", "turkce": "fırlatmak/başlatmak", "okunus": "lonç", "seviye": "B1" },
  { "ingilizce": "logo", "turkce": "logo", "okunus": "logo", "seviye": "A2" },
  { "ingilizce": "master", "turkce": "uzmanlaşmak", "okunus": "mastır", "seviye": "B1" },
  { "ingilizce": "private", "turkce": "özel", "okunus": "prayvıt", "seviye": "A2" },
  { "ingilizce": "put someone through", "turkce": "telefonu bağlamak", "okunus": "put samvan tru", "seviye": "B2" },
  { "ingilizce": "respond", "turkce": "yanıt vermek", "okunus": "rispond", "seviye": "B1" },
  { "ingilizce": "rubber", "turkce": "kauçuk/silgi", "okunus": "rabır", "seviye": "A2" },
  { "ingilizce": "simplicity", "turkce": "basitlik", "okunus": "simplisıti", "seviye": "B1" },
  { "ingilizce": "skeleton", "turkce": "iskelet", "okunus": "skelitın", "seviye": "A2" },
  { "ingilizce": "software", "turkce": "yazılım", "okunus": "softver", "seviye": "A2" },
  { "ingilizce": "statistics", "turkce": "istatistik", "okunus": "stı tis tiks", "seviye": "B1" },
  { "ingilizce": "tag", "turkce": "etiketlemek", "okunus": "teg", "seviye": "A2" },
  { "ingilizce": "tree sap", "turkce": "ağaç özü", "okunus": "tri sep", "seviye": "B2" },
  { "ingilizce": "trillion", "turkce": "trilyon", "okunus": "trilyın", "seviye": "B1" },
  { "ingilizce": "trophy", "turkce": "kupa/ödül", "okunus": "trofi", "seviye": "A2" },
  { "ingilizce": "valuable", "turkce": "değerli", "okunus": "velyubıl", "seviye": "A2" },
  { "ingilizce": "version", "turkce": "versiyon", "okunus": "vörşın", "seviye": "A2" },
  { "ingilizce": "waste time", "turkce": "zaman harcamak", "okunus": "veyst taym", "seviye": "A2" },
  { "ingilizce": "accidentally", "turkce": "kazara", "okunus": "eksidentıli", "seviye": "A2" },
  { "ingilizce": "anniversary", "turkce": "yıl dönümü", "okunus": "enıvörsıri", "seviye": "A2" },
  { "ingilizce": "appreciate", "turkce": "takdir etmek", "okunus": "ıprişieyt", "seviye": "B1" },
  { "ingilizce": "astronomer", "turkce": "astronom", "okunus": "ıstranımır", "seviye": "B1" },
  { "ingilizce": "bridesmaid", "turkce": "nedime", "okunus": "braydzmeyd", "seviye": "B1" },
  { "ingilizce": "cabbage", "turkce": "lahana", "okunus": "kebic", "seviye": "A2" },
  { "ingilizce": "collector", "turkce": "koleksiyoncu", "okunus": "kılektır", "seviye": "A2" },
  { "ingilizce": "commemorative", "turkce": "anma/hatıra", "okunus": "kıme mırıtiv", "seviye": "C1" },
  { "ingilizce": "cope", "turkce": "başa çıkmak", "okunus": "kop", "seviye": "B1" },
  { "ingilizce": "demand", "turkce": "talep etmek", "okunus": "dimand", "seviye": "B1" },
  { "ingilizce": "demanding", "turkce": "talepkar/zorlu", "okunus": "dimanding", "seviye": "B1" },
  { "ingilizce": "due", "turkce": "vadesi dolmuş/beklenen", "okunus": "dyu", "seviye": "B1" },
  { "ingilizce": "duplicate", "turkce": "kopya/benzer", "okunus": "dyuplikit", "seviye": "B2" },
  { "ingilizce": "engaged", "turkce": "nişanlı", "okunus": "inge ycd", "seviye": "A2" },
  { "ingilizce": "entrepreneur", "turkce": "girişimci", "okunus": "antrıprınör", "seviye": "B1" },
  { "ingilizce": "fail", "turkce": "başarısız olmak", "okunus": "feyl", "seviye": "A2" },
  { "ingilizce": "forbidden", "turkce": "yasak", "okunus": "forbidın", "seviye": "B1" },
  { "ingilizce": "funeral", "turkce": "cenaze", "okunus": "fyunırıl", "seviye": "A2" },
  { "ingilizce": "garage", "turkce": "garaj/tamirhane", "okunus": "gırac", "seviye": "A1" },
  { "ingilizce": "healthcare", "turkce": "sağlık hizmeti", "okunus": "heltker", "seviye": "B1" },
  { "ingilizce": "honeymoon", "turkce": "balayı", "okunus": "hanimun", "seviye": "A2" },
  { "ingilizce": "influence", "turkce": "etkilemek", "okunus": "influıns", "seviye": "B1" },
  { "ingilizce": "keyboard", "turkce": "klavye/org", "okunus": "ki bord", "seviye": "A2" },
  { "ingilizce": "life expectancy", "turkce": "ortalama yaşam süresi", "okunus": "layf ikspektınsi", "seviye": "B2" },
  { "ingilizce": "married", "turkce": "evli", "okunus": "merid", "seviye": "A1" },
  { "ingilizce": "memorabilia", "turkce": "hatıra eşyalar", "okunus": "memıra biliya", "seviye": "C1" },
  { "ingilizce": "never-ending", "turkce": "bitmeyen", "okunus": "nevır ending", "seviye": "B1" },
  { "ingilizce": "optimistic", "turkce": "iyimser", "okunus": "aptımistik", "seviye": "B1" },
  { "ingilizce": "peer", "turkce": "akran", "okunus": "pir", "seviye": "B1" },
  { "ingilizce": "pessimistic", "turkce": "kötümser", "okunus": "pesımistik", "seviye": "B1" },
  { "ingilizce": "physicist", "turkce": "fizikçi", "okunus": "fizisist", "seviye": "B1" },
  { "ingilizce": "poetry", "turkce": "şiir sanatı", "okunus": "poıtri", "seviye": "B1" },
  { "ingilizce": "pregnant", "turkce": "hamile", "okunus": "preg nınt", "seviye": "A2" },
  { "ingilizce": "raindrop", "turkce": "yağmur damlası", "okunus": "reyndrap", "seviye": "A2" },
  { "ingilizce": "regret", "turkce": "pişmanlık", "okunus": "rigret", "seviye": "B1" },
  { "ingilizce": "renewed", "turkce": "yenilenmiş", "okunus": "ri nyud", "seviye": "B1" },
  { "ingilizce": "repair", "turkce": "tamir etmek", "okunus": "riper", "seviye": "A2" },
  { "ingilizce": "resources", "turkce": "kaynaklar", "okunus": "ri sorsız", "seviye": "B1" },
  { "ingilizce": "rocket", "turkce": "roket", "okunus": "rakit", "seviye": "A2" },
  { "ingilizce": "selfish", "turkce": "bencil", "okunus": "selfiş", "seviye": "A2" },
  { "ingilizce": "serious", "turkce": "ciddi", "okunus": "siriyıs", "seviye": "A2" },
  { "ingilizce": "servant", "turkce": "hizmetçi", "okunus": "sörvınt", "seviye": "B1" },
  { "ingilizce": "split up", "turkce": "ayrılmak", "okunus": "split ap", "seviye": "A2" },
  { "ingilizce": "stick", "turkce": "sopa/baston", "okunus": "stik", "seviye": "A2" },
  { "ingilizce": "surrogate", "turkce": "taşıyıcı (anne)", "okunus": "sörı git", "seviye": "C1" },
  { "ingilizce": "tragedy", "turkce": "trajedi", "okunus": "trecidi", "seviye": "B1" },
  { "ingilizce": "unsaid", "turkce": "söylenmemiş", "okunus": "an sed", "seviye": "B2" },
  { "ingilizce": "wealth", "turkce": "servet", "okunus": "velt", "seviye": "B1" },
  { "ingilizce": "widowed", "turkce": "dul kalmış", "okunus": "vidov d", "seviye": "B1" },
  { "ingilizce": "barbecue", "turkce": "mangal", "okunus": "barbikyu", "seviye": "A2" },
  { "ingilizce": "biscuit", "turkce": "bisküvi", "okunus": "biskit", "seviye": "A1" },
  { "ingilizce": "boomerang", "turkce": "bumerang", "okunus": "bumıreng", "seviye": "B1" },
  { "ingilizce": "campus", "turkce": "kampüs", "okunus": "kempıs", "seviye": "A2" },
  { "ingilizce": "coincidence", "turkce": "tesadüf", "okunus": "ko insidıns", "seviye": "B1" },
  { "ingilizce": "confuse", "turkce": "kafasını karıştırmak", "okunus": "kınfyuz", "seviye": "A2" },
  { "ingilizce": "drop out", "turkce": "okulu bırakmak", "okunus": "drop aut", "seviye": "B1" },
  { "ingilizce": "economics", "turkce": "ekonomi", "okunus": "ikonomiks", "seviye": "B1" },
  { "ingilizce": "go", "turkce": "gitmek", "okunus": "gov", "seviye": "A1" },
  { "ingilizce": "come", "turkce": "gelmek", "okunus": "kam", "seviye": "A1" },
  { "ingilizce": "make", "turkce": "yapmak", "okunus": "meyk", "seviye": "A1" },
  { "ingilizce": "want", "turkce": "istemek", "okunus": "vont", "seviye": "A1" },
  { "ingilizce": "need", "turkce": "ihtiyaç duymak", "okunus": "nid", "seviye": "A1" },
  { "ingilizce": "like", "turkce": "hoşlanmak", "okunus": "layk", "seviye": "A1" },
  { "ingilizce": "use", "turkce": "kullanmak", "okunus": "yuz", "seviye": "A1" },
  { "ingilizce": "know", "turkce": "bilmek", "okunus": "nov", "seviye": "A1" },
  { "ingilizce": "think", "turkce": "düşünmek", "okunus": "tink", "seviye": "A1" },
  { "ingilizce": "get", "turkce": "almak/olmak", "okunus": "get", "seviye": "A1" },
  { "ingilizce": "give", "turkce": "vermek", "okunus": "giv", "seviye": "A1" },
  { "ingilizce": "take", "turkce": "almak", "okunus": "teyk", "seviye": "A1" },
  { "ingilizce": "put", "turkce": "koymak", "okunus": "put", "seviye": "A1" },
  { "ingilizce": "say", "turkce": "söylemek", "okunus": "sey", "seviye": "A1" },
  { "ingilizce": "ask", "turkce": "sormak", "okunus": "ask", "seviye": "A1" },
  { "ingilizce": "help", "turkce": "yardım etmek", "okunus": "help", "seviye": "A1" },
  { "ingilizce": "live", "turkce": "yaşamak", "okunus": "liv", "seviye": "A1" },
  { "ingilizce": "find", "turkce": "bulmak", "okunus": "faynd", "seviye": "A1" },
  { "ingilizce": "start", "turkce": "başlamak", "okunus": "start", "seviye": "A1" },
  { "ingilizce": "stop", "turkce": "durmak", "okunus": "stap", "seviye": "A1" },
  { "ingilizce": "open", "turkce": "açmak", "okunus": "opın", "seviye": "A1" },
  { "ingilizce": "close", "turkce": "kapatmak", "okunus": "kloz", "seviye": "A1" },
  { "ingilizce": "buy", "turkce": "satın almak", "okunus": "bay", "seviye": "A1" },
  { "ingilizce": "sell", "turkce": "satmak", "okunus": "sel", "seviye": "A1" },
  { "ingilizce": "wear", "turkce": "giymek", "okunus": "ver", "seviye": "A1" },
  { "ingilizce": "water", "turkce": "su", "okunus": "votır", "seviye": "A1" },
  { "ingilizce": "house", "turkce": "ev", "okunus": "haus", "seviye": "A1" },
  { "ingilizce": "family", "turkce": "aile", "okunus": "femili", "seviye": "A1" },
  { "ingilizce": "friend", "turkce": "arkadaş", "okunus": "frend", "seviye": "A1" },
  { "ingilizce": "school", "turkce": "okul", "okunus": "skul", "seviye": "A1" },
  { "ingilizce": "city", "turkce": "şehir", "okunus": "siti", "seviye": "A1" },
  { "ingilizce": "morning", "turkce": "sabah", "okunus": "morning", "seviye": "A1" },
  { "ingilizce": "evening", "turkce": "akşam", "okunus": "ivning", "seviye": "A1" },
  { "ingilizce": "week", "turkce": "hafta", "okunus": "vik", "seviye": "A1" },
  { "ingilizce": "month", "turkce": "ay (takvim)", "okunus": "mant", "seviye": "A1" },
  { "ingilizce": "year", "turkce": "yıl", "okunus": "yiır", "seviye": "A1" },
  { "ingilizce": "animal", "turkce": "hayvan", "okunus": "enimıl", "seviye": "A1" },
  { "ingilizce": "dog", "turkce": "köpek", "okunus": "dog", "seviye": "A1" },
  { "ingilizce": "cat", "turkce": "kedi", "okunus": "ket", "seviye": "A1" },
  { "ingilizce": "apple", "turkce": "elma", "okunus": "epıl", "seviye": "A1" },
  { "ingilizce": "milk", "turkce": "süt", "okunus": "milk", "seviye": "A1" },
  { "ingilizce": "bread", "turkce": "ekmek", "okunus": "bred", "seviye": "A1" },
  { "ingilizce": "egg", "turkce": "yumurta", "okunus": "eg", "seviye": "A1" },
  { "ingilizce": "fish", "turkce": "balık", "okunus": "fiş", "seviye": "A1" },
  { "ingilizce": "chicken", "turkce": "tavuk", "okunus": "çikın", "seviye": "A1" },
  { "ingilizce": "rain", "turkce": "yağmur", "okunus": "reyn", "seviye": "A1" },
  { "ingilizce": "snow", "turkce": "kar", "okunus": "snov", "seviye": "A1" },
  { "ingilizce": "wind", "turkce": "rüzgar", "okunus": "vind", "seviye": "A1" },
  { "ingilizce": "cloud", "turkce": "bulut", "okunus": "klaud", "seviye": "A1" },
  { "ingilizce": "sun", "turkce": "güneş", "okunus": "san", "seviye": "A1" },
  { "ingilizce": "moon", "turkce": "ay (gök)", "okunus": "mun", "seviye": "A1" },
  { "ingilizce": "star", "turkce": "yıldız", "okunus": "star", "seviye": "A1" },
  { "ingilizce": "sky", "turkce": "gökyüzü", "okunus": "skay", "seviye": "A1" },
  { "ingilizce": "tree", "turkce": "ağaç", "okunus": "tri", "seviye": "A1" },
  { "ingilizce": "flower", "turkce": "çiçek", "okunus": "flauır", "seviye": "A1" },
  { "ingilizce": "river", "turkce": "nehir", "okunus": "rivır", "seviye": "A1" },
  { "ingilizce": "sea", "turkce": "deniz", "okunus": "si", "seviye": "A1" },
  { "ingilizce": "hot", "turkce": "sıcak", "okunus": "hat", "seviye": "A1" },
  { "ingilizce": "young", "turkce": "genç", "okunus": "yang", "seviye": "A1" },
  { "ingilizce": "accept", "turkce": "kabul etmek", "okunus": "iksept", "seviye": "A2" },
  { "ingilizce": "account", "turkce": "hesap", "okunus": "ıkaunt", "seviye": "A2" },
  { "ingilizce": "achieve", "turkce": "başarmak", "okunus": "içiv", "seviye": "A2" },
  { "ingilizce": "adult", "turkce": "yetişkin", "okunus": "ıdalt", "seviye": "A2" },
  { "ingilizce": "advantage", "turkce": "avantaj", "okunus": "ıdvantic", "seviye": "A2" },
  { "ingilizce": "adventure", "turkce": "macera", "okunus": "ıdvençır", "seviye": "A2" },
  { "ingilizce": "advise", "turkce": "tavsiye etmek", "okunus": "ıdvayz", "seviye": "A2" },
  { "ingilizce": "air", "turkce": "hava", "okunus": "er", "seviye": "A2" },
  { "ingilizce": "alarm", "turkce": "alarm", "okunus": "ılarm", "seviye": "A2" },
  { "ingilizce": "angel", "turkce": "melek", "okunus": "eyncıl", "seviye": "A2" },
  { "ingilizce": "apartment", "turkce": "apartman dairesi", "okunus": "ıpartmınt", "seviye": "A2" },
  { "ingilizce": "appear", "turkce": "görünmek", "okunus": "ıpiır", "seviye": "A2" },
  { "ingilizce": "architecture", "turkce": "mimari", "okunus": "arkitekçır", "seviye": "A2" },
  { "ingilizce": "area", "turkce": "alan/bölge", "okunus": "eıriı", "seviye": "A2" },
  { "ingilizce": "argue", "turkce": "tartışmak", "okunus": "argyu", "seviye": "A2" },
  { "ingilizce": "attention", "turkce": "dikkat", "okunus": "ıtenşın", "seviye": "A2" },
  { "ingilizce": "attractive", "turkce": "çekici", "okunus": "ıtraktiv", "seviye": "A2" },
  { "ingilizce": "author", "turkce": "yazar", "okunus": "othır", "seviye": "A2" },
  { "ingilizce": "bargain", "turkce": "pazarlık", "okunus": "bargın", "seviye": "A2" },
  { "ingilizce": "battery", "turkce": "pil", "okunus": "betıri", "seviye": "A2" },
  { "ingilizce": "beauty", "turkce": "güzellik", "okunus": "byuti", "seviye": "A2" },
  { "ingilizce": "blood", "turkce": "kan", "okunus": "blad", "seviye": "A2" },
  { "ingilizce": "bored", "turkce": "sıkılmış", "okunus": "bord", "seviye": "A2" },
  { "ingilizce": "brand", "turkce": "marka", "okunus": "brend", "seviye": "A2" },
  { "ingilizce": "bride", "turkce": "gelin", "okunus": "brayd", "seviye": "A2" },
  { "ingilizce": "calendar", "turkce": "takvim", "okunus": "kelındır", "seviye": "A2" },
  { "ingilizce": "capital", "turkce": "başkent", "okunus": "kepitıl", "seviye": "A2" },
  { "ingilizce": "century", "turkce": "yüzyıl", "okunus": "sençıri", "seviye": "A2" },
  { "ingilizce": "chain", "turkce": "zincir", "okunus": "çeyn", "seviye": "A2" },
  { "ingilizce": "challenge", "turkce": "meydan okuma", "okunus": "çelınc", "seviye": "A2" },
  { "ingilizce": "champion", "turkce": "şampiyon", "okunus": "çempiyın", "seviye": "A2" },
  { "ingilizce": "chess", "turkce": "satranç", "okunus": "çes", "seviye": "A2" },
  { "ingilizce": "cigarette", "turkce": "sigara", "okunus": "sigıret", "seviye": "A2" },
  { "ingilizce": "citizen", "turkce": "vatandaş", "okunus": "sitizın", "seviye": "A2" },
  { "ingilizce": "classic", "turkce": "klasik", "okunus": "klesik", "seviye": "A2" },
  { "ingilizce": "clue", "turkce": "ipucu", "okunus": "klu", "seviye": "A2" },
  { "ingilizce": "comfortable", "turkce": "rahat", "okunus": "kamftıbıl", "seviye": "A2" },
  { "ingilizce": "common", "turkce": "ortak/yaygın", "okunus": "kamın", "seviye": "A2" },
  { "ingilizce": "company", "turkce": "şirket", "okunus": "kampıni", "seviye": "A2" },
  { "ingilizce": "compare", "turkce": "karşılaştırmak", "okunus": "kımper", "seviye": "A2" },
  { "ingilizce": "complain", "turkce": "şikayet etmek", "okunus": "kımpleyn", "seviye": "A2" },
  { "ingilizce": "concern", "turkce": "endişe", "okunus": "kınsörn", "seviye": "A2" },
  { "ingilizce": "consider", "turkce": "göz önünde bulundurmak", "okunus": "kınsidır", "seviye": "A2" },
  { "ingilizce": "continue", "turkce": "devam etmek", "okunus": "kıntinyu", "seviye": "A2" },
  { "ingilizce": "control", "turkce": "kontrol etmek", "okunus": "kıntrol", "seviye": "A2" },
  { "ingilizce": "cost", "turkce": "maliyet", "okunus": "kost", "seviye": "A2" },
  { "ingilizce": "count", "turkce": "saymak", "okunus": "kaunt", "seviye": "A2" },
  { "ingilizce": "creative", "turkce": "yaratıcı", "okunus": "krieytiv", "seviye": "A2" },
  { "ingilizce": "crowd", "turkce": "kalabalık", "okunus": "kraud", "seviye": "A2" },
  { "ingilizce": "custom", "turkce": "gelenek", "okunus": "kastım", "seviye": "A2" },
  { "ingilizce": "customer", "turkce": "müşteri", "okunus": "kastımır", "seviye": "A2" },
  { "ingilizce": "danger", "turkce": "tehlike", "okunus": "deyncır", "seviye": "A2" },
  { "ingilizce": "dead", "turkce": "ölü", "okunus": "ded", "seviye": "A2" },
  { "ingilizce": "decide", "turkce": "karar vermek", "okunus": "disayd", "seviye": "A2" },
  { "ingilizce": "depend", "turkce": "bağlı olmak", "okunus": "dipend", "seviye": "A2" },
  { "ingilizce": "desert", "turkce": "çöl", "okunus": "dezırt", "seviye": "A2" },
  { "ingilizce": "detail", "turkce": "detay", "okunus": "diteyl", "seviye": "A2" },
  { "ingilizce": "diamond", "turkce": "elmas", "okunus": "dayımınd", "seviye": "A2" },
  { "ingilizce": "direction", "turkce": "yön", "okunus": "direkşın", "seviye": "A2" },
  { "ingilizce": "discussion", "turkce": "tartışma", "okunus": "diskaşın", "seviye": "A2" },
  { "ingilizce": "absorb", "turkce": "emmek/soğurmak", "okunus": "ıbzorb", "seviye": "B1" },
  { "ingilizce": "academic", "turkce": "akademik", "okunus": "ekıdemik", "seviye": "B1" },
  { "ingilizce": "accompany", "turkce": "eşlik etmek", "okunus": "ıkampıni", "seviye": "B1" },
  { "ingilizce": "accomplish", "turkce": "başarmak", "okunus": "ıkamplış", "seviye": "B1" },
  { "ingilizce": "achievement", "turkce": "başarı", "okunus": "içivmınt", "seviye": "B1" },
  { "ingilizce": "acquire", "turkce": "edinmek", "okunus": "ıkvayır", "seviye": "B1" },
  { "ingilizce": "adapt", "turkce": "uyum sağlamak", "okunus": "ıdept", "seviye": "B1" },
  { "ingilizce": "address", "turkce": "hitap etmek", "okunus": "ıdres", "seviye": "B1" },
  { "ingilizce": "administration", "turkce": "yönetim", "okunus": "ıdministreyşın", "seviye": "B1" },
  { "ingilizce": "adopt", "turkce": "evlat edinmek/benimsemek", "okunus": "ıdapt", "seviye": "B1" },
  { "ingilizce": "advance", "turkce": "ilerlemek", "okunus": "ıdvans", "seviye": "B1" },
  { "ingilizce": "aggressive", "turkce": "saldırgan", "okunus": "ıgresiv", "seviye": "B1" },
  { "ingilizce": "agreement", "turkce": "anlaşma", "okunus": "ıgrimınt", "seviye": "B1" },
  { "ingilizce": "agriculture", "turkce": "tarım", "okunus": "egrikalçır", "seviye": "B1" },
  { "ingilizce": "alternative", "turkce": "alternatif", "okunus": "oltörnıtiv", "seviye": "B1" },
  { "ingilizce": "amount", "turkce": "miktar", "okunus": "ımaunt", "seviye": "B1" },
  { "ingilizce": "analysis", "turkce": "analiz", "okunus": "ınelısis", "seviye": "B1" },
  { "ingilizce": "anger", "turkce": "öfke", "okunus": "engır", "seviye": "B1" },
  { "ingilizce": "announcement", "turkce": "duyuru", "okunus": "ınaunsmınt", "seviye": "B1" },
  { "ingilizce": "annual", "turkce": "yıllık", "okunus": "enyuıl", "seviye": "B1" },
  { "ingilizce": "anxiety", "turkce": "kaygı", "okunus": "engzayıti", "seviye": "B1" },
  { "ingilizce": "apology", "turkce": "özür", "okunus": "ıpalıci", "seviye": "B1" },
  { "ingilizce": "appeal", "turkce": "çekicilik/başvuru", "okunus": "ıpil", "seviye": "B1" },
  { "ingilizce": "applause", "turkce": "alkış", "okunus": "ıploz", "seviye": "B1" },
  { "ingilizce": "application", "turkce": "başvuru", "okunus": "eplikeyşın", "seviye": "B1" },
  { "ingilizce": "approach", "turkce": "yaklaşım", "okunus": "ıproç", "seviye": "B1" },
  { "ingilizce": "approval", "turkce": "onay", "okunus": "ıpruvıl", "seviye": "B1" },
  { "ingilizce": "architect", "turkce": "mimar", "okunus": "arkitekt", "seviye": "B1" },
  { "ingilizce": "arrange", "turkce": "düzenlemek", "okunus": "ıreync", "seviye": "B1" },
  { "ingilizce": "arrangement", "turkce": "düzenleme", "okunus": "ıreyncmınt", "seviye": "B1" },
  { "ingilizce": "assist", "turkce": "yardım etmek", "okunus": "ısist", "seviye": "B1" },
  { "ingilizce": "assistance", "turkce": "yardım", "okunus": "ısistıns", "seviye": "B1" },
  { "ingilizce": "athletic", "turkce": "atletik", "okunus": "etletik", "seviye": "B1" },
  { "ingilizce": "atmosphere", "turkce": "atmosfer", "okunus": "etmısfiır", "seviye": "B1" },
  { "ingilizce": "attach", "turkce": "eklemek", "okunus": "ıteç", "seviye": "B1" },
  { "ingilizce": "attend", "turkce": "katılmak", "okunus": "ıtend", "seviye": "B1" },
  { "ingilizce": "attract", "turkce": "çekmek (ilgi)", "okunus": "ıtrekt", "seviye": "B1" },
  { "ingilizce": "available", "turkce": "müsait", "okunus": "ıveylıbıl", "seviye": "B1" },
  { "ingilizce": "aware", "turkce": "farkında", "okunus": "ıveır", "seviye": "B1" },
  { "ingilizce": "awareness", "turkce": "farkındalık", "okunus": "ıveırnıs", "seviye": "B1" },
  { "ingilizce": "balance", "turkce": "denge", "okunus": "belıns", "seviye": "B1" },
  { "ingilizce": "bare", "turkce": "çıplak", "okunus": "ber", "seviye": "B1" },
  { "ingilizce": "behalf", "turkce": "adına", "okunus": "biheyf", "seviye": "B1" },
  { "ingilizce": "benefit", "turkce": "fayda", "okunus": "benıfit", "seviye": "B1" },
  { "ingilizce": "bitter", "turkce": "acı (tat)", "okunus": "bitır", "seviye": "B1" },
  { "ingilizce": "blend", "turkce": "karıştırmak", "okunus": "blend", "seviye": "B1" },
  { "ingilizce": "bond", "turkce": "bağ", "okunus": "band", "seviye": "B1" },
  { "ingilizce": "brief", "turkce": "kısa", "okunus": "brif", "seviye": "B1" },
  { "ingilizce": "broad", "turkce": "geniş", "okunus": "brod", "seviye": "B1" },
  { "ingilizce": "calculate", "turkce": "hesaplamak", "okunus": "kelkyuleyt", "seviye": "B1" },
  { "ingilizce": "capable", "turkce": "yetenekli", "okunus": "keypıbıl", "seviye": "B1" },
  { "ingilizce": "category", "turkce": "kategori", "okunus": "ketıgori", "seviye": "B1" },
  { "ingilizce": "cave", "turkce": "mağara", "okunus": "keyv", "seviye": "B1" },
  { "ingilizce": "characteristic", "turkce": "özellik", "okunus": "keriktıristik", "seviye": "B1" },
  { "ingilizce": "charge", "turkce": "ücret/şarj etmek", "okunus": "çarc", "seviye": "B1" },
  { "ingilizce": "chief", "turkce": "başlıca/şef", "okunus": "çif", "seviye": "B1" },
  { "ingilizce": "clinic", "turkce": "klinik", "okunus": "klinik", "seviye": "B1" },
  { "ingilizce": "combine", "turkce": "birleştirmek", "okunus": "kımbayn", "seviye": "B1" },
  { "ingilizce": "comment", "turkce": "yorum", "okunus": "kament", "seviye": "B1" },
  { "ingilizce": "commit", "turkce": "taahhüt etmek/işlemek (suç)", "okunus": "kımit", "seviye": "B1" },
  { "ingilizce": "companion", "turkce": "arkadaş/refakatçı", "okunus": "kımpenyın", "seviye": "B1" },
  { "ingilizce": "competitor", "turkce": "rakip", "okunus": "kımpetıtır", "seviye": "B1" },
  { "ingilizce": "complicated", "turkce": "karmaşık", "okunus": "kamplikeytıd", "seviye": "B1" },
  { "ingilizce": "compose", "turkce": "bestelemek/oluşturmak", "okunus": "kımpoz", "seviye": "B1" },
  { "ingilizce": "concept", "turkce": "kavram", "okunus": "kansept", "seviye": "B1" },
  { "ingilizce": "conclude", "turkce": "sonuçlandırmak", "okunus": "kınklud", "seviye": "B1" },
  { "ingilizce": "conclusion", "turkce": "sonuç", "okunus": "kınklujın", "seviye": "B1" },
  { "ingilizce": "confirm", "turkce": "onaylamak", "okunus": "kınförm", "seviye": "B1" },
  { "ingilizce": "conflict", "turkce": "çatışma", "okunus": "kanflikt", "seviye": "B1" },
  { "ingilizce": "connect", "turkce": "bağlamak", "okunus": "kınekt", "seviye": "B1" },
  { "ingilizce": "abandoned", "turkce": "terk edilmiş", "okunus": "ıbendınd", "seviye": "B2" },
  { "ingilizce": "abolish", "turkce": "kaldırmak (yasa vb.)", "okunus": "ıbaliş", "seviye": "B2" },
  { "ingilizce": "abruptly", "turkce": "aniden", "okunus": "ıbraptli", "seviye": "B2" },
  { "ingilizce": "absurd", "turkce": "saçma", "okunus": "ıbsörd", "seviye": "B2" },
  { "ingilizce": "abuse", "turkce": "istismar", "okunus": "ıbyus", "seviye": "B2" },
  { "ingilizce": "accumulate", "turkce": "biriktirmek", "okunus": "ıkyumyuleyt", "seviye": "B2" },
  { "ingilizce": "acquisition", "turkce": "edinim", "okunus": "ekvizişın", "seviye": "B2" },
  { "ingilizce": "acute", "turkce": "keskin/şiddetli", "okunus": "ıkyut", "seviye": "B2" },
  { "ingilizce": "addict", "turkce": "bağımlı (kişi)", "okunus": "edikt", "seviye": "B2" },
  { "ingilizce": "adequate", "turkce": "yeterli", "okunus": "edikvıt", "seviye": "B2" },
  { "ingilizce": "administrative", "turkce": "idari", "okunus": "ıdministrıtiv", "seviye": "B2" },
  { "ingilizce": "admirable", "turkce": "takdire değer", "okunus": "edmırıbıl", "seviye": "B2" },
  { "ingilizce": "adventurous", "turkce": "maceracı", "okunus": "ıdvençırıs", "seviye": "B2" },
  { "ingilizce": "affordable", "turkce": "uygun fiyatlı", "okunus": "ıfordıbıl", "seviye": "B2" },
  { "ingilizce": "aircraft", "turkce": "uçak", "okunus": "eırkraft", "seviye": "B2" },
  { "ingilizce": "alliance", "turkce": "ittifak", "okunus": "ılayıns", "seviye": "B2" },
  { "ingilizce": "altitude", "turkce": "rakım/yükseklik", "okunus": "eltityud", "seviye": "B2" },
  { "ingilizce": "ambiguous", "turkce": "belirsiz/muğlak", "okunus": "embigyuıs", "seviye": "B2" },
  { "ingilizce": "amuse", "turkce": "eğlendirmek", "okunus": "ımyuz", "seviye": "B2" },
  { "ingilizce": "analyst", "turkce": "analist", "okunus": "enılıst", "seviye": "B2" },
  { "ingilizce": "anonymous", "turkce": "anonim", "okunus": "ınanımıs", "seviye": "B2" },
  { "ingilizce": "anticipate", "turkce": "beklemek/öngörmek", "okunus": "entisipeyt", "seviye": "B2" },
  { "ingilizce": "appropriate", "turkce": "uygun", "okunus": "ıproprieyt", "seviye": "B2" },
  { "ingilizce": "arena", "turkce": "arena", "okunus": "ırinı", "seviye": "B2" },
  { "ingilizce": "arrogant", "turkce": "kibirli", "okunus": "erıgınt", "seviye": "B2" },
  { "ingilizce": "assemble", "turkce": "bir araya getirmek", "okunus": "ısembıl", "seviye": "B2" },
  { "ingilizce": "assess", "turkce": "değerlendirmek", "okunus": "ıses", "seviye": "B2" },
  { "ingilizce": "assessment", "turkce": "değerlendirme", "okunus": "ısesmınt", "seviye": "B2" },
  { "ingilizce": "assume", "turkce": "varsaymak", "okunus": "ısyum", "seviye": "B2" },
  { "ingilizce": "assumption", "turkce": "varsayım", "okunus": "ısampşın", "seviye": "B2" },
  { "ingilizce": "astonishing", "turkce": "şaşırtıcı", "okunus": "ıstanişing", "seviye": "B2" },
  { "ingilizce": "attentive", "turkce": "dikkatli", "okunus": "ıtentiv", "seviye": "B2" },
  { "ingilizce": "attribute", "turkce": "özellik/atfetmek", "okunus": "etribyut", "seviye": "B2" },
  { "ingilizce": "authoritative", "turkce": "otoriter", "okunus": "ıtoritıtiv", "seviye": "B2" },
  { "ingilizce": "bankrupt", "turkce": "iflas etmiş", "okunus": "benkrapt", "seviye": "B2" },
  { "ingilizce": "barrier", "turkce": "engel", "okunus": "beriır", "seviye": "B2" },
  { "ingilizce": "betray", "turkce": "ihanet etmek", "okunus": "bitrey", "seviye": "B2" },
  { "ingilizce": "bewildered", "turkce": "şaşkına dönmüş", "okunus": "bivildırd", "seviye": "B2" },
  { "ingilizce": "bizarre", "turkce": "tuhaf/acayip", "okunus": "bizar", "seviye": "B2" },
  { "ingilizce": "blast", "turkce": "patlama", "okunus": "blast", "seviye": "B2" },
  { "ingilizce": "bloom", "turkce": "çiçek açmak", "okunus": "blum", "seviye": "B2" },
  { "ingilizce": "bombard", "turkce": "bombalamak", "okunus": "bambard", "seviye": "B2" },
  { "ingilizce": "boost", "turkce": "artırmak/güçlendirmek", "okunus": "bust", "seviye": "B2" },
  { "ingilizce": "breakdown", "turkce": "bozulma/çöküş", "okunus": "breykdaun", "seviye": "B2" },
  { "ingilizce": "breakthrough", "turkce": "çığır açan gelişme", "okunus": "breyktru", "seviye": "B2" },
  { "ingilizce": "campaign", "turkce": "kampanya", "okunus": "kempeyn", "seviye": "B2" },
  { "ingilizce": "candidate", "turkce": "aday", "okunus": "kendidıt", "seviye": "B2" },
  { "ingilizce": "capability", "turkce": "yetenek/kapasite", "okunus": "keypıbilıti", "seviye": "B2" },
  { "ingilizce": "catastrophe", "turkce": "felaket", "okunus": "kıtestrıfi", "seviye": "B2" },
  { "ingilizce": "cease", "turkce": "durmak/sona ermek", "okunus": "siz", "seviye": "B2" },
  { "ingilizce": "certificate", "turkce": "sertifika", "okunus": "sörtifikıt", "seviye": "B2" },
  { "ingilizce": "chaotic", "turkce": "kaotik", "okunus": "keyatik", "seviye": "B2" },
  { "ingilizce": "clarify", "turkce": "açıklığa kavuşturmak", "okunus": "klerifay", "seviye": "B2" },
  { "ingilizce": "classification", "turkce": "sınıflandırma", "okunus": "klesifikeyşın", "seviye": "B2" },
  { "ingilizce": "coherent", "turkce": "tutarlı", "okunus": "kohirınt", "seviye": "B2" },
  { "ingilizce": "coalition", "turkce": "koalisyon", "okunus": "kovılişın", "seviye": "B2" },
  { "ingilizce": "commemorate", "turkce": "anmak", "okunus": "kımemıreyt", "seviye": "B2" },
  { "ingilizce": "commute", "turkce": "işe gidip gelmek", "okunus": "kımyut", "seviye": "B2" },
  { "ingilizce": "compassion", "turkce": "şefkat", "okunus": "kımpeşın", "seviye": "B2" },
  { "ingilizce": "compatible", "turkce": "uyumlu", "okunus": "kımpetıbıl", "seviye": "B2" },
  { "ingilizce": "compensate", "turkce": "tazmin etmek", "okunus": "kampınseyt", "seviye": "B2" },
  { "ingilizce": "competence", "turkce": "yeterlilik/beceri", "okunus": "kampıtıns", "seviye": "B2" },
  { "ingilizce": "compile", "turkce": "derlemek", "okunus": "kımpayl", "seviye": "B2" },
  { "ingilizce": "comprehensive", "turkce": "kapsamlı", "okunus": "kamprihensiv", "seviye": "B2" },
  { "ingilizce": "concrete", "turkce": "somut/beton", "okunus": "kankrit", "seviye": "B2" },
  { "ingilizce": "condemn", "turkce": "kınamak", "okunus": "kındem", "seviye": "B2" },
  { "ingilizce": "confront", "turkce": "yüzleşmek", "okunus": "kınfrant", "seviye": "B2" },
  { "ingilizce": "consensus", "turkce": "fikir birliği", "okunus": "kınsensıs", "seviye": "B2" },
  { "ingilizce": "considerably", "turkce": "önemli ölçüde", "okunus": "kınsidırıbli", "seviye": "B2" },
  { "ingilizce": "contaminate", "turkce": "kirletmek", "okunus": "kıntemineyt", "seviye": "B2" },
  { "ingilizce": "ubiquitous", "turkce": "her yerde bulunan", "okunus": "yubikvitıs", "seviye": "C1" },
  { "ingilizce": "meticulous", "turkce": "titiz", "okunus": "mitikyulıs", "seviye": "C1" },
  { "ingilizce": "ambivalent", "turkce": "kararsız/çelişkili duygularla", "okunus": "embivılınt", "seviye": "C1" },
  { "ingilizce": "eloquent", "turkce": "etkili konuşan", "okunus": "elıkvınt", "seviye": "C1" },
  { "ingilizce": "pragmatic", "turkce": "pragmatik/gerçekçi", "okunus": "pregmetik", "seviye": "C1" },
  { "ingilizce": "resilient", "turkce": "dirençli", "okunus": "riziliınt", "seviye": "C1" },
  { "ingilizce": "profound", "turkce": "derin (etki/anlam)", "okunus": "prıfaund", "seviye": "C1" },
  { "ingilizce": "inevitable", "turkce": "kaçınılmaz", "okunus": "inevitıbıl", "seviye": "C1" },
  { "ingilizce": "plausible", "turkce": "inandırıcı/makul", "okunus": "plozıbıl", "seviye": "C1" },
  { "ingilizce": "paradox", "turkce": "çelişki/paradoks", "okunus": "perıdaks", "seviye": "C1" },
  { "ingilizce": "discrepancy", "turkce": "tutarsızlık", "okunus": "diskrepınsi", "seviye": "C1" },
  { "ingilizce": "skeptical", "turkce": "şüpheci", "okunus": "skeptikıl", "seviye": "C1" },
  { "ingilizce": "subtle", "turkce": "ince/belli belirsiz", "okunus": "satıl", "seviye": "C1" },
  { "ingilizce": "tedious", "turkce": "yorucu/sıkıcı", "okunus": "tidiıs", "seviye": "C1" },
  { "ingilizce": "viable", "turkce": "uygulanabilir", "okunus": "vayıbıl", "seviye": "C1" },
  { "ingilizce": "rigorous", "turkce": "titiz/sıkı", "okunus": "rigırıs", "seviye": "C1" },
  { "ingilizce": "coherence", "turkce": "tutarlılık", "okunus": "kohirıns", "seviye": "C1" },
  { "ingilizce": "arbitrary", "turkce": "keyfi", "okunus": "arbitreri", "seviye": "C1" },
  { "ingilizce": "inherent", "turkce": "doğuştan/özünde olan", "okunus": "inhirınt", "seviye": "C1" },
  { "ingilizce": "controversial", "turkce": "tartışmalı", "okunus": "kantrıvörşıl", "seviye": "C1" },
  { "ingilizce": "deteriorate", "turkce": "kötüleşmek", "okunus": "ditiriyıreyt", "seviye": "C1" },
  { "ingilizce": "exacerbate", "turkce": "kötüleştirmek", "okunus": "igzesırbeyt", "seviye": "C1" },
  { "ingilizce": "hypothesis", "turkce": "hipotez", "okunus": "haypatısis", "seviye": "C1" },
  { "ingilizce": "implicit", "turkce": "örtük/dolaylı", "okunus": "implisit", "seviye": "C1" },
  { "ingilizce": "explicit", "turkce": "açık/net", "okunus": "iksplisit", "seviye": "C1" },
  { "ingilizce": "jeopardize", "turkce": "tehlikeye atmak", "okunus": "cepırdayz", "seviye": "C1" },
  { "ingilizce": "mitigate", "turkce": "hafifletmek", "okunus": "mitigeyt", "seviye": "C1" },
  { "ingilizce": "notion", "turkce": "kavram/fikir", "okunus": "noşın", "seviye": "C1" },
  { "ingilizce": "obsolete", "turkce": "eskimiş/kullanım dışı", "okunus": "absılit", "seviye": "C1" },
  { "ingilizce": "perceive", "turkce": "algılamak", "okunus": "pırsiv", "seviye": "C1" },
  { "ingilizce": "prevalent", "turkce": "yaygın", "okunus": "prevılınt", "seviye": "C1" },
  { "ingilizce": "reluctant", "turkce": "isteksiz", "okunus": "rilaktınt", "seviye": "C1" },
  { "ingilizce": "scrutiny", "turkce": "didik didik inceleme", "okunus": "skrutıni", "seviye": "C1" },
  { "ingilizce": "substantial", "turkce": "önemli/hatırı sayılır", "okunus": "sıbstenşıl", "seviye": "C1" },
  { "ingilizce": "tangible", "turkce": "somut/elle tutulur", "okunus": "tencıbıl", "seviye": "C1" },
  { "ingilizce": "underlying", "turkce": "altta yatan", "okunus": "andırlayıng", "seviye": "C1" },
  { "ingilizce": "versatile", "turkce": "çok yönlü", "okunus": "vörsıtayl", "seviye": "C1" },
  { "ingilizce": "vigorous", "turkce": "güçlü/dinç", "okunus": "vigırıs", "seviye": "C1" },
  { "ingilizce": "wary", "turkce": "temkinli/çekingen", "okunus": "veri", "seviye": "C1" },
  { "ingilizce": "zealous", "turkce": "hevesli/gayretli", "okunus": "zelıs", "seviye": "C1" }
];
