export const kelimeler=[

  { "ingilizce": "abroad", "turkce": "yurt dışı", "okunus": "ıbrod" },
  { "ingilizce": "academy", "turkce": "akademi", "okunus": "ı kedımi" },
  { "ingilizce": "accommodation", "turkce": "konaklama", "okunus": "ı komı deyşın" },
  { "ingilizce": "album", "turkce": "albüm", "okunus": "el bım" },
  { "ingilizce": "applicable", "turkce": "uygulanabilir", "okunus": "ı pli kıbıl" },
  { "ingilizce": "arrival", "turkce": "varış", "okunus": "ı rayvıl" },
  { "ingilizce": "bar", "turkce": "bar", "okunus": "bar" },
  { "ingilizce": "beard", "turkce": "sakal", "okunus": "bird" },
  { "ingilizce": "blind date", "turkce": "görmeden randevulaşma", "okunus": "blaynd deyt" },
  { "ingilizce": "borrow", "turkce": "ödünç almak", "okunus": "borov" },
  { "ingilizce": "bubbly", "turkce": "hayat dolu/neşeli", "okunus": "babli" },
  { "ingilizce": "busker", "turkce": "sokak çalgıcısı", "okunus": "baskır" },
  { "ingilizce": "camper van", "turkce": "karavan", "okunus": "kempır ven" },
  { "ingilizce": "carpenter", "turkce": "marangoz", "okunus": "karpıntır" },
  { "ingilizce": "chatty", "turkce": "geveze/konuşkan", "okunus": "çeti" },
  { "ingilizce": "cheers", "turkce": "şerefe/teşekkürler", "okunus": "çirs" },
  { "ingilizce": "college", "turkce": "kolej/yüksekokul", "okunus": "kalıc" },
  { "ingilizce": "couple", "turkce": "çift", "okunus": "kapıl" },
  { "ingilizce": "crazy", "turkce": "çılgın", "okunus": "kreyzi" },
  { "ingilizce": "crazy about", "turkce": "bayılmak (bir şeye)", "okunus": "kreyzi ıbaut" },
  { "ingilizce": "daily", "turkce": "günlük", "okunus": "deyli" },
  { "ingilizce": "date", "turkce": "tarih/hurma/randevu", "okunus": "deyt" },
  { "ingilizce": "definitely", "turkce": "kesinlikle", "okunus": "definitli" },
  { "ingilizce": "delete", "turkce": "silmek", "okunus": "dilit" },
  { "ingilizce": "delicious", "turkce": "lezzetli", "okunus": "dilişıs" },
  { "ingilizce": "departure", "turkce": "kalkış", "okunus": "diparçır" },
  { "ingilizce": "dietary", "turkce": "diyetle ilgili", "okunus": "dayıtri" },
  { "ingilizce": "early days", "turkce": "henüz erken", "okunus": "örli deyz" },
  { "ingilizce": "embarrass", "turkce": "utandırmak", "okunus": "imbıres" },
  { "ingilizce": "embarrassing", "turkce": "utanç verici", "okunus": "imbıresing" },
  { "ingilizce": "emergency", "turkce": "acil durum", "okunus": "imörcınsi" },
  { "ingilizce": "empty", "turkce": "boş", "okunus": "empti" },
  { "ingilizce": "excited", "turkce": "heyecanlı", "okunus": "iksaytıd" },
  { "ingilizce": "fabulous", "turkce": "harika/efsanevi", "okunus": "febyılıs" },
  { "ingilizce": "flatmate", "turkce": "ev arkadaşı", "okunus": "fletmeyt" },
  { "ingilizce": "forever", "turkce": "sonsuza dek", "okunus": "for evır" },
  { "ingilizce": "gender", "turkce": "cinsiyet", "okunus": "cendır" },
  { "ingilizce": "global", "turkce": "küresel", "okunus": "globıl" },
  { "ingilizce": "heavy", "turkce": "ağır/yoğun", "okunus": "hevi" },
  { "ingilizce": "hire", "turkce": "kiralamak", "okunus": "hayır" },
  { "ingilizce": "hostel", "turkce": "pansiyon", "okunus": "hostıl" },
  { "ingilizce": "How do you do?", "turkce": "Memnun oldum (resmi)", "okunus": "hav du yu du" },
  { "ingilizce": "I'm afraid", "turkce": "Korkarım ki/Maalesef", "okunus": "aym ıfreyd" },
  { "ingilizce": "improve", "turkce": "geliştirmek", "okunus": "impruv" },
  { "ingilizce": "in common", "turkce": "ortak nokta", "okunus": "in kamın" },
  { "ingilizce": "journalist", "turkce": "gazeteci", "okunus": "cörnılist" },
  { "ingilizce": "jumper", "turkce": "kazak", "okunus": "campır" },
  { "ingilizce": "kind", "turkce": "kibar", "okunus": "kaynd" },
  { "ingilizce": "kiss", "turkce": "öpmek", "okunus": "kis" },
  { "ingilizce": "knock over", "turkce": "devirmek/çarpmak", "okunus": "nak ovır" },
  { "ingilizce": "lend", "turkce": "ödünç vermek", "okunus": "lend" },
  { "ingilizce": "lose touch", "turkce": "iletişimi koparmak", "okunus": "luz taç" },
  { "ingilizce": "marital status", "turkce": "medeni hal", "okunus": "meritıl steytıs" },
  { "ingilizce": "mean", "turkce": "cimri/kaba", "okunus": "min" },
  { "ingilizce": "medical condition", "turkce": "tıbbi durum/rahatsızlık", "okunus": "medikıl kındişın" },
  { "ingilizce": "mess", "turkce": "dağınıklık", "okunus": "mes" },
  { "ingilizce": "miss", "turkce": "özlemek/kaçırmak", "okunus": "mis" },
  { "ingilizce": "mountain", "turkce": "dağ", "okunus": "mauntın" },
  { "ingilizce": "my pleasure", "turkce": "bir şey değil/zevkliydi", "okunus": "may plejır" },
  { "ingilizce": "nest", "turkce": "yuva", "okunus": "nest" },
  { "ingilizce": "never mind", "turkce": "boşver/önemli değil", "okunus": "nevır maynd" },
  { "ingilizce": "nickname", "turkce": "lakap", "okunus": "nikneym" },
  { "ingilizce": "no trouble", "turkce": "sorun değil/zahmet değil", "okunus": "no trabıl" },
  { "ingilizce": "noise", "turkce": "gürültü", "okunus": "noyz" },
  { "ingilizce": "obviously", "turkce": "açıkçası/belli ki", "okunus": "abviısli" },
  { "ingilizce": "occupation", "turkce": "meslek", "okunus": "akyı peyşın" },
  { "ingilizce": "pardon", "turkce": "pardon/efendim?", "okunus": "pardın" },
  { "ingilizce": "permanent", "turkce": "kalıcı", "okunus": "pörmınınt" },
  { "ingilizce": "pick up", "turkce": "toplamak/almak", "okunus": "pik ap" },
  { "ingilizce": "pleasure", "turkce": "zevk/memnuniyet", "okunus": "plejır" },
  { "ingilizce": "postcode", "turkce": "posta kodu", "okunus": "postkod" },
  { "ingilizce": "pretty", "turkce": "güzel/sevimli", "okunus": "priti" },
  { "ingilizce": "pub", "turkce": "pub/bar", "okunus": "pab" },
  { "ingilizce": "relationship", "turkce": "ilişki", "okunus": "ri leyşınşip" },
  { "ingilizce": "reporter", "turkce": "muhabir", "okunus": "ri portır" },
  { "ingilizce": "requirements", "turkce": "gereksinimler", "okunus": "ri kuayırmınts" },
  { "ingilizce": "rescue", "turkce": "kurtarmak", "okunus": "reskyu" },
  { "ingilizce": "retire", "turkce": "emekli olmak", "okunus": "ri tayır" },
  { "ingilizce": "reunited", "turkce": "yeniden birleşmiş", "okunus": "ri yunaytıd" },
  { "ingilizce": "scholarship", "turkce": "burs", "okunus": "skalırşip" },
  { "ingilizce": "seaside", "turkce": "deniz kenarı", "okunus": "sisayd" },
  { "ingilizce": "secondary school", "turkce": "ortaokul", "okunus": "sekındri skul" },
  { "ingilizce": "signature", "turkce": "imza", "okunus": "signıçır" },
  { "ingilizce": "single", "turkce": "bekar", "okunus": "singıl" },
  { "ingilizce": "surname", "turkce": "soyadı", "okunus": "sörneym" },
  { "ingilizce": "surprising", "turkce": "şaşırtıcı", "okunus": "sıprayzing" },
  { "ingilizce": "text", "turkce": "mesaj yazmak", "okunus": "tekst" },
  { "ingilizce": "unusual", "turkce": "olağandışı", "okunus": "an yujıl" },
  { "ingilizce": "veggie (vegetarian)", "turkce": "vejetaryen", "okunus": "veci" },
  { "ingilizce": "wardrobe", "turkce": "gardırop", "okunus": "vordrob" },
  { "ingilizce": "well-paid", "turkce": "iyi maaşlı", "okunus": "vel peyd" },
  { "ingilizce": "wild", "turkce": "vahşi", "okunus": "vayld" },
  { "ingilizce": "wink", "turkce": "göz kırpmak", "okunus": "vink" },
  { "ingilizce": "woolly", "turkce": "yünlü", "okunus": "vuli" },
  { "ingilizce": "worried", "turkce": "endişeli", "okunus": "vörid" },
  { "ingilizce": "a handful", "turkce": "ele avuca sığmaz", "okunus": "ı hendful" },
  { "ingilizce": "absolutely", "turkce": "kesinlikle", "okunus": "ebsılutli" },
  { "ingilizce": "acting", "turkce": "oyunculuk", "okunus": "ekting" },
  { "ingilizce": "art gallery", "turkce": "sanat galerisi", "okunus": "art gelıri" },
  { "ingilizce": "beat", "turkce": "yenmek", "okunus": "bit" },
  { "ingilizce": "believe", "turkce": "inanmak", "okunus": "biliv" },
  { "ingilizce": "brave", "turkce": "cesur", "okunus": "breyv" },
  { "ingilizce": "competitive", "turkce": "rekabetçi", "okunus": "kımpetitiv" },
  { "ingilizce": "confidence", "turkce": "özgüven", "okunus": "kanfidıns" },
  { "ingilizce": "confident", "turkce": "kendinden emin", "okunus": "kanfidınt" },
  { "ingilizce": "countryside", "turkce": "kırsal bölge", "okunus": "kantri sayd" },
  { "ingilizce": "crossword", "turkce": "bulmaca", "okunus": "krosvörd" },
  { "ingilizce": "dependent", "turkce": "bağımlı", "okunus": "dipendınt" },
  { "ingilizce": "despite", "turkce": "-e rağmen", "okunus": "dispayt" },
  { "ingilizce": "disagree", "turkce": "katılmamak", "okunus": "disıgri" },
  { "ingilizce": "divorced", "turkce": "boşanmış", "okunus": "divorst" },
  { "ingilizce": "dress", "turkce": "elbise", "okunus": "dres" },
  { "ingilizce": "dye", "turkce": "boyamak (saç vb.)", "okunus": "day" },
  { "ingilizce": "equally", "turkce": "eşit derecede", "okunus": "ikuıli" },
  { "ingilizce": "experiment", "turkce": "deney yapmak", "okunus": "iksperimınt" },
  { "ingilizce": "explore", "turkce": "keşfetmek", "okunus": "iksplor" },
  { "ingilizce": "express an opinion", "turkce": "fikir beyan etmek", "okunus": "ikspres en ıpin yın" },
  { "ingilizce": "fence", "turkce": "çit", "okunus": "fens" },
  { "ingilizce": "fight", "turkce": "kavga etmek", "okunus": "fayt" },
  { "ingilizce": "forget", "turkce": "unutmak", "okunus": "fırget" },
  { "ingilizce": "grown-up", "turkce": "yetişkin", "okunus": "gron ap" },
  { "ingilizce": "headphones", "turkce": "kulaklık", "okunus": "hedfons" },
  { "ingilizce": "homework", "turkce": "ev ödevi", "okunus": "homvörk" },
  { "ingilizce": "hopeless", "turkce": "umutsuz/beceriksiz", "okunus": "hoplıs" },
  { "ingilizce": "identical", "turkce": "özdeş/tıpatıp aynı", "okunus": "aydentikıl" },
  { "ingilizce": "ill", "turkce": "hasta", "okunus": "il" },
  { "ingilizce": "independent", "turkce": "bağımsız", "okunus": "indipendınt" },
  { "ingilizce": "ingredients", "turkce": "malzemeler", "okunus": "ingridiyınts" },
  { "ingilizce": "invite", "turkce": "davet etmek", "okunus": "invayt" },
  { "ingilizce": "jealous", "turkce": "kıskanç", "okunus": "celıs" },
  { "ingilizce": "keep in touch", "turkce": "iletişimi sürdürmek", "okunus": "kip in taç" },
  { "ingilizce": "lazy", "turkce": "tembel", "okunus": "leyzi" },
  { "ingilizce": "lie-in", "turkce": "geç uyanmak", "okunus": "lay in" },
  { "ingilizce": "magazine", "turkce": "dergi", "okunus": "megı zin" },
  { "ingilizce": "neighbour", "turkce": "komşu", "okunus": "neybır" },
  { "ingilizce": "notice", "turkce": "fark etmek", "okunus": "notis" },
  { "ingilizce": "pay no attention", "turkce": "aldırış etmemek", "okunus": "pey no ıtenşın" },
  { "ingilizce": "personality", "turkce": "kişilik", "okunus": "pörsınalıti" },
  { "ingilizce": "play", "turkce": "oyun (tiyatro)", "okunus": "pley" },
  { "ingilizce": "polite", "turkce": "kibar", "okunus": "pılayt" },
  { "ingilizce": "postman", "turkce": "postacı", "okunus": "postmın" },
  { "ingilizce": "practice", "turkce": "pratik", "okunus": "prektis" },
  { "ingilizce": "puzzle", "turkce": "yapboz/bulmaca", "okunus": "pazıl" },
  { "ingilizce": "quiz", "turkce": "kısa sınav", "okunus": "kuiz" },
  { "ingilizce": "recipe", "turkce": "tarif", "okunus": "resıpi" },
  { "ingilizce": "rich", "turkce": "zengin", "okunus": "riç" },
  { "ingilizce": "saxophone", "turkce": "saksafon", "okunus": "seksıfon" },
  { "ingilizce": "scary", "turkce": "korkutucu", "okunus": "skeri" },
  { "ingilizce": "score", "turkce": "skor/puan", "okunus": "skor" },
  { "ingilizce": "shy", "turkce": "utangaç", "okunus": "şay" },
  { "ingilizce": "smart", "turkce": "akıllı/şık", "okunus": "smart" },
  { "ingilizce": "solitary", "turkce": "yalnız", "okunus": "salıteri" },
  { "ingilizce": "solve", "turkce": "çözmek", "okunus": "salv" },
  { "ingilizce": "suit", "turkce": "yakışmak", "okunus": "sut" },
  { "ingilizce": "suspicious", "turkce": "şüpheli/kuşkulu", "okunus": "sıspişıs" },
  { "ingilizce": "takeaway", "turkce": "paket servis", "okunus": "teykıvey" },
  { "ingilizce": "tattoo", "turkce": "dövme", "okunus": "tetu" },
  { "ingilizce": "twins", "turkce": "ikizler", "okunus": "tvins" },
  { "ingilizce": "usually", "turkce": "genellikle", "okunus": "yujıli" },
  { "ingilizce": "village", "turkce": "köy", "okunus": "vilic" },
  { "ingilizce": "accident", "turkce": "kaza", "okunus": "eksidınt" },
  { "ingilizce": "afford", "turkce": "maddi gücü yetmek", "okunus": "ıford" },
  { "ingilizce": "air conditioning", "turkce": "klima", "okunus": "er kındişning" },
  { "ingilizce": "angry", "turkce": "kızgın", "okunus": "engri" },
  { "ingilizce": "appointment", "turkce": "randevu", "okunus": "ıpointmınt" },
  { "ingilizce": "assassin", "turkce": "suikastçı", "okunus": "ısesin" },
  { "ingilizce": "bang", "turkce": "çarpmak/gümlemek", "okunus": "beng" },
  { "ingilizce": "boss", "turkce": "patron", "okunus": "bos" },
  { "ingilizce": "breathe", "turkce": "nefes almak", "okunus": "brid" },
  { "ingilizce": "bricklayer", "turkce": "duvar ustası", "okunus": "brikleyır" },
  { "ingilizce": "bullet", "turkce": "kurşun/mermi", "okunus": "bulit" },
  { "ingilizce": "capture", "turkce": "yakalamak", "okunus": "kepçır" },
  { "ingilizce": "cardboard box", "turkce": "karton kutu", "okunus": "kardbord boks" },
  { "ingilizce": "checkout", "turkce": "kasa (market)", "okunus": "çekaut" },
  { "ingilizce": "club together", "turkce": "para birleştirmek", "okunus": "klab tıgedır" },
  { "ingilizce": "coast", "turkce": "sahil", "okunus": "kost" },
  { "ingilizce": "continually", "turkce": "sürekli", "okunus": "kıntinyuıli" },
  { "ingilizce": "covered", "turkce": "kaplı/örtülü", "okunus": "kavırd" },
  { "ingilizce": "creep", "turkce": "sinsice yaklaşmak/sürünmek", "okunus": "krip" },
  { "ingilizce": "curse", "turkce": "lanetlemek/küfretmek", "okunus": "körs" },
  { "ingilizce": "curtain", "turkce": "perde", "okunus": "körtın" },
  { "ingilizce": "cut", "turkce": "kesmek", "okunus": "kat" },
  { "ingilizce": "darkness", "turkce": "karanlık", "okunus": "darknıs" },
  { "ingilizce": "description", "turkce": "tanımlama", "okunus": "diskripşın" },
  { "ingilizce": "die", "turkce": "ölmek", "okunus": "day" },
  { "ingilizce": "disappear", "turkce": "kaybolmak", "okunus": "disıpir" },
  { "ingilizce": "enjoy", "turkce": "tadını çıkarmak", "okunus": "incoy" },
  { "ingilizce": "escape", "turkce": "kaçmak", "okunus": "iskeyp" },
  { "ingilizce": "exactly", "turkce": "tam olarak", "okunus": "igzektli" },
  { "ingilizce": "excellent", "turkce": "mükemmel", "okunus": "eksılınt" },
  { "ingilizce": "expiry date", "turkce": "son kullanma tarihi", "okunus": "ikspayri deyt" },
  { "ingilizce": "feathers", "turkce": "tüyler", "okunus": "fedırz" },
  { "ingilizce": "feed", "turkce": "beslemek", "okunus": "fid" },
  { "ingilizce": "finishing line", "turkce": "bitiş çizgisi", "okunus": "finişing layn" },
  { "ingilizce": "fluently", "turkce": "akıcı bir şekilde", "okunus": "fluıntli" },
  { "ingilizce": "furious", "turkce": "öfkeli", "okunus": "fyuriyıs" },
  { "ingilizce": "generously", "turkce": "cömertçe", "okunus": "cenırısli" },
  { "ingilizce": "gradually", "turkce": "yavaş yavaş", "okunus": "grecuıli" },
  { "ingilizce": "guess", "turkce": "tahmin etmek", "okunus": "ges" },
  { "ingilizce": "guiltily", "turkce": "suçlu bir şekilde", "okunus": "giltili" },
  { "ingilizce": "gun", "turkce": "silah", "okunus": "gan" },
  { "ingilizce": "gunshot", "turkce": "silah sesi", "okunus": "ganşat" },
  { "ingilizce": "happily", "turkce": "mutlulukla", "okunus": "hepili" },
  { "ingilizce": "headfirst", "turkce": "kafa üstü", "okunus": "hedförst" },
  { "ingilizce": "headline", "turkce": "manşet", "okunus": "hedlayn" },
  { "ingilizce": "honk", "turkce": "korna çalmak", "okunus": "hank" },
  { "ingilizce": "injured", "turkce": "yaralı", "okunus": "incırd" },
  { "ingilizce": "invitation", "turkce": "davetiye", "okunus": "invıteyşın" },
  { "ingilizce": "luxurious", "turkce": "lüks", "okunus": "lag juriyıs" },
  { "ingilizce": "midnight", "turkce": "gece yarısı", "okunus": "midnayt" },
  { "ingilizce": "motorway", "turkce": "otoyol", "okunus": "motırvey" },
  { "ingilizce": "oil", "turkce": "yağ/petrol", "okunus": "oyl" },
  { "ingilizce": "painter", "turkce": "ressam/boyacı", "okunus": "peyntır" },
  { "ingilizce": "passionately", "turkce": "tutkuyla", "okunus": "peşınıtli" },
  { "ingilizce": "payday", "turkce": "maaş günü", "okunus": "peydey" },
  { "ingilizce": "peacefully", "turkce": "huzurla", "okunus": "pisfıli" },
  { "ingilizce": "penguin", "turkce": "penguen", "okunus": "pengvin" },
  { "ingilizce": "pillow", "turkce": "yastık", "okunus": "pilov" },
  { "ingilizce": "poem", "turkce": "şiir", "okunus": "poim" },
  { "ingilizce": "portrait", "turkce": "portre", "okunus": "portreyt" },
  { "ingilizce": "refuse", "turkce": "reddetmek", "okunus": "rifyuz" },
  { "ingilizce": "robber", "turkce": "soyguncu", "okunus": "rabır" },
  { "ingilizce": "sardine", "turkce": "sardalya", "okunus": "sardin" },
  { "ingilizce": "seashore", "turkce": "deniz kıyısı", "okunus": "sişor" },
  { "ingilizce": "secret agent", "turkce": "gizli ajan", "okunus": "sikrıt eycınt" },
  { "ingilizce": "sick", "turkce": "hasta", "okunus": "sik" },
  { "ingilizce": "spot", "turkce": "fark etmek/görmek", "okunus": "spat" },
  { "ingilizce": "spy", "turkce": "casus", "okunus": "spay" },
  { "ingilizce": "staff", "turkce": "personel", "okunus": "staf" },
  { "ingilizce": "stall", "turkce": "tezgah/stand", "okunus": "stol" },
  { "ingilizce": "strong", "turkce": "güçlü", "okunus": "strong" },
  { "ingilizce": "studio", "turkce": "stüdyo", "okunus": "stüdyov" },
  { "ingilizce": "tail", "turkce": "kuyruk", "okunus": "teyl" },
  { "ingilizce": "tear", "turkce": "gözyaşı", "okunus": "tir" },
  { "ingilizce": "thump", "turkce": "güm güm vurmak", "okunus": "tamp" },
  { "ingilizce": "tiny", "turkce": "küçücük", "okunus": "tayni" },
  { "ingilizce": "triathlon", "turkce": "triatlon", "okunus": "trayetlon" },
  { "ingilizce": "urgently", "turkce": "acilen", "okunus": "örcıntli" },
  { "ingilizce": "vase", "turkce": "vazo", "okunus": "vaz" },
  { "ingilizce": "wallet", "turkce": "cüzdan", "okunus": "valit" },
  { "ingilizce": "whisper", "turkce": "fısıldamak", "okunus": "vispır" },
  { "ingilizce": "alcohol", "turkce": "alkol", "okunus": "elkıhol" },
  { "ingilizce": "attraction", "turkce": "cazibe/turistik yer", "okunus": "ıtrekşın" },
  { "ingilizce": "bake", "turkce": "fırında pişirmek", "okunus": "beyk" },
  { "ingilizce": "baking", "turkce": "pişirme", "okunus": "beyking" },
  { "ingilizce": "bitterly", "turkce": "acı bir şekilde", "okunus": "bitırli" },
  { "ingilizce": "bunch", "turkce": "salkım/demet", "okunus": "banç" },
  { "ingilizce": "can", "turkce": "konserve kutusu", "okunus": "ken" },
  { "ingilizce": "caramel", "turkce": "karamel", "okunus": "kerımel" },
  { "ingilizce": "chef", "turkce": "şef", "okunus": "şef" },
  { "ingilizce": "chewing gum", "turkce": "sakız", "okunus": "çuing gam" },
  { "ingilizce": "chillies", "turkce": "acı biberler", "okunus": "çiliz" },
  { "ingilizce": "complaint", "turkce": "şikayet", "okunus": "kımpleynt" },
  { "ingilizce": "contented", "turkce": "hoşnut/memnun", "okunus": "kıntentıd" },
  { "ingilizce": "cookies", "turkce": "kurabiyeler", "okunus": "kukiz" },
  { "ingilizce": "crisps", "turkce": "cips", "okunus": "krisps" },
  { "ingilizce": "curry", "turkce": "köri/körili yemek", "okunus": "kari" },
  { "ingilizce": "decaf", "turkce": "kafeinsiz", "okunus": "dikef" },
  { "ingilizce": "delicatessen", "turkce": "şarküteri", "okunus": "delikıtesın" },
  { "ingilizce": "discover", "turkce": "keşfetmek", "okunus": "diskavır" },
  { "ingilizce": "dough", "turkce": "hamur", "okunus": "do" },
  { "ingilizce": "engineer", "turkce": "mühendis", "okunus": "encinir" },
  { "ingilizce": "flavour", "turkce": "aroma/tat", "okunus": "fleyvır" },
  { "ingilizce": "fork", "turkce": "çatal", "okunus": "fork" },
  { "ingilizce": "french fries", "turkce": "patates kızartması", "okunus": "frenç frayz" },
  { "ingilizce": "fridge", "turkce": "buzdolabı", "okunus": "fric" },
  { "ingilizce": "fry", "turkce": "kızartmak", "okunus": "fray" },
  { "ingilizce": "fussy", "turkce": "titiz/zor beğenen", "okunus": "fasi" },
  { "ingilizce": "glasses", "turkce": "gözlük", "okunus": "glasız" },
  { "ingilizce": "guest", "turkce": "misafir", "okunus": "gest" },
  { "ingilizce": "hike", "turkce": "doğa yürüyüşü yapmak", "okunus": "hayk" },
  { "ingilizce": "ice lolly", "turkce": "meyveli buz", "okunus": "ays lali" },
  { "ingilizce": "ID", "turkce": "kimlik", "okunus": "ay di" },
  { "ingilizce": "increase", "turkce": "artış/artmak", "okunus": "inkris" },
  { "ingilizce": "industrial", "turkce": "endüstriyel", "okunus": "indastriyıl" },
  { "ingilizce": "invent", "turkce": "icat etmek", "okunus": "invent" },
  { "ingilizce": "lick", "turkce": "yalamak", "okunus": "lik" },
  { "ingilizce": "lift", "turkce": "asansör", "okunus": "lift" },
  { "ingilizce": "loaf", "turkce": "somun (ekmek)", "okunus": "lof" },
  { "ingilizce": "lose", "turkce": "kaybetmek", "okunus": "luz" },
  { "ingilizce": "match", "turkce": "kibrit", "okunus": "meç" },
  { "ingilizce": "melt", "turkce": "erimek", "okunus": "melt" },
  { "ingilizce": "newsagent's", "turkce": "gazete bayii", "okunus": "nyuz eycınts" },
  { "ingilizce": "off-licence", "turkce": "tekel bayii", "okunus": "of laysıns" },
  { "ingilizce": "olive", "turkce": "zeytin", "okunus": "aliv" },
  { "ingilizce": "omelette", "turkce": "omlet", "okunus": "amlit" },
  { "ingilizce": "original", "turkce": "orijinal", "okunus": "ıricinıl" },
  { "ingilizce": "out of this world", "turkce": "harika/muhteşem", "okunus": "aut of dis vörld" },
  { "ingilizce": "packet", "turkce": "paket", "okunus": "pekit" },
  { "ingilizce": "patent", "turkce": "patent", "okunus": "peytınt" },
  { "ingilizce": "petrol", "turkce": "benzin", "okunus": "petrıl" },
  { "ingilizce": "popular", "turkce": "popüler", "okunus": "papyulır" },
  { "ingilizce": "porch", "turkce": "veranda", "okunus": "porç" },
  { "ingilizce": "postcard", "turkce": "kartpostal", "okunus": "postkard" },
  { "ingilizce": "powder", "turkce": "toz", "okunus": "paudır" },
  { "ingilizce": "publish", "turkce": "yayımlamak", "okunus": "pabliş" },
  { "ingilizce": "receive", "turkce": "almak/teslim almak", "okunus": "risiv" },
  { "ingilizce": "roast chicken", "turkce": "fırında tavuk", "okunus": "rost çikin" },
  { "ingilizce": "secret", "turkce": "sır", "okunus": "sikrıt" },
  { "ingilizce": "shopkeeper", "turkce": "dükkan sahibi", "okunus": "şapkipır" },
  { "ingilizce": "slice", "turkce": "dilim", "okunus": "slays" },
  { "ingilizce": "sparkling", "turkce": "gazlı (içecek)", "okunus": "sparkling" },
  { "ingilizce": "spectacular", "turkce": "görkemli", "okunus": "spektekyulır" },
  { "ingilizce": "spicy", "turkce": "baharatlı", "okunus": "spaysi" },
  { "ingilizce": "spinach", "turkce": "ıspanak", "okunus": "spiniç" },
  { "ingilizce": "spoon", "turkce": "kaşık", "okunus": "spun" },
  { "ingilizce": "spoonful", "turkce": "kaşık dolusu", "okunus": "spunful" },
  { "ingilizce": "sprouts", "turkce": "Brüksel lahanası", "okunus": "sprauts" },
  { "ingilizce": "strange", "turkce": "tuhaf", "okunus": "streync" },
  { "ingilizce": "successful", "turkce": "başarılı", "okunus": "sıksesfıl" },
  { "ingilizce": "supply", "turkce": "tedarik/kaynak", "okunus": "sıplay" },
  { "ingilizce": "taste", "turkce": "tatmak", "okunus": "teyst" },
  { "ingilizce": "taste buds", "turkce": "tat tomurcukları", "okunus": "teyst badz" },
  { "ingilizce": "thin", "turkce": "ince", "okunus": "tin" },
  { "ingilizce": "tissues", "turkce": "kağıt mendil", "okunus": "tişuz" },
  { "ingilizce": "tongue", "turkce": "dil", "okunus": "tang" },
  { "ingilizce": "tuna", "turkce": "ton balığı", "okunus": "tuna" },
  { "ingilizce": "unexpected", "turkce": "beklenmedik", "okunus": "anikspektıd" },
  { "ingilizce": "wax paper", "turkce": "yağlı kağıt", "okunus": "veks peypır" },
  { "ingilizce": "whisky", "turkce": "viski", "okunus": "viski" },
  { "ingilizce": "advertising", "turkce": "reklamcılık", "okunus": "edvırtayzing" },
  { "ingilizce": "ambition", "turkce": "hırs", "okunus": "embişın" },
  { "ingilizce": "apply", "turkce": "başvurmak", "okunus": "ıplay" },
  { "ingilizce": "arrest", "turkce": "tutuklamak", "okunus": "ırest" },
  { "ingilizce": "as usual", "turkce": "her zamanki gibi", "okunus": "ez yujıl" },
  { "ingilizce": "attack", "turkce": "saldırı", "okunus": "ıtek" },
  { "ingilizce": "average", "turkce": "ortalama", "okunus": "evıric" },
  { "ingilizce": "award", "turkce": "ödül", "okunus": "ıvord" },
  { "ingilizce": "ballet", "turkce": "bale", "okunus": "bele" },
  { "ingilizce": "break", "turkce": "mola/kırmak", "okunus": "breyk" },
  { "ingilizce": "brilliant", "turkce": "parlak/zeki", "okunus": "brilyınt" },
  { "ingilizce": "bully", "turkce": "zorbalık etmek", "okunus": "buli" },
  { "ingilizce": "career", "turkce": "kariyer", "okunus": "kırir" },
  { "ingilizce": "carry out", "turkce": "gerçekleştirmek", "okunus": "keri aut" },
  { "ingilizce": "catch up", "turkce": "yakalamak/telafi etmek", "okunus": "keç ap" },
  { "ingilizce": "competition", "turkce": "yarışma", "okunus": "kampıtişın" },
  { "ingilizce": "course", "turkce": "kurs/ders", "okunus": "kors" },
  { "ingilizce": "court", "turkce": "mahkeme/kort", "okunus": "kort" },
  { "ingilizce": "crash", "turkce": "çarpmak", "okunus": "kreş" },
  { "ingilizce": "create", "turkce": "yaratmak", "okunus": "kri eyt" },
  { "ingilizce": "cyber criminal", "turkce": "siber suçlu", "okunus": "saybır krimınıl" },
  { "ingilizce": "debts", "turkce": "borçlar", "okunus": "dets" },
  { "ingilizce": "definite", "turkce": "kesin", "okunus": "definit" },
  { "ingilizce": "develop", "turkce": "geliştirmek", "okunus": "divelıp" },
  { "ingilizce": "disappointed", "turkce": "hayal kırıklığına uğramış", "okunus": "disıpoyntıd" },
  { "ingilizce": "doubt", "turkce": "şüphe etmek", "okunus": "daut" },
  { "ingilizce": "earn", "turkce": "para kazanmak", "okunus": "örn" },
  { "ingilizce": "exam", "turkce": "sınav", "okunus": "igzem" },
  { "ingilizce": "fall out", "turkce": "küsüşmek/ayrılmak", "okunus": "fol aut" },
  { "ingilizce": "fashion", "turkce": "moda", "okunus": "feşın" },
  { "ingilizce": "favourite", "turkce": "favori", "okunus": "feyvırit" },
  { "ingilizce": "fed up", "turkce": "bıkmış", "okunus": "fed ap" },
  { "ingilizce": "get on (well) with", "turkce": "iyi geçinmek", "okunus": "get on vel vid" },
  { "ingilizce": "give up", "turkce": "pes etmek/bırakmak", "okunus": "giv ap" },
  { "ingilizce": "grandparents", "turkce": "büyükanne ve büyükbaba", "okunus": "grendperınts" },
  { "ingilizce": "grow up", "turkce": "büyümek", "okunus": "grov ap" },
  { "ingilizce": "hacker", "turkce": "bilgisayar korsanı", "okunus": "hekır" },
  { "ingilizce": "homesick", "turkce": "ev özlemi çeken", "okunus": "homsik" },
  { "ingilizce": "idiomatic", "turkce": "deyimsel", "okunus": "idiyı metik" },
  { "ingilizce": "landscape design", "turkce": "peyzaj tasarımı", "okunus": "lend skeyp dizayn" },
  { "ingilizce": "leap", "turkce": "sıçramak", "okunus": "lip" },
  { "ingilizce": "literal", "turkce": "kelimesi kelimesine", "okunus": "litırıl" },
  { "ingilizce": "look after", "turkce": "göz kulak olmak", "okunus": "luk aftır" },
  { "ingilizce": "look forward to", "turkce": "dört gözle beklemek", "okunus": "luk forvırd tu" },
  { "ingilizce": "look up", "turkce": "sözlükten bakmak/yukarı bakmak", "okunus": "luk ap" },
  { "ingilizce": "miserable", "turkce": "sefil/mutsuz", "okunus": "mizrıbıl" },
  { "ingilizce": "notorious", "turkce": "kötü şöhretli", "okunus": "notoriyıs" },
  { "ingilizce": "owe", "turkce": "borçlu olmak", "okunus": "ov" },
  { "ingilizce": "paramedic", "turkce": "sağlık görevlisi", "okunus": "perımedik" },
  { "ingilizce": "pay back", "turkce": "geri ödemek", "okunus": "pey bek" },
  { "ingilizce": "principal", "turkce": "baş/asıl", "okunus": "prinsıpıl" },
  { "ingilizce": "prison", "turkce": "hapishane", "okunus": "prizın" },
  { "ingilizce": "program", "turkce": "program", "okunus": "progrım" },
  { "ingilizce": "run out of", "turkce": "tükenmek/bitmek", "okunus": "ran aut of" },
  { "ingilizce": "slum", "turkce": "gecekondu mahallesi", "okunus": "slam" },
  { "ingilizce": "soul", "turkce": "ruh", "okunus": "sol" },
  { "ingilizce": "stressful", "turkce": "stresli", "okunus": "stresfıl" },
  { "ingilizce": "suitable", "turkce": "uygun", "okunus": "sutıbıl" },
  { "ingilizce": "take off", "turkce": "çıkarmak (kıyafet)/havalanmak", "okunus": "teyk of" },
  { "ingilizce": "take up", "turkce": "başlamak (hobi vb.)", "okunus": "teyk ap" },
  { "ingilizce": "talent", "turkce": "yetenek", "okunus": "telınt" },
  { "ingilizce": "throw away", "turkce": "atmak", "okunus": "tro ıvey" },
  { "ingilizce": "traffic jam", "turkce": "trafik sıkışıklığı", "okunus": "trefik cem" },
  { "ingilizce": "try on", "turkce": "denemek (kıyafet)", "okunus": "tray on" },
  { "ingilizce": "turn off", "turkce": "kapatmak", "okunus": "törn of" },
  { "ingilizce": "turn round", "turkce": "arkasını dönmek", "okunus": "törn raund" },
  { "ingilizce": "username", "turkce": "kullanıcı adı", "okunus": "yuzırneym" },
  { "ingilizce": "virus", "turkce": "virüs", "okunus": "vayrıs" },
  { "ingilizce": "ability", "turkce": "yetenek", "okunus": "ıbilıti" },
  { "ingilizce": "accountant", "turkce": "muhasebeci", "okunus": "ıkauntınt" },
  { "ingilizce": "actor", "turkce": "aktör", "okunus": "ektır" },
  { "ingilizce": "adviser", "turkce": "danışman", "okunus": "edvayzır" },
  { "ingilizce": "afraid", "turkce": "korkmuş", "okunus": "ıfreyd" },
  { "ingilizce": "amazing", "turkce": "harika/şaşırtıcı", "okunus": "ı meyzing" },
  { "ingilizce": "ancestor", "turkce": "ata", "okunus": "ensestır" },
  { "ingilizce": "ancient", "turkce": "antik", "okunus": "eynşınt" },
  { "ingilizce": "announce", "turkce": "duyurmak", "okunus": "ınauns" },
  { "ingilizce": "aqueduct", "turkce": "su kemeri", "okunus": "ekvidakt" },
  { "ingilizce": "archaeology", "turkce": "arkeoloji", "okunus": "arki alıci" },
  { "ingilizce": "argument", "turkce": "tartışma", "okunus": "argyumınt" },
  { "ingilizce": "armies", "turkce": "ordular", "okunus": "armiz" },
  { "ingilizce": "artist", "turkce": "sanatçı", "okunus": "artıst" },
  { "ingilizce": "assistant", "turkce": "asistan", "okunus": "ı sistınt" },
  { "ingilizce": "avoid", "turkce": "kaçınmak", "okunus": "ıvoyd" },
  { "ingilizce": "biography", "turkce": "biyografi", "okunus": "bayagrafi" },
  { "ingilizce": "catch", "turkce": "yakalamak", "okunus": "keç" },
  { "ingilizce": "celebrity", "turkce": "ünlü kişi", "okunus": "selebriti" },
  { "ingilizce": "charity", "turkce": "hayır kurumu", "okunus": "çerıti" },
  { "ingilizce": "cleaner", "turkce": "temizlikçi", "okunus": "klinır" },
  { "ingilizce": "coin", "turkce": "madeni para", "okunus": "koyn" },
  { "ingilizce": "contact", "turkce": "temas/iletişim", "okunus": "kantakt" },
  { "ingilizce": "currency", "turkce": "para birimi", "okunus": "kırınsi" },
  { "ingilizce": "date", "turkce": "flört etmek/tarih", "okunus": "deyt" },
  { "ingilizce": "death", "turkce": "ölüm", "okunus": "det" },
  { "ingilizce": "destroy", "turkce": "yok etmek", "okunus": "distroy" },
  { "ingilizce": "discovery", "turkce": "keşif", "okunus": "diskavri" },
  { "ingilizce": "distant", "turkce": "uzak", "okunus": "distınt" },
  { "ingilizce": "dressmaker", "turkce": "terzi", "okunus": "dresmeykır" },
  { "ingilizce": "economist", "turkce": "ekonomist", "okunus": "ikanı mist" },
  { "ingilizce": "electrician", "turkce": "elektrikçi", "okunus": "ilek trişın" },
  { "ingilizce": "empire", "turkce": "imparatorluk", "okunus": "empayır" },
  { "ingilizce": "environment", "turkce": "çevre", "okunus": "invayrınmınt" },
  { "ingilizce": "execute", "turkce": "idam etmek/yürütmek", "okunus": "ekzekyut" },
  { "ingilizce": "exhibition", "turkce": "sergi", "okunus": "eksi bişın" },
  { "ingilizce": "expense", "turkce": "masraf", "okunus": "ikspens" },
  { "ingilizce": "fame", "turkce": "şöhret", "okunus": "feym" },
  { "ingilizce": "footsteps", "turkce": "ayak izleri", "okunus": "futsteps" },
  { "ingilizce": "foreign", "turkce": "yabancı", "okunus": "forın" },
  { "ingilizce": "glove", "turkce": "eldiven", "okunus": "glav" },
  { "ingilizce": "government", "turkce": "hükümet", "okunus": "gavırn mınt" },
  { "ingilizce": "homeless", "turkce": "evsiz", "okunus": "homlıs" },
  { "ingilizce": "interpreter", "turkce": "tercüman", "okunus": "intörpritır" },
  { "ingilizce": "invade", "turkce": "istila etmek", "okunus": "inveyd" },
  { "ingilizce": "inventor", "turkce": "mucit", "okunus": "inventır" },
  { "ingilizce": "join", "turkce": "katılmak", "okunus": "coyn" },
  { "ingilizce": "kitten", "turkce": "kedi yavrusu", "okunus": "kitın" },
  { "ingilizce": "landmines", "turkce": "mayınlar", "okunus": "lendmaynz" },
  { "ingilizce": "leprosy", "turkce": "cüzzam", "okunus": "leprısi" },
  { "ingilizce": "lifetime", "turkce": "ömür boyu", "okunus": "layftaym" },
  { "ingilizce": "minced meat", "turkce": "kıyma", "okunus": "minst mit" },
  { "ingilizce": "minefield", "turkce": "mayın tarlası", "okunus": "mayn fild" },
  { "ingilizce": "musician", "turkce": "müzisyen", "okunus": "myuzi şın" },
  { "ingilizce": "ordinary", "turkce": "sıradan", "okunus": "ordınri" },
  { "ingilizce": "orphan", "turkce": "yetim", "okunus": "orfın" },
  { "ingilizce": "passion", "turkce": "tutku", "okunus": "peşın" },
  { "ingilizce": "patron", "turkce": "hami/destekçi", "okunus": "peyt rın" },
  { "ingilizce": "pharaoh", "turkce": "firavun", "okunus": "ferov" },
  { "ingilizce": "politician", "turkce": "politikacı", "okunus": "palı tişın" },
  { "ingilizce": "professor", "turkce": "profesör", "okunus": "prı fesır" },
  { "ingilizce": "protester", "turkce": "protestocu", "okunus": "prıtestır" },
  { "ingilizce": "public", "turkce": "halka açık/kamu", "okunus": "pablik" },
  { "ingilizce": "recently", "turkce": "son zamanlarda", "okunus": "risıntli" },
  { "ingilizce": "refugees", "turkce": "mülteciler", "okunus": "refyuciz" },
  { "ingilizce": "regularly", "turkce": "düzenli olarak", "okunus": "regyulırli" },
  { "ingilizce": "reminder", "turkce": "hatırlatıcı", "okunus": "ri mayndır" },
  { "ingilizce": "research", "turkce": "araştırma", "okunus": "ri sörç" },
  { "ingilizce": "reservation", "turkce": "rezervasyon", "okunus": "rezır veyşın" },
  { "ingilizce": "set up", "turkce": "kurmak", "okunus": "set ap" },
  { "ingilizce": "sewage", "turkce": "kanalizasyon", "okunus": "suic" },
  { "ingilizce": "shelter", "turkce": "barınak", "okunus": "şeltır" },
  { "ingilizce": "shipyard", "turkce": "tersane", "okunus": "şip yard" },
  { "ingilizce": "soldier", "turkce": "asker", "okunus": "solcır" },
  { "ingilizce": "solo artist", "turkce": "solo sanatçı", "okunus": "solo artıst" },
  { "ingilizce": "straight", "turkce": "düz", "okunus": "streyt" },
  { "ingilizce": "taxes", "turkce": "vergiler", "okunus": "teksiz" },
  { "ingilizce": "tent", "turkce": "çadır", "okunus": "tent" },
  { "ingilizce": "tomb", "turkce": "mezar", "okunus": "tum" },
  { "ingilizce": "underpants", "turkce": "külot/iç çamaşırı", "okunus": "andırpents" },
  { "ingilizce": "victim", "turkce": "kurban", "okunus": "viktim" },
  { "ingilizce": "wide", "turkce": "geniş", "okunus": "vayd" },
  { "ingilizce": "wildlife", "turkce": "vahşi yaşam", "okunus": "vayld layf" },
  { "ingilizce": "adore", "turkce": "tapmak/çok sevmek", "okunus": "ıdor" },
  { "ingilizce": "bridge", "turkce": "köprü", "okunus": "bric" },
  { "ingilizce": "bright", "turkce": "parlak", "okunus": "brayt" },
  { "ingilizce": "building", "turkce": "bina", "okunus": "bildiŋ" },
  { "ingilizce": "calm", "turkce": "sakin", "okunus": "kam" },
  { "ingilizce": "capture", "turkce": "yakalamak", "okunus": "kepçır" },
  { "ingilizce": "collection", "turkce": "koleksiyon", "okunus": "kılekşın" },
  { "ingilizce": "composer", "turkce": "besteci", "okunus": "kımpozır" },
  { "ingilizce": "concert", "turkce": "konser", "okunus": "kansirt" },
  { "ingilizce": "concert hall", "turkce": "konser salonu", "okunus": "kansirt hol" },
  { "ingilizce": "cosmopolitan", "turkce": "kozmopolit", "okunus": "kazmı palıtin" },
  { "ingilizce": "dirty", "turkce": "kirli", "okunus": "dörti" },
  { "ingilizce": "experience", "turkce": "tecrübe", "okunus": "iks piriyıns" },
  { "ingilizce": "factory", "turkce": "fabrika", "okunus": "fektri" },
  { "ingilizce": "fierce", "turkce": "şiddetli/vahşi", "okunus": "firs" },
  { "ingilizce": "fireplace", "turkce": "şömine", "okunus": "fayır pleys" },
  { "ingilizce": "friendly", "turkce": "dost canlısı", "okunus": "frendli" },
  { "ingilizce": "glad", "turkce": "memnun", "okunus": "gled" },
  { "ingilizce": "gorgeous", "turkce": "muhteşem", "okunus": "gorcıs" },
  { "ingilizce": "iron", "turkce": "demir", "okunus": "ayırn" },
  { "ingilizce": "jungle", "turkce": "orman (balta girmemiş)", "okunus": "cangıl" },
  { "ingilizce": "lightning", "turkce": "şimşek", "okunus": "laytning" },
  { "ingilizce": "mood", "turkce": "ruh hali", "okunus": "mud" },
  { "ingilizce": "mysterious", "turkce": "gizemli", "okunus": "mistiriyıs" },
  { "ingilizce": "negative", "turkce": "olumsuz", "okunus": "negıtiv" },
  { "ingilizce": "nightlife", "turkce": "gece hayatı", "okunus": "nayt layf" },
  { "ingilizce": "opposite", "turkce": "karşı/zıt", "okunus": "apızit" },
  { "ingilizce": "out of focus", "turkce": "odaklanmamış/bulanık", "okunus": "aut of fokıs" },
  { "ingilizce": "parcel", "turkce": "koli/paket", "okunus": "parsıl" },
  { "ingilizce": "photographer", "turkce": "fotoğrafçı", "okunus": "fıtografır" },
  { "ingilizce": "pleased", "turkce": "memnun", "okunus": "plizd" },
  { "ingilizce": "population", "turkce": "nüfus", "okunus": "papyu leyşın" },
  { "ingilizce": "pretend", "turkce": "gibi yapmak", "okunus": "pritend" },
  { "ingilizce": "proud", "turkce": "gururlu", "okunus": "pra ud" },
  { "ingilizce": "qualified", "turkce": "nitelikli", "okunus": "kualifayd" },
  { "ingilizce": "rediscover", "turkce": "yeniden keşfetmek", "okunus": "ri diskavır" },
  { "ingilizce": "reliable", "turkce": "güvenilir", "okunus": "rilaybıl" },
  { "ingilizce": "rude", "turkce": "kaba", "okunus": "rud" },
  { "ingilizce": "salary", "turkce": "maaş", "okunus": "selıri" },
  { "ingilizce": "salty", "turkce": "tuzlu", "okunus": "solti" },
  { "ingilizce": "screen saver", "turkce": "ekran koruyucu", "okunus": "skrin seyvır" },
  { "ingilizce": "sculptor", "turkce": "heykeltıraş", "okunus": "skalp tır" },
  { "ingilizce": "shadow", "turkce": "gölge", "okunus": "şedov" },
  { "ingilizce": "skyscraper", "turkce": "gökdelen", "okunus": "skays krey pır" },
  { "ingilizce": "specialize", "turkce": "uzmanlaşmak", "okunus": "speşı layz" },
  { "ingilizce": "steel", "turkce": "çelik", "okunus": "stil" },
  { "ingilizce": "storm", "turkce": "fırtına", "okunus": "storm" },
  { "ingilizce": "stupid", "turkce": "aptal", "okunus": "styupid" },
  { "ingilizce": "terrified", "turkce": "dehşete düşmüş", "okunus": "terifayd" },
  { "ingilizce": "thunder", "turkce": "gök gürültüsü", "okunus": "tandır" },
  { "ingilizce": "tour", "turkce": "tur", "okunus": "tur" },
  { "ingilizce": "turtle", "turkce": "kaplumbağa", "okunus": "törtıl" },
  { "ingilizce": "unique", "turkce": "benzersiz", "okunus": "yunik" },
  { "ingilizce": "view", "turkce": "manzara", "okunus": "vyu" },
  { "ingilizce": "virtual", "turkce": "sanal", "okunus": "vörçıl" },
  { "ingilizce": "waste", "turkce": "israf etmek/atık", "okunus": "veyst" },
  { "ingilizce": "well-known", "turkce": "iyi bilinen", "okunus": "vel non" },
  { "ingilizce": "ache", "turkce": "ağrı/sızı", "okunus": "eyk" },
  { "ingilizce": "advertisement", "turkce": "reklam", "okunus": "edvörtayzmınt" },
  { "ingilizce": "advice", "turkce": "tavsiye", "okunus": "edvays" },
  { "ingilizce": "allergy", "turkce": "alerji", "okunus": "elıci" },
  { "ingilizce": "ambulance", "turkce": "ambulans", "okunus": "embyılıns" },
  { "ingilizce": "ankle", "turkce": "ayak bileği", "okunus": "engkıl" },
  { "ingilizce": "application form", "turkce": "başvuru formu", "okunus": "eplikeyşın form" },
  { "ingilizce": "archery", "turkce": "okçuluk", "okunus": "arçiri" },
  { "ingilizce": "arm", "turkce": "kol", "okunus": "arm" },
  { "ingilizce": "audition", "turkce": "seçme (oyunculuk)", "okunus": "odişın" },
  { "ingilizce": "be sick", "turkce": "hasta olmak/kusmak", "okunus": "bi sik" },
  { "ingilizce": "belt", "turkce": "kemer", "okunus": "belt" },
  { "ingilizce": "bite", "turkce": "ısırmak", "okunus": "bayt" },
  { "ingilizce": "blow", "turkce": "üflemek", "okunus": "blov" },
  { "ingilizce": "body", "turkce": "vücut", "okunus": "badi" },
  { "ingilizce": "boot", "turkce": "bot", "okunus": "but" },
  { "ingilizce": "boxing", "turkce": "boks", "okunus": "boksing" },
  { "ingilizce": "cap", "turkce": "şapka", "okunus": "kep" },
  { "ingilizce": "chariot", "turkce": "savaş arabası", "okunus": "çeriyıt" },
  { "ingilizce": "chat", "turkce": "sohbet etmek", "okunus": "çet" },
  { "ingilizce": "coach", "turkce": "koç/otobüs", "okunus": "koç" },
  { "ingilizce": "cold", "turkce": "soğuk algınlığı", "okunus": "kold" },
  { "ingilizce": "couch", "turkce": "kanepe", "okunus": "kauç" },
  { "ingilizce": "cough", "turkce": "öksürmek", "okunus": "kof" },
  { "ingilizce": "crash diet", "turkce": "şok diyet", "okunus": "kreş dayıt" },
  { "ingilizce": "depressing", "turkce": "bunalımlı", "okunus": "dipresing" },
  { "ingilizce": "desk", "turkce": "sıra/masa", "okunus": "desk" },
  { "ingilizce": "diarrhoea", "turkce": "ishal", "okunus": "dayı ria" },
  { "ingilizce": "easy-going", "turkce": "uyumlu/rahat", "okunus": "izi goving" },
  { "ingilizce": "equipment", "turkce": "ekipman", "okunus": "ikuipmınt" },
  { "ingilizce": "exercise", "turkce": "egzersiz", "okunus": "eksırsayz" },
  { "ingilizce": "eye", "turkce": "göz", "okunus": "ay" },
  { "ingilizce": "feet", "turkce": "ayaklar", "okunus": "fit" },
  { "ingilizce": "fever", "turkce": "ateş", "okunus": "fivır" },
  { "ingilizce": "finger", "turkce": "parmak", "okunus": "fingır" },
  { "ingilizce": "fit", "turkce": "formda", "okunus": "fit" },
  { "ingilizce": "fitness routine", "turkce": "fitness rutini", "okunus": "fitnıs rutin" },
  { "ingilizce": "flight attendant", "turkce": "kabin memuru", "okunus": "flayt ıten dınt" },
  { "ingilizce": "flu", "turkce": "grip", "okunus": "flu" },
  { "ingilizce": "food poisoning", "turkce": "gıda zehirlenmesi", "okunus": "fud poyzıning" },
  { "ingilizce": "gentle", "turkce": "nazik", "okunus": "centıl" },
  { "ingilizce": "gland", "turkce": "bez (vücutta)", "okunus": "glend" },
  { "ingilizce": "goggles", "turkce": "koruyucu gözlük", "okunus": "gagılz" },
  { "ingilizce": "gymnastics", "turkce": "jimnastik", "okunus": "cimnestiks" },
  { "ingilizce": "hand", "turkce": "el", "okunus": "hend" },
  { "ingilizce": "head", "turkce": "baş", "okunus": "hed" },
  { "ingilizce": "helmet", "turkce": "kask", "okunus": "helmit" },
  { "ingilizce": "high heels", "turkce": "yüksek topuklar", "okunus": "hay hilz" },
  { "ingilizce": "hold your breath", "turkce": "nefesini tutmak", "okunus": "hold yor bret" },
  { "ingilizce": "hoodie", "turkce": "kapüşonlu", "okunus": "hudi" },
  { "ingilizce": "hurt", "turkce": "incinmek/acımak", "okunus": "hört" },
  { "ingilizce": "injury", "turkce": "sakatlık", "okunus": "incıri" },
  { "ingilizce": "jacket", "turkce": "ceket", "okunus": "cekit" },
  { "ingilizce": "jeans", "turkce": "kot pantolon", "okunus": "cinz" },
  { "ingilizce": "knee", "turkce": "diz", "okunus": "ni" },
  { "ingilizce": "leggings", "turkce": "tayt", "okunus": "legingz" },
  { "ingilizce": "leg", "turkce": "bacak", "okunus": "leg" },
  { "ingilizce": "liquid", "turkce": "sıvı", "okunus": "likvid" },
  { "ingilizce": "lose weight", "turkce": "kilo vermek", "okunus": "luz veyt" },
  { "ingilizce": "martial art", "turkce": "dövüş sanatı", "okunus": "marşıl art" },
  { "ingilizce": "mental", "turkce": "zihinsel", "okunus": "mentıl" },
  { "ingilizce": "mind", "turkce": "zihin", "okunus": "maynd" },
  { "ingilizce": "necessary", "turkce": "gerekli", "okunus": "nesısiri" },
  { "ingilizce": "neck", "turkce": "boyun", "okunus": "nek" },
  { "ingilizce": "on the spot", "turkce": "yerinde/hemen", "okunus": "on dı spat" },
  { "ingilizce": "physical", "turkce": "fiziksel", "okunus": "fizikıl" },
  { "ingilizce": "prescribe", "turkce": "reçete yazmak", "okunus": "pris krayb" },
  { "ingilizce": "prescription", "turkce": "reçete", "okunus": "pris kripşın" },
  { "ingilizce": "put on weight", "turkce": "kilo almak", "okunus": "put on veyt" },
  { "ingilizce": "rehydrate", "turkce": "su kaybını gidermek", "okunus": "ri haydreyt" },
  { "ingilizce": "risky", "turkce": "riskli", "okunus": "riski" },
  { "ingilizce": "role", "turkce": "rol", "okunus": "rol" },
  { "ingilizce": "sandals", "turkce": "sandalet", "okunus": "sendılz" },
  { "ingilizce": "scarf", "turkce": "atkı", "okunus": "skarf" },
  { "ingilizce": "sensitive", "turkce": "hassas", "okunus": "sensıtiv" },
  { "ingilizce": "shave", "turkce": "tıraş olmak", "okunus": "şeyv" },
  { "ingilizce": "shirt", "turkce": "gömlek", "okunus": "şört" },
  { "ingilizce": "shorts", "turkce": "şort", "okunus": "şorts" },
  { "ingilizce": "shoulder", "turkce": "omuz", "okunus": "şoldır" },
  { "ingilizce": "skateboarding", "turkce": "kaykay", "okunus": "skeytbording" },
  { "ingilizce": "skip", "turkce": "atlamak (öğün vb.)", "okunus": "skip" },
  { "ingilizce": "skirt", "turkce": "etek", "okunus": "skört" },
  { "ingilizce": "slippery", "turkce": "kaygan", "okunus": "sliperi" },
  { "ingilizce": "sneeze", "turkce": "hapşırmak", "okunus": "sniz" },
  { "ingilizce": "socks", "turkce": "çorap", "okunus": "soks" },
  { "ingilizce": "sore throat", "turkce": "boğaz ağrısı", "okunus": "sor trot" },
  { "ingilizce": "sports vest", "turkce": "spor atleti", "okunus": "sports vest" },
  { "ingilizce": "sprain", "turkce": "burkmak", "okunus": "spreyn" },
  { "ingilizce": "stuff", "turkce": "şeyler/eşya", "okunus": "staf" },
  { "ingilizce": "stuntwoman", "turkce": "kadın dublör", "okunus": "stant vumın" },
  { "ingilizce": "suit", "turkce": "takım elbise", "okunus": "sut" },
  { "ingilizce": "sunglasses", "turkce": "güneş gözlüğü", "okunus": "sanglasız" },
  { "ingilizce": "surfboard", "turkce": "sörf tahtası", "okunus": "sörfbord" },
  { "ingilizce": "surfer", "turkce": "sörfçü", "okunus": "sörfır" },
  { "ingilizce": "swallow", "turkce": "yutmak", "okunus": "svalov" },
  { "ingilizce": "swimsuit", "turkce": "mayo", "okunus": "svimsut" },
  { "ingilizce": "swollen", "turkce": "şişmiş", "okunus": "svolın" },
  { "ingilizce": "sword", "turkce": "kılıç", "okunus": "sord" },
  { "ingilizce": "temperature", "turkce": "sıcaklık/ateş", "okunus": "temprıçır" },
  { "ingilizce": "tie", "turkce": "kravat", "okunus": "tay" },
  { "ingilizce": "toe", "turkce": "ayak parmağı", "okunus": "to" },
  { "ingilizce": "tracksuit", "turkce": "eşofman", "okunus": "trek sut" },
  { "ingilizce": "train", "turkce": "antrenman yapmak", "okunus": "treyn" },
  { "ingilizce": "trainers", "turkce": "spor ayakkabı", "okunus": "treynırz" },
  { "ingilizce": "truck", "turkce": "kamyon", "okunus": "trak" },
  { "ingilizce": "T-shirt", "turkce": "tişört", "okunus": "ti şört" },
  { "ingilizce": "uniform", "turkce": "üniforma", "okunus": "yuniform" },
  { "ingilizce": "waist", "turkce": "bel", "okunus": "veyst" },
  { "ingilizce": "warm up", "turkce": "ısınmak", "okunus": "vorm ap" },
  { "ingilizce": "watch", "turkce": "kol saati", "okunus": "voç" },
  { "ingilizce": "wave", "turkce": "dalga", "okunus": "veyv" },
  { "ingilizce": "wheel", "turkce": "tekerlek", "okunus": "vil" },
  { "ingilizce": "wrist", "turkce": "bilek", "okunus": "rist" },
  { "ingilizce": "annoyed", "turkce": "rahatsız olmuş", "okunus": "ı noy d" },
  { "ingilizce": "atomic bomb", "turkce": "atom bombası", "okunus": "ı to mik bam" },
  { "ingilizce": "audience", "turkce": "seyirci", "okunus": "odiyıns" },
  { "ingilizce": "bark", "turkce": "havlamak", "okunus": "bark" },
  { "ingilizce": "behave", "turkce": "davranmak", "okunus": "bi heyv" },
  { "ingilizce": "being", "turkce": "varlık", "okunus": "bi ing" },
  { "ingilizce": "chase", "turkce": "kovalamak", "okunus": "çeys" },
  { "ingilizce": "clap", "turkce": "alkışlamak", "okunus": "klep" },
  { "ingilizce": "complex", "turkce": "karmaşık", "okunus": "kam pleks" },
  { "ingilizce": "doll", "turkce": "oyuncak bebek", "okunus": "dal" },
  { "ingilizce": "graduate", "turkce": "mezun olmak", "okunus": "grecu eyt" },
  { "ingilizce": "graveyard", "turkce": "mezarlık", "okunus": "greyv yard" },
  { "ingilizce": "heartbroken", "turkce": "kalbi kırık", "okunus": "hart brokın" },
  { "ingilizce": "lecture", "turkce": "ders/konferans", "okunus": "lekçır" },
  { "ingilizce": "literature", "turkce": "edebiyat", "okunus": "litırıçır" },
  { "ingilizce": "lock", "turkce": "kilitlemek", "okunus": "lak" },
  { "ingilizce": "lonely", "turkce": "yalnız", "okunus": "lonli" },
  { "ingilizce": "memory", "turkce": "hafıza/anı", "okunus": "memıri" },
  { "ingilizce": "monster", "turkce": "canavar", "okunus": "manstır" },
  { "ingilizce": "moral", "turkce": "kıssadan hisse/ahlak", "okunus": "morıl" },
  { "ingilizce": "naughty", "turkce": "yaramaz", "okunus": "noti" },
  { "ingilizce": "nervous", "turkce": "gergin", "okunus": "nörvıs" },
  { "ingilizce": "novel", "turkce": "roman", "okunus": "navıl" },
  { "ingilizce": "overjoyed", "turkce": "aşırı mutlu", "okunus": "ovır coyd" },
  { "ingilizce": "poor", "turkce": "fakir", "okunus": "pur" },
  { "ingilizce": "possession", "turkce": "sahiplik/eşya", "okunus": "pızeşın" },
  { "ingilizce": "sack", "turkce": "çuval", "okunus": "sek" },
  { "ingilizce": "shake", "turkce": "sallamak/titremek", "okunus": "şeyk" },
  { "ingilizce": "simple", "turkce": "basit", "okunus": "sim pıl" },
  { "ingilizce": "society", "turkce": "toplum", "okunus": "sı sayıti" },
  { "ingilizce": "stranger", "turkce": "yabancı", "okunus": "streyncır" },
  { "ingilizce": "stressed", "turkce": "stresli", "okunus": "strest" },
  { "ingilizce": "swap", "turkce": "takas etmek", "okunus": "svap" },
  { "ingilizce": "ugly", "turkce": "çirkin", "okunus": "agli" },
  { "ingilizce": "upset", "turkce": "üzgün", "okunus": "ap set" },
  { "ingilizce": "wise", "turkce": "bilge", "okunus": "vayz" },
  { "ingilizce": "yard", "turkce": "avlu/yarda", "okunus": "yard" },
  { "ingilizce": "addicted", "turkce": "bağımlı", "okunus": "ıdiktıd" },
  { "ingilizce": "artificial intelligence", "turkce": "yapay zeka", "okunus": "arti fişıl intelicıns" },
  { "ingilizce": "ballpoint pen", "turkce": "tükenmez kalem", "okunus": "bolpoint pen" },
  { "ingilizce": "breath", "turkce": "nefes", "okunus": "bret" },
  { "ingilizce": "broadcast", "turkce": "yayın yapmak", "okunus": "brod kast" },
  { "ingilizce": "chew", "turkce": "çiğnemek", "okunus": "çu" },
  { "ingilizce": "chum", "turkce": "kafa dengi arkadaş", "okunus": "çam" },
  { "ingilizce": "disadvantage", "turkce": "dezavantaj", "okunus": "disıd vantic" },
  { "ingilizce": "export", "turkce": "ihraç etmek", "okunus": "eksport" },
  { "ingilizce": "fan", "turkce": "hayran/taraftar", "okunus": "fen" },
  { "ingilizce": "flood", "turkce": "sel basmak/taşmak", "okunus": "flad" },
  { "ingilizce": "football ground", "turkce": "futbol sahası", "okunus": "futbol graund" },
  { "ingilizce": "found", "turkce": "kurmak", "okunus": "faund" },
  { "ingilizce": "freshen", "turkce": "tazelemek", "okunus": "freşın" },
  { "ingilizce": "genius", "turkce": "dahi", "okunus": "ciniyıs" },
  { "ingilizce": "glory", "turkce": "şan/şeref", "okunus": "glori" },
  { "ingilizce": "hand-held", "turkce": "elde taşınan", "okunus": "hend held" },
  { "ingilizce": "invention", "turkce": "icat", "okunus": "invenşın" },
  { "ingilizce": "kill", "turkce": "öldürmek", "okunus": "kil" },
  { "ingilizce": "landline", "turkce": "sabit hat", "okunus": "lend layn" },
  { "ingilizce": "launch", "turkce": "fırlatmak/başlatmak", "okunus": "lonç" },
  { "ingilizce": "logo", "turkce": "logo", "okunus": "logo" },
  { "ingilizce": "master", "turkce": "uzmanlaşmak", "okunus": "mastır" },
  { "ingilizce": "private", "turkce": "özel", "okunus": "prayvıt" },
  { "ingilizce": "put someone through", "turkce": "telefonu bağlamak", "okunus": "put samvan tru" },
  { "ingilizce": "respond", "turkce": "yanıt vermek", "okunus": "rispond" },
  { "ingilizce": "rubber", "turkce": "kauçuk/silgi", "okunus": "rabır" },
  { "ingilizce": "simplicity", "turkce": "basitlik", "okunus": "simplisıti" },
  { "ingilizce": "skeleton", "turkce": "iskelet", "okunus": "skelitın" },
  { "ingilizce": "software", "turkce": "yazılım", "okunus": "softver" },
  { "ingilizce": "statistics", "turkce": "istatistik", "okunus": "stı tis tiks" },
  { "ingilizce": "tag", "turkce": "etiketlemek", "okunus": "teg" },
  { "ingilizce": "tree sap", "turkce": "ağaç özü", "okunus": "tri sep" },
  { "ingilizce": "trillion", "turkce": "trilyon", "okunus": "trilyın" },
  { "ingilizce": "trophy", "turkce": "kupa/ödül", "okunus": "trofi" },
  { "ingilizce": "valuable", "turkce": "değerli", "okunus": "velyubıl" },
  { "ingilizce": "version", "turkce": "versiyon", "okunus": "vörşın" },
  { "ingilizce": "waste time", "turkce": "zaman harcamak", "okunus": "veyst taym" },
  { "ingilizce": "accidentally", "turkce": "kazara", "okunus": "eksidentıli" },
  { "ingilizce": "anniversary", "turkce": "yıl dönümü", "okunus": "enıvörsıri" },
  { "ingilizce": "appreciate", "turkce": "takdir etmek", "okunus": "ıprişieyt" },
  { "ingilizce": "astronomer", "turkce": "astronom", "okunus": "ıstranımır" },
  { "ingilizce": "bridesmaid", "turkce": "nedime", "okunus": "braydzmeyd" },
  { "ingilizce": "cabbage", "turkce": "lahana", "okunus": "kebic" },
  { "ingilizce": "collector", "turkce": "koleksiyoncu", "okunus": "kılektır" },
  { "ingilizce": "commemorative", "turkce": "anma/hatıra", "okunus": "kıme mırıtiv" },
  { "ingilizce": "cope", "turkce": "başa çıkmak", "okunus": "kop" },
  { "ingilizce": "demand", "turkce": "talep etmek", "okunus": "dimand" },
  { "ingilizce": "demanding", "turkce": "talepkar/zorlu", "okunus": "dimanding" },
  { "ingilizce": "due", "turkce": "vadesi dolmuş/beklenen", "okunus": "dyu" },
  { "ingilizce": "duplicate", "turkce": "kopya/benzer", "okunus": "dyuplikit" },
  { "ingilizce": "engaged", "turkce": "nişanlı", "okunus": "inge ycd" },
  { "ingilizce": "entrepreneur", "turkce": "girişimci", "okunus": "antrıprınör" },
  { "ingilizce": "fail", "turkce": "başarısız olmak", "okunus": "feyl" },
  { "ingilizce": "forbidden", "turkce": "yasak", "okunus": "forbidın" },
  { "ingilizce": "funeral", "turkce": "cenaze", "okunus": "fyunırıl" },
  { "ingilizce": "garage", "turkce": "garaj/tamirhane", "okunus": "gırac" },
  { "ingilizce": "healthcare", "turkce": "sağlık hizmeti", "okunus": "heltker" },
  { "ingilizce": "honeymoon", "turkce": "balayı", "okunus": "hanimun" },
  { "ingilizce": "influence", "turkce": "etkilemek", "okunus": "influıns" },
  { "ingilizce": "keyboard", "turkce": "klavye/org", "okunus": "ki bord" },
  { "ingilizce": "life expectancy", "turkce": "ortalama yaşam süresi", "okunus": "layf ikspektınsi" },
  { "ingilizce": "married", "turkce": "evli", "okunus": "merid" },
  { "ingilizce": "memorabilia", "turkce": "hatıra eşyalar", "okunus": "memıra biliya" },
  { "ingilizce": "never-ending", "turkce": "bitmeyen", "okunus": "nevır ending" },
  { "ingilizce": "optimistic", "turkce": "iyimser", "okunus": "aptımistik" },
  { "ingilizce": "peer", "turkce": "akran", "okunus": "pir" },
  { "ingilizce": "pessimistic", "turkce": "kötümser", "okunus": "pesımistik" },
  { "ingilizce": "physicist", "turkce": "fizikçi", "okunus": "fizisist" },
  { "ingilizce": "poetry", "turkce": "şiir sanatı", "okunus": "poıtri" },
  { "ingilizce": "pregnant", "turkce": "hamile", "okunus": "preg nınt" },
  { "ingilizce": "raindrop", "turkce": "yağmur damlası", "okunus": "reyndrap" },
  { "ingilizce": "regret", "turkce": "pişmanlık", "okunus": "rigret" },
  { "ingilizce": "renewed", "turkce": "yenilenmiş", "okunus": "ri nyud" },
  { "ingilizce": "repair", "turkce": "tamir etmek", "okunus": "riper" },
  { "ingilizce": "resources", "turkce": "kaynaklar", "okunus": "ri sorsız" },
  { "ingilizce": "rocket", "turkce": "roket", "okunus": "rakit" },
  { "ingilizce": "selfish", "turkce": "bencil", "okunus": "selfiş" },
  { "ingilizce": "serious", "turkce": "ciddi", "okunus": "siriyıs" },
  { "ingilizce": "servant", "turkce": "hizmetçi", "okunus": "sörvınt" },
  { "ingilizce": "split up", "turkce": "ayrılmak", "okunus": "split ap" },
  { "ingilizce": "stick", "turkce": "sopa/baston", "okunus": "stik" },
  { "ingilizce": "surrogate", "turkce": "taşıyıcı (anne)", "okunus": "sörı git" },
  { "ingilizce": "tragedy", "turkce": "trajedi", "okunus": "trecidi" },
  { "ingilizce": "unsaid", "turkce": "söylenmemiş", "okunus": "an sed" },
  { "ingilizce": "wealth", "turkce": "servet", "okunus": "velt" },
  { "ingilizce": "widowed", "turkce": "dul kalmış", "okunus": "vidov d" },
  { "ingilizce": "barbecue", "turkce": "mangal", "okunus": "barbikyu" },
  { "ingilizce": "biscuit", "turkce": "bisküvi", "okunus": "biskit" },
  { "ingilizce": "boomerang", "turkce": "bumerang", "okunus": "bumıreng" },
  { "ingilizce": "campus", "turkce": "kampüs", "okunus": "kempıs" },
  { "ingilizce": "coincidence", "turkce": "tesadüf", "okunus": "ko insidıns" },
  { "ingilizce": "confuse", "turkce": "kafasını karıştırmak", "okunus": "kınfyuz" },
  { "ingilizce": "drop out", "turkce": "okulu bırakmak", "okunus": "drop aut" },
  { "ingilizce": "economics", "turkce": "ekonomi", "okunus": "ikonomiks" }
];